### ISSUE TITLE
Imports 

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/web#1]
Add additional password manager options to the import process:
- [x] LastPass csv
- [x] 1Password 1pif
- [x] KeePass
- [x] Dashlane csv
- [x] Keeper csv
- [x] Enpass csv
- [x] SafeInCloud csv
- [x] SafeInCloud xml
- [x] Padlock csv
- [x] Sticky Password xml
- [x] Firefox Password Exporter xml
- [x] Chrome csv
- [x] UPM csv
- [x] Password Dragon xml
- [x] Password Safe xml

**Comment by Juginabi** [comment]
Example keepass2.30 XML database export can be found here: http://pastebin.com/NWS2u3HD

It contains three example user credentials stored in sub categories. Database also attached to this post as zip file containing one file named ExampleDatabase.kbdx. Password for this database file is: example_password

Seems like a nice software! I'm gonna keep an eye on this!

[ExampleDatabase.zip](https://github.com/bitwarden/web/files/519333/ExampleDatabase.zip)

**Comment by kspearrin** [comment]
Thank you for this. Is XML the only export option available?

**Comment by yunake** [comment]
KeePassX 2 supports export to CSV

**Comment by digitalknk** [comment]
Another one that may be easy to import is SafeInCloud. Currently using this from LastPass, wouldn't love to be able to import from it.

**Comment by jeremyw24** [comment]
+1 for SafeInCloud - here is a clean sample from their CSV: http://pastebin.com/ArLj7xNJ and from their Text Export: http://pastebin.com/6BtUViYQ if it helps.

**Comment by kspearrin** [comment]
@jeremyw24 should be very easy to add. Will add soon.

**Comment by kspearrin** [comment]
@jeremyw24 @digitalknk does safe in cloud support folders at all?

**Comment by jeremyw24** [comment]
@kspearrin no, not quite. They use a 'tag' system so all passwords can be viewed together or by tags such as business, personal, web etc. You can see the tags on the left side in this image from their site: https://www.safe-in-cloud.com/en/images/free_desktop_app.png

**Comment by kspearrin** [comment]
@jeremyw24 I'm guessing that's not included in the export though? I don't see any data for that in your example.

**Comment by jeremyw24** [comment]
@kspearrin  No, not in their CSV/TXT exports but I did just check their XML Export which does include the tags on the export. I can pastebin a sample of that if you like.

**Comment by kspearrin** [comment]
@jeremyw24 That's be great. I'll add csv support for now since that's very simple. Coming right up with a commit.

**Comment by kspearrin** [comment]
https://github.com/bitwarden/web/commit/d17211ff864c24965dc747f4ec14caaaec7afdcf SafeInCloud csv support

**Comment by kspearrin** [comment]
https://github.com/bitwarden/web/commit/85efba92e64c8807ee0080fedf52c4d094d8292f KeyPass 2.x XML support

**Comment by kspearrin** [comment]
@Juginabi @jeremyw24 @digitalknk SafeInCloud and KeyPass imports have been pushed live and are now available in the web vault: https://github.com/bitwarden/web/releases/tag/v1.1.0

Let me know if you have any issues with them. Thanks for the example info.

**Comment by jeremyw24** [comment]
@kspearrin Oh No! Something went wrong! - Error when importing safeincloud csv :(

**Comment by kspearrin** [comment]
@jeremyw24 is there something different about your CSV data than the file you provided my as an example?

**Comment by doubledeee** [comment]
Tool looks great so far!  I was trying to import from LastPass by following your documentation, but when I try to import, it says "Oh No!  Something went wrong!"  Anyone else having this issue with LastPass?

**Comment by blindly** [comment]
Example of 1Password export in csv format.

[1Password( 2 items and 0 folders).csv.zip](https://github.com/bitwarden/web/files/527360/1Password.2.items.and.0.folders.csv.zip)

**Comment by kspearrin** [comment]
@doubledeee See this issue: https://github.com/bitwarden/web/issues/7 . There is a fix here: https://github.com/bitwarden/web/issues/7#issuecomment-253567666

@jeremyw24 I think the above mentioned problem with LastPass is what is causing your problem too. Currently bitwarden requires a URL and Password for every site. Other managers do not require this. I will be making an update tonight that removes this requirement from bitwarden as well so all should work. In the meantime you could edit your data and add URLs and passwords to make this work.

**Comment by jeremyw24** [comment]
@kspearrin Negative, the sample I supplied you was the file I tried to import - I just did a new export from SafeInCloud and tried again with that but got the same error. 

Will wait to see after your update, SafeInCloud has URL registered for sites but its not a requirement I did notice it exports the URL. Personally all mine have URL as I like that it grabs the favicon from the site and displays it in the password list.

**Comment by kspearrin** [comment]
@jeremyw24 I just imported this just fine on my account:

```
"Title","Login","Password","URL","Notes"
"500px","username","xxxxxx","http://500px.com",""
```

This is what you tried too?

**Comment by kspearrin** [comment]
Released v1.1.1 with more fixes for all.

**Comment by kspearrin** [comment]
@blindly Does 1Password support folders through csv export?

**Comment by jeremyw24** [comment]
@kspearrin Safe In Cloud works now after the 1.1.1 update.

**Comment by kspearrin** [comment]
@jeremyw24 Great. Do you have a XML example you can provide so that I can properly support tags -> folders?

**Comment by jeremyw24** [comment]
@kspearrin Ill put something together for you, their XML is a nasty mess. Leave it with me.

**Comment by jeremyw24** [comment]
@kspearrin never mind, didnt take that long: http://pastebin.com/vcDaziS8

**Comment by kspearrin** [comment]
Added padlock CSV import: https://github.com/bitwarden/web/commit/2d11bef2622ad71bd3b49b90a198e04d2f46678c

@jeremyw24 Can you help me understand what those nodes are and how they would relate to bitwarden?

**Comment by jeremyw24** [comment]
Yep, the different card types are for different things ie you can save a email account with specific details or your credit card capturing the CCV and expiration, they just have pre-defined templates as you can see in their XML <card .... title="Website" ... /card> 

I woud suspect in your case the only relevant fields are the card title, <field Name="login"/> and <field type="password"/>.

In saying that Ive not had a look how you are parsing this data on the import, but those fields should do the job.

**Comment by kspearrin** [comment]
@jeremyw24 So from what I can tell it looks like card = a bitwarden site and label = a bitwarden folder?

In your example you have 3 folders:

- Business
- Confluence
- Personal

and 3 sites:

- VW Confluence, Folder Personal
- AGL, Folder Personal
- Google, Folder Personal

Is this right?

**Comment by jeremyw24** [comment]
@kspearrin Yep, thats right. Nailed it.

**Comment by blindly** [comment]
@kspearrin I should have noted I used 1Password 6 under Mac. Having said that tho, when i attempt to export on mac, I have some fields available by default: 

> Notes,Password,Title,Type,URL,Username

You can manipulate the order you want them from there, so if you want to make Username first, it's just a matter of drag and drop of the field. I do realize that doesn't match what they show online. Perhaps what's online is for imports. For exports, there's a bit more liberty. 

I was both a standalone vault as well as a 1password online vault. The folders are entirely gone from the online vault but available on the standalone vault. Folders are not included in the supported data fields.

I did an export of bitwarden and noticed the header fields:

> Title,URI,Username,Password,Notes,Folder

I tried to match the headers on the 1password export and then importing as bitwarden csv. It failed. It looks like 1Password uses quotes and the Bitwarden csv does not. Removing the quotes allows it to import. As a side note, if i added a folder name to the 1password csv exported file set to match the Bitwarden format, it doesn't import into the existing folder and instead creates a new one.

**Comment by kspearrin** [comment]
@blindly I think I'm just going to write a parser for the 1pif file instead since I think it is more standardized.

**Comment by kspearrin** [comment]
@blindly 1password 1pif done. https://github.com/bitwarden/web/commit/0ae11cc40c222ea14aa87ddbf07aa404cc23af54

Will be available next release.

**Comment by kspearrin** [comment]
@jeremyw24 SafeInCloud XML now available. Would you be able to test it? https://github.com/bitwarden/web/commit/30d19b4ee152e9713baff06b1a6e181a11b61238

**Comment by scottdetoffol** [comment]
Using Keepass 2.34 export to XML (2.0), then import Keepass (XML) on bitwarden 1.2.0. I'm getting the something went wrong error message.

**Comment by kspearrin** [comment]
Hey @scottdetoffol, thanks for the report. are you familiar with using your browser tools? If so, could you look for the import API call and see What the real error message is?

**Comment by digitalknk** [comment]
@kspearrin The SafeInCloud XML import works great; I do not see any issues with it. Excellent work!

**Comment by digitalknk** [comment]
@kspearrin For Enpass, what are you looking to allow the user to import? Enpass has a lot of options available.

**Comment by kspearrin** [comment]
@digitalknk I am not familiar with all of the features enpass offers or what their export options looks like in relation to these features. However, if they offer it, a CSV, XML, and/or JSON sample would be best.

**Comment by digitalknk** [comment]
@kspearrin I'll provide something to you sometime this week, want to make sure I get a full dataset for you. FYI it exports it out as a plan txt file most likely CSV or XML.

**Comment by blindly** [comment]
@kspearrin Importing 1Password shows this message.

> Please wait. We are now importing all of your data. Do not close this window. You will be redirected to your vault when the import has completed.

Error log shows: Uncaught SyntaxError: Unexpected token ] in JSON at position 9700

This was importing 15 items.

`
    "createdAt": 1445788840,
    "typeName": "webforms.WebForm"
}, ]

`

**Comment by kspearrin** [comment]
@blindly Can you send me a scrubbed sample file?

**Comment by kspearrin** [comment]
Added firefox and chrome exports.

**Comment by Igetin** [comment]
Exported my database from KeePass 2.32 as XML and imported it to bitwarden through the web vault, which resulted in completely empty entries. What might be the problem here?

**Comment by kspearrin** [comment]
@lgetin  what it be possible for you to generate an example export from key pass that doesn't work that you could send to me via email?  The example that I was able to create was what I wrote the code for the import off of and it works so I'm not sure what's different about yours. Thanks

**Comment by Igetin** [comment]
@kspearrin Hmm, I exported and imported the database again and now the entries appeared correctly with all information. I compared the previous and the newly exported XML, and there were 0 differences between them. So a bug must've happened in the import process itself in the web vault.

**Comment by kspearrin** [comment]
@Igetin Very weird. You are not the first person to report the empty import like that, though you are the first to report that simply trying it again solved the problem. I have a feeling that file encodings may be causing some issues for folks. Are you able to confirm that both files are saved as UTF-8? Do you have any non-english characters in there?

**Comment by Igetin** [comment]
@kspearrin Both files have several non-English characters, and both were saved with UTF-8 encoding.

I tried the exporting and

**Comment by blindly** [comment]
Enpass 5.3.0 Portable export

[Enpass_2016-11-11_11-36-21.txt](https://github.com/bitwarden/web/files/586256/Enpass_2016-11-11_11-36-21.txt)

**Comment by kspearrin** [comment]
sticky password example export: http://pastebin.com/rm6aDjk2

**Comment by Plonq** [comment]
Enpass can now export in CSV (v5.4.0.4), although I think it has its own format. Attached is an example with a few different types of entries.
Format is basically: Name, Field, Value, Field, Value, [more field-value pairs], Note
For secure notes, there are no fields, so it's just Name, Note

[Enpass_2016-12-22_09-16-58.txt](https://github.com/bitwarden/web/files/667510/Enpass_2016-12-22_09-16-58.txt)

**Comment by kspearrin** [comment]
@Plonq Great, I'll check into Enpass again soon.

**Comment by kspearrin** [comment]
@Plonq @blindly @digitalknk - Enpass csv added for next release https://github.com/bitwarden/web/commit/11787193ed63d3735f919993daa65d811ea0df47

**Comment by StephenCleary** [comment]
I'd love to see support for PasswordSafe `psafe` files.

**Comment by kspearrin** [comment]
@StephenCleary Done (via Password Safe XML export). See https://github.com/bitwarden/web/commit/6cbd618fb8e6a1fecb1c636c57cccaa6dce118f7

Will go next release as well.

**Comment by kspearrin** [comment]
I added an "experimental" Dashlane csv importer (https://github.com/bitwarden/web/commit/f86bce970ed7e0a6a556a9908958f3f7e2573bb8). Keep in mind that it may not be 100% accurate for each entry (it may make some mistakes due to the bad CSV format from Dashlane), but it will definitely help move a majority of the data over fairly accurately.

**Comment by Plonq** [comment]
Thanks for adding Enpass support.

I've found a minor bug relating to importing, hopefully this is the correct place to put it. Importing doesn't work when the file has multiple extensions. For example, by default Enpass exports as `Enpass_yyyy-mm-dd_hh-mm-ss.csv.txt`, and importing as is results in lots of entries with the name "--" and no data (all other fields are empty). Renaming anf removing the ".txt" results in a successful import.

**Comment by kspearrin** [comment]
Sticky Password (xml) added: https://github.com/bitwarden/web/commit/6bf6cc365b967e1f2077d65d1d3a42387ef448b3

**Comment by kspearrin** [comment]
Closing this task since I have added all requested importers. If you need another importer feel free to open a new issue.
