### ISSUE TITLE
Remove or allow opt out of Google Analytics

### ISSUE THREAD

**Issue by OmgImAlexis** [bitwarden/web#10]
If you need to collect analytics at least look into an alternative to Google's. I've linked to an issue from when Homebrew decided to use Google Analytics which should show you why this is a bad idea to start with and what some alternatives are.

Ref: https://github.com/Homebrew/brew/issues/142

**Comment by kspearrin** [comment]
Thanks for the suggestion. I will be adding an opt out flag soon for the browser and mobile products, but won't be here for the web project. If you are worried about google analytics on the web you can always use a nice extension like ghostery.

https://chrome.google.com/webstore/detail/ghostery/mlomiejdfkolichcflejclcbmpeaniij?hl=en

**Comment by OmgImAlexis** [comment]
Why not make it that if people opt-out on their account that all Google analytics are disabled?

**Comment by kspearrin** [comment]
It needs to be a device setting because there are parts of the application that do not require a user to be logged in.

**Comment by OmgImAlexis** [comment]
Tracking a user until they login to the web app where you can then check if they want to be tracked or not seems to be a fair compromise.
