### ISSUE TITLE
Self hosted version web doesn show colelctions/folders with MS Edge browser

### ISSUE THREAD

**Issue by alancivita** [bitwarden/web#1005]
## Describe the Bug

Bitwarden web page on self hosted version doesn't show folders or collection with Microsoft Edge. It works fine with Chrome/Firefox/Safari 
Any tips?

## Environment

- Operating system: Ubuntu 20.04
- Build Version: latest available
- Self Hosted: true

**Comment by alancivita** [comment]
Sure,
Version 91.0.864.37 (Build ufficiale) (x86_64) MacOS, but i can reproduce it on Windows 10 as well

<img width="479" alt="image001" src="https://user-images.githubusercontent.com/23634711/120510596-ddaedf00-c3c9-11eb-87e4-a7999bb18ede.png">

HAppy to provide more info or debug

Alan

**Comment by alancivita** [comment]
it looks like the same issue is affecting Chrome version 91.0.4472.77 both on MAc and Windows.
Firefox version 89.0 works fine on both.

**Comment by Virinum** [comment]
I've tested this on Windows 10 with Edge `91.0.864.37` and Chrome `91.0.4472.77`. In both browsers I see my folders.

Maybe you can see some error logs in the console of developer tools:

Press F12, reload page, login and look at the console if there's some red text.

**Comment by alancivita** [comment]
Hi, this is the error i get:
`core.js:6210 ERROR Error: Uncaught (in promise): TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Set (<anonymous>)
    at t.<anonymous> (groupings.component.ts:65)
    at main.8bb68b321ef3db0b700c.js:1
    at Object.next (main.8bb68b321ef3db0b700c.js:1)
    at a (main.8bb68b321ef3db0b700c.js:1)
    at t.invoke (zone.js:400)
    at Object.onInvoke (core.js:28591)
    at t.invoke (zone.js:399)
    at e.run (zone.js:160)
    at zone.js:1318
    at j (zone.js:1255)
    at zone.js:1162
    at s (main.8bb68b321ef3db0b700c.js:1)
    at t.invoke (zone.js:400)
    at Object.onInvoke (core.js:28591)
    at t.invoke (zone.js:399)
    at e.run (zone.js:160)
    at zone.js:1318
    at t.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28578)
qi @ core.js:6210
handleError @ core.js:6258
next @ core.js:29198
t.__tryOrUnsub @ Subscriber.js:192
t.next @ Subscriber.js:130
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
emit @ core.js:25940
(anonymous) @ core.js:28617
t.invoke @ zone.js:400
e.run @ zone.js:160
runOutsideAngular @ core.js:28520
onHandleError @ core.js:28617
t.handleError @ zone.js:404
e.runGuarded @ zone.js:174
t @ zone.js:1113
Zone.__load_patch.n.microtaskDrainDone @ zone.js:1125
m @ zone.js:627`

**Comment by Virinum** [comment]
Does the error also occur with other accounts? Can you create a new one and check if it also happens there?

**Comment by alancivita** [comment]
Yes, the error occurs with every account - Please note that we are using Microsoft AD integration and that, at the moment, every user is marked as Owner.

**Comment by eliykat** [comment]
Hi @alancivita, this looks like a similar issue we had on our desktop client: https://github.com/bitwarden/desktop/issues/894. That's been fixed and I thought the issue was isolated to that client, but clearly not. I'll get to work on it as high priority.

In the meantime, the following should fix the issue:
* clear local browser data
* do not collapse any of your folders/sub-folders or collections/sub-collections (it's the code that saves the collapsed state that throws the error)
