### ISSUE TITLE
Bitwarden Send Timestamp Issue 

### ISSUE THREAD

**Issue by Krychaz** [bitwarden/web#1006]
## Steps To Reproduce

1. Go to bitwarden vault 
2. Click on your online vault 
3. Create a Send, note the time on your device 

## Expected Result
A bitwarden send that has the same timestamp as the device it was created on

## Actual Result
Send link with a different timestamp on it

## Screenshots or Videos

![Bitwarden Time 01](https://user-images.githubusercontent.com/36608718/120466237-bc80cb00-c396-11eb-9335-aa979a51255f.jpeg)
![Bitwarden Time 02](https://user-images.githubusercontent.com/36608718/120466254-c0145200-c396-11eb-98b1-ac2d3d5c5670.jpeg)

## Environment

- Device: Web Vault, OnePlus 8T
- Operating system: Android 11
- Build Version: 2.10.0 (3516)

**Comment by Virinum** [comment]
Do you mean this timestamp? 
![image](https://user-images.githubusercontent.com/42373861/120472718-877c7480-c3a6-11eb-9be7-bb4ddea925de.png)

It's not the creation date but the deletion date. In my case, I chose 7 days.

**Comment by Krychaz** [comment]
Good catch! Case closed in that case.
