### ISSUE TITLE
Possible DOMXSS in webauthn-fallback.ts

### ISSUE THREAD

**Issue by bt-nia** [bitwarden/web#1020]
Hi!

The Snyk Code scanner I used to review some of the code of this project mentioned these two code sections, where input is being directly used to influence the `innerHTML`
https://github.com/bitwarden/web/blob/82ec4b12f7393c4479df494d7e82e38da0d275bc/src/connectors/webauthn-fallback.ts#L117

https://github.com/bitwarden/web/blob/82ec4b12f7393c4479df494d7e82e38da0d275bc/src/connectors/webauthn-fallback.ts#L107

In case the `message` parameter can be influenced by an attacker, this could lead to an XSS issue. Looking at this, it does not seem too dangerous, but at the same time it would be better to encode the string before putting it into the `innerHTML` or put the content into `textContent` instead. 
More details: https://stackoverflow.com/questions/30661497/xss-prevention-and-innerhtml

**Comment by cscharf** [comment]
Hi @bt-nia , thanks for the inquiry on this. While this would generally be a concern, especially if this were user-generated content, these are methods contained in an isolated component which are simply showing messages from an exception or trusted translation source messages (such as `"webAuthnSuccess": "<strong>WebAuthn verified successfully!</strong><br>You may close this tab."`. In these scenarios we're using the HTML as a way of breaking up our message displayed in a more user-friendly way. I don't believe we have any plans to change this at this time.

Thanks again! Closing this issue. If you do happen to find or think you've found any vulnerabilities in the future, please consider using our program on [HackerOne](https://hackerone.com/bitwarden) to submit those to our security team.

**Comment by cscharf** [comment]
Actually, re-opening this for re-evaluation. After more careful review and follow up internally we feel it would be best to address this even if there is very low risk.
