### ISSUE TITLE
Unable to use Microsoft Authentication with 2FA

### ISSUE THREAD

**Issue by alistair23** [bitwarden/web#103]
When trying to setup 2FA with the Microsoft authentication I see this error after trying to enter "Enter the resulting 6 digit verification code from the app"

Errors have occurred
    Invalid token.

I have tried multiple times, both using the QR code and manually entering the key.

**Comment by kspearrin** [comment]
Is your devices system time correct?

**Comment by alistair23** [comment]
It is, I used the same app to login to GitHub to create the issue.

**Comment by kspearrin** [comment]
Hmm, that's weird. I'll have to take a look at MS authenticator to see what's up.

**Comment by alistair23** [comment]
Yeah, AFAIK it follows the standard spec. Let me know if you want me to test anything or report any logs.

**Comment by kspearrin** [comment]
When you entered the key manually did you remove the spaces?

**Comment by alistair23** [comment]
Yes, I did

**Comment by kspearrin** [comment]
Try without spaces.

**Comment by alistair23** [comment]
I tried the QR code, manually entering with spaces and manually entering without spaced. All three generate the same tokens and none of them work.

**Comment by kspearrin** [comment]
I just tested it with MS Authenticator on iOS and it worked just fine (used QR code with camera). I'm not sure. Try removing the account and adding it back to MS authenticator?

**Comment by alistair23** [comment]
I just cleared everything I could and it seems to be working now. Not sure what was going on yesterday. Thanks for your help.
