### ISSUE TITLE
locked bitwarden vault unable to unlock

### ISSUE THREAD

**Issue by hardmooth** [bitwarden/web#1031]
## Describe the Bug

Repeatedly, yet not everytime, I come back to an already open Tab of the Bitwarden Web Vault at https://vault.bitwarden.com/#/lock and pressing on Unlock/Entsperren shows no action (and I can thus not unlock the vault)
(I of course entered the correct password)

Noticeable is the 
> Angemeldet als __$1__ auf bitwarden.com. 
> (Logged in as __$1__ on bitwarden.com)

The following help to exit this deadlock:

* clicking on Abmelden/logout and then do a complete login
* closing the tab and opening another

## Steps To Reproduce

Sadly this only happens sometimes.

## Expected Result

I would expect my UserName/E-Mail to show up instead of __$1__
> Angemeldet als <UserName> auf bitwarden.com. 
> (Logged in as <UserName> on bitwarden.com)

and, of course, to actually log me in when clicking on login/Anmelden

## Actual Result

As described above:
* I can't login without reopening the tab or logging out
* I am told to be logged in as __$1__

## Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/39583404/121991420-eb883b00-cd9f-11eb-931c-cbf3fc0c83aa.png)

## Environment

- Operating system: Windows 10
- Browser: Firefox 89.0 32Bit
- Build Version 2.20.4

**Comment by sso-bitwarden** [comment]
Thank you for your report. This issue has been fixed, pending a release.

https://github.com/bitwarden/web/issues/978
