### ISSUE TITLE
"An error has occurred" when setting password hint to master password

### ISSUE THREAD

**Issue by Scoder12** [bitwarden/web#1037]
## Describe the Bug

When registering an account, if the master password hint is the same as the password, a toast pops up saying "An error has occurred". 

## Steps To Reproduce

1. Click register
2. Fill out the form
3. Set the password hint field to the master password

## Expected Result

The toast says "password hint cannot be the same as master password" or similar. 

## Actual Result

A toast that says "An error has occurred". 

## Additional Context

Obviously you shouldn't actually do this but the error is pretty confusing.

**Comment by sov-j** [comment]
Just tested on Version 2.21.1 and the toast now says exactly what Expected Result requests, so this one may be closed probably.
