### ISSUE TITLE
Lastpass importer does not replace HTML encoding for special characters

### ISSUE THREAD

**Issue by jvican** [bitwarden/web#104]
First off, awesome project.
  
When importing from Lastpass, characters like `<` are represented as `&lt;` and the importer does not handle them gracefully. When authenticating in a website with such a password, the authentication fails. I presume this is a bug.

**Comment by kspearrin** [comment]
Please see docs here. This is a lastpass bug.

https://help.bitwarden.com/article/import-from-lastpass/

**Comment by jvican** [comment]
Thank you, that's a good catch.
