### ISSUE TITLE
Please let users configure how long to display the Bitwarden popup. 

### ISSUE THREAD

**Issue by catgun** [bitwarden/web#105]
Please let users configure how long to display the Bitwarden popup. Right now, if I switch browser focus, it disappears immediately. This is very frustrating, as I often use Bitwarden to enter passwords in other browsers, and other browser windows.

**Comment by kspearrin** [comment]
I believe this issue is in the wrong repo. We already do this in the web. Can you confirm and please open this issue in https://github.com/bitwarden/browser if that is the appropriate place?

**Comment by catgun** [comment]
Moved to the other repo.
