### ISSUE TITLE
Return to My Vault link from User menu in Business Portal does not work

### ISSUE THREAD

**Issue by luckman212** [bitwarden/web#1057]
## Describe the Bug

The **Return to My Vault** link from User menu in Bitwarden Business Portal does not work. The link seems to point to `https://portal.bitwarden.com/#` instead of `https://vault.bitwarden.com/#`

## Steps To Reproduce

1. log in to https://portal.bitwarden.com/
2. click user icon
3. click _Return to My Vault_ 
4. Nothing happens...

## Version

According to the page footer: `Version 1.41.4`

## Screenshot 
![CleanShot 2021-07-01 at 19 55 20](https://user-images.githubusercontent.com/1992842/124201556-693d8d80-daa6-11eb-8d68-84414eb955ec.png)

**Comment by cscharf** [comment]
@eliykat , I'm not sure we ever figured out what that button was supposed to do. TLDR; I would prefer we simply remove it. We don't have a backwards path to re-opening and logging in/unlocking the vault from the business portal as the business portal is fully outside of the context of the vault's cryptographic scope and while server-side we SSO to the business portal from the web vault token, it doesn't go both ways in that sense. Also, we open the business portal in a new tab/window, `target="_blank"` so returning would be just switching browser tabs presumably. All-in-all, the option looks good and I'm sure we must have had some great plan for it at some point, but I know the other desire is to deprecate the business portal in the near future so let's just remove that option for now so it's not confusing.

**Comment by luckman212** [comment]
Thanks for the comments, what is the plan for the features currently being provided by the business portal? They will be somehow merged into the main vault portal?

**Comment by cscharf** [comment]
> They will be somehow merged into the main vault portal?

Yes, exactly. The only thing currently in the business portal that is _not_ also in the main vault is SSO configuration, so we'll be migrating that over sometime soon. Conceptually the business portal seemed like a great idea but we've hit too many constraints in other things we're doing and planning to keep it going.
