### ISSUE TITLE
Please give users the option to display the password when entering it

### ISSUE THREAD

**Issue by catgun** [bitwarden/web#106]
Please give users the option to display the password when entering it. As it is, I have to enter the password, then save it, then view it make sure I entered it correctly, then edit it, then save it again. Very frustrating.

**Comment by kspearrin** [comment]
We've been meaning to add this to the browser extension.

**Comment by kspearrin** [comment]
I believe this issue is in the wrong repo. We already do this in the web. Can you confirm and please open this issue in https://github.com/bitwarden/browser if that is the appropriate place?

**Comment by catgun** [comment]
Moved to https://github.com/bitwarden/browser repo.
