### ISSUE TITLE
Verification code sent to old email address after changing new email address

### ISSUE THREAD

**Issue by Dr4m9s1b16** [bitwarden/web#1063]

**Comment by SergeantConfused** [comment]
Hi @haranloga,

The email address used for your login and the email address used for 2FA are unlinked. After changing the email address that your account is registered on, you can also change the email address that's used for 2FA like so: https://bitwarden.com/help/article/setup-two-step-login-email/

If you have any further questions, please do not hesitate to get in touch with us here: https://bitwarden.com/contact/


All the best,
