### ISSUE TITLE
400 on org user page

### ISSUE THREAD

**Issue by codyrandall** [bitwarden/web#1065]
## Describe the Bug
When I load my org's users list page, i get a spinner and the following 400

ERROR Error: Uncaught (in promise): t: {"response":{"Object":"error","Message":"Organization Keys already exist","ValidationErrors":null,"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null},"message":"Organization Keys already exist","validationErrors":null,"statusCode":400}

## Steps To Reproduce

Accepted invited user into org. Reloaded page.

## Expected Result

The page to load

## Actual Result

The page doesn't load.

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: [e.g. Firefox 73.0.1]
- Build Version (Bottom of the page): [2.13.0]

**Comment by eliykat** [comment]
This is a known regression from the last release and has been fixed by https://github.com/bitwarden/web/pull/1055. It will be included in an upcoming patch release.
