### ISSUE TITLE
Vault locks when page is refreshed

### ISSUE THREAD

**Issue by neil210** [bitwarden/web#1068]
## Describe the Bug

I press refresh when browsing https://vault.bitwarden.com/# to update the list of entries with new ones added by my colleagues. Instead of the list being refresh the vault locks.

## Steps To Reproduce

1. Browse to https://vault.bitwarden.com/
2. Login
3. Press refesh (F5)

## Expected Result

My list of sites gets refreshed

## Actual Result

Vault locks

## Environment

- Operating system: Windows 10
- Browser: Chrome Version 91.0.4472.124 (Official Build) (64-bit)
- Build Version (Bottom of the page): Version 2.21.0

**Comment by tgreer-bw** [comment]
Hi @neil210! Refreshing the page re-loads the entire javascript application, which causes your vault to lock (this is intended). The vault will refresh automatically as you navigate between areas (i.e. Vault/Settings/Tools/)

**Comment by neil210** [comment]
I am used to pressing F5 in my Lastpass vault. It's hard to change my behaviour. Can we at least have a large refresh button. I was unable to get my sites to refresh without logging out and then back in again.

**Comment by tgreer-bw** [comment]
Totally understand habits and muscle memory 😄 

Feel free to add feature requests (such as the refresh button, or change in refresh behavior) here: https://community.bitwarden.com/c/feature-requests/5

We use GitHub for bug/issue tracking and our forums for feature requests and their related discussion 🤘

**Comment by eliykat** [comment]
Thanks @tgreer-bw! As feature requests are best discussed on the forums, I'll close this thread here.
