### ISSUE TITLE
Please add a second password confirmation field

### ISSUE THREAD

**Issue by catgun** [bitwarden/web#107]
Please add a second password confirmation field, to make sure that we've entered it correctly. (Look at how KeepassX does it.)

**Comment by kspearrin** [comment]
I believe this issue is in the wrong repo. We already do this in the web. Can you confirm and please open this issue in https://github.com/bitwarden/browser if that is the appropriate place?

**Comment by catgun** [comment]
Moved to https://github.com/bitwarden/browser repo.
