### ISSUE TITLE
Lastpass CSV import might be broken

### ISSUE THREAD

**Issue by Daniele122898** [bitwarden/web#1083]
## Describe the Bug

I have opened an issue on the extension site but i think it might be the web import that is broken and not the autofill. I just switched from lastpass to bitwarden and ofc made a lastpass export and then imported the csv file into bitwarden. 

It seems now that many passwords have a whitespace in front and thus when autofilling do not autofill correctly. 

## Steps To Reproduce

1. Create lastpass password export
2. Import unmodified CSV file into bitwarden
3. See some (not all?) passwords have a whitespace infront
4. Fail autofill because of it

## Expected Result

Correctly import lastpass csv file

## Actual Result

Added whitespace to front of passwords

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/20451770/125816205-fabdd589-c9d6-45c1-bdc6-04f583189888.png)

## Environment

- Operating system: Windows 10
- Browser: Chrome 91.0.4472.124
- Build Version (Bottom of the page): 2.21.1

**Comment by eliykat** [comment]
Were you able to confirm that this is an import vs. autofill issue? If so, please close your other issue [here](https://github.com/bitwarden/browser/issues/1954).

Can you provide a sample LastPass CSV file for import, that we can use to recreate this? (make sure that it doesn't contain any sensitive information)

**Comment by Daniele122898** [comment]
Yes and im also pretty sure i figured out why. 
I will attach a sample CSV file with some URLs that didnt work for me after import. It seems that lastpass sometimes adds a whitespace after the comma which obv needs to get trimmed away because afaik no password can start or even have whitespaces. 

I have replaced only the passwords with x's but kept everything else equal like whitespaces and co, same with email. 

I had to upload it as a .txt because github does not support .csv files. Just change the file ending.

But again im pretty sure the import process does not trim the passwords and keeps the whitespaces at the beginning. 
I've also added a line that worked and there you can see exists no whitespace in the csv file (the notion login).

[lastpass_export.txt](https://github.com/bitwarden/web/files/6832622/lastpass_export.txt)

**Comment by eliykat** [comment]
Thanks for the sample export file. This is strange behaviour, I haven't heard of LastPass doing this before. However, a space is a completely legal character to have in a password, even as the first character of a password. (Some sites may differ depending on their rules, but in general spaces are fine.) We couldn't strip leading spaces without causing other problems - e.g. "why did Bitwarden change my password when I imported it?" We should be importing _exactly_ the password we're provided, and trust the other password manager to provide accurate exports.

I'd recommend reporting this as a bug to LastPass (if you want) as I don't think it's something we can safely and properly solve at our end.
