### ISSUE TITLE
Simplified Chinese interface display Traditional Chinese

### ISSUE THREAD

**Issue by kouhe3** [bitwarden/web#1136]
## Describe the Bug

I changed the interface language to zh CN in the settings

But the interface is zh TW

## Steps To Reproduce

go to setting -> options . change language to zh-CN

## Expected Result

UI is zh-CN

## Actual Result

![image](https://user-images.githubusercontent.com/25522053/130026806-815d3b49-0b65-404e-bee0-98884fd23947.png)

it's zh-TW

## Environment

bitwarden web 2.22.0
Chrome  92.0.4515.159
Windows 10 20H2

**Comment by edisonlee55** [comment]
This issue should be caused by PR #1134.
Where zh-CN translation has been swapped with zh-TW translation.

**Comment by eliykat** [comment]
Thank you for reporting this issue. We made some changes to our auto-sync with CrowdIn, which seems to have caused some problems. We've un-swapped these languages in #1150.
