### ISSUE TITLE
Collections with an already shared login

### ISSUE THREAD

**Issue by bfabio** [bitwarden/web#114]
When you share a login and subsequently want to modify the collections associated with it, you can only choose between the previously selected collection and not between all the available ones.

Additionally, if you deselect all the collections and save the login, the item disappears and reappears only if you reload the page (with no collection associated and no way to add it to one).

**Comment by kspearrin** [comment]
Thanks. We discovered this the other day and have patched it for our next release.

**Comment by kspearrin** [comment]
The workaround is to manage the collections from the org's admin area vault.
