### ISSUE TITLE
Cannot login/register account

### ISSUE THREAD

**Issue by timololipop** [bitwarden/web#1161]
Hey,

I cant provide any logs as there are no errors. I try to login on https://vault.bitwarden.com/#/ and it ends up in an eternity loading. Tried different browsers, different networks, no success.

This pops up:
Ein Fehler ist aufgetreten.
<!DOCTYPE html>     <html class="no-js" lang="en-US">  <head> <title>bitwardenapi-s38gsxx.azurewebsites.net | 524: A timeout occurred</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" /> </head> <body> <div id="cf-wrapper"> <div id="cf-error-details" class="p-0"> <header 

> class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8"> <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2"> <span class="cf-error-type">Error</span> <span class="cf-error-code">524</span> </h1> <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 685d2414d612215d &bull;</span> <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2021-08-28 11:20:26 UTC</span> <h2 class="text-gray-600 leading-1.3 text-3xl font-light">A timeout occurred</h2> </header> <div class="my-8 bg-gradient-gray"> <div class="w-240 lg:w-full mx-auto"> <div class="clearfix md:px-8"> <div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left

**Comment by tcelestino** [comment]
Same thing here

**Comment by djsmith85** [comment]
Hi @timololipop some customers already reported issues connecting this morning. We've addressed the issue and everything should be working now.
