### ISSUE TITLE
Problems Login/Register vault.bitwarden.com

### ISSUE THREAD

**Issue by timololipop** [bitwarden/web#1162]
Hey,

I cant provide any logs as there are no errors. I try to login on https://vault.bitwarden.com/#/ and it ends up in an eternity loading. Tried different browsers, different networks, no success.

This pops up:
Got problems pasting it here,
![image](https://user-images.githubusercontent.com/25285295/131216390-d7306c69-c9a0-4496-bcff-97b8b92e4eb5.png)

**Comment by djsmith85** [comment]
Hi @timololipop some customers already reported issues connecting this morning. We've addressed the issue and everything should be working now.
