### ISSUE TITLE
Enter on "permanently delete" modal submits background form

### ISSUE THREAD

**Issue by OmgImAlexis** [bitwarden/web#12]
Pressing enter after typing your master password in the "permanently delete" modal just submits whatever form is in the background instead of submitting the modal's form.

**Comment by kspearrin** [comment]
Unable to reproduce in Chrome on windows. What browser?

**Comment by OmgImAlexis** [comment]
Latest Chrome. I'll try and reproduce after work and add a screen capture gif here.
