### ISSUE TITLE
Link to Amazon App is dead

### ISSUE THREAD

**Issue by amenk** [bitwarden/web#126]
The link on "Get the apps" to Amazon https://www.amazon.com/dp/B06XMYGPMV is not working.
I also can not find the app via the search in the store 

(I do not need it though, just discovered the dead link)

**Comment by kspearrin** [comment]
Thanks. We deprecated support for the Amazon app, so this needs to be removed.

**Comment by amenk** [comment]
Okay.

May I ask why?were there problems?

**Comment by kspearrin** [comment]
Yes, Amazon suspended bitwarden (and many others such as LastPass, Dashlane, Enpass, etc) from their app store for "infringing on rights" of one of our password manager competitors, Keeper.

Copy of the email from them:

> We have received a third party notice claiming that the distribution of the following app(s) you have submitted for sale through the Amazon Mobile App Distribution Program may not be properly authorized by the appropriate rights holder. Title(s): bitwarden Free Password Manager Sale of the app has been suspended pending further investigation. Please work with the inquiring third party to settle any rights dispute before resubmitting these applications. Below is the contact information of the third party who claims you have infringed its rights. We expect that you will compensate this party appropriately for any infringing copies sold or downloaded. Demand from: mmxxxxxx@keepersecurity.com

I emailed them back for more clarity and was basically given no info. Amazon store basically has no market share so we just moved on.
