### ISSUE TITLE
Safari extension unavailable in Mac app version 1.29.0 (1790)

### ISSUE THREAD

**Issue by i-ghost** [bitwarden/web#1268]
### Steps To Reproduce

- Install version 1.29.0 (1790) from the Mac App Store
- Open Safari
- Open Safari -> Preferences -> Extensions

### Expected Result

The Bitwarden Safari extension should be available for activation in Safari's extension preference pane.

### Actual Result

The Bitwarden Safari extension is unavailable for activation in Safari's extension preference pane.

### Screenshots or Videos

<img width="787" alt="Screenshot 2021-10-30 at 00 56 40" src="https://user-images.githubusercontent.com/2255046/139512656-382db07b-388d-4c2d-bdbf-2cd6065c6755.png">

### Operating System

macOS

### Operating System Version

12.0.1

### Web Browser

Safari

### Browser Version

15.1 (17612.2.9.1.20)

### Build Version

1.29.0 (1790)

**Comment by SergeantConfused** [comment]
Hi @i-ghost,

This has been already reported here: https://github.com/bitwarden/desktop/issues/1126 and we have submitted a new version to address this. Please await version 1.29.1 from the Mac App Store.

I thank you in advance for your understanding and patience.

**Comment by djsmith85** [comment]
Hi @i-ghost, 

The update to 1.29.1 has been released, approved and is available via the store. Please update to the newest version.

Kind Regards
Daniel
