### ISSUE TITLE
Dates not imported from 1Password correctly

### ISSUE THREAD

**Issue by EmnaX** [bitwarden/web#1287]
### Steps To Reproduce

I have recently moved over to Bitwarden from 1Password. I exported my 1Password vaults as 1Password Interchange Format (.1pif) but when I import them into Bitwarden, the date fields are shown as a long number instead of a date. 

### Steps to Reproduce:

**In 1Password, export a vault**
1. Open the 1Password app (Running on MacOS)
2. Select a vault
3. Click on 'File' --> 'Export' --> 'All Items...'
4. Enter your vaults master password
5. Select file format: 1Password Interchange Format (.1pif)
6. Click 'Save'

**In Bitwarden, import the 1Password vault**
1. Log into the web vault.
2. Click on 'Tools' --> 'Import Data'
3. Select the format of the import file: 1Password (1pif)
4. Select the import file.
5. Click on 'Import Data'
6. Click on any newly important item which had a date field from 1Password.

### Expected Result

1Password records with a date field show the date as: 2021-11-09

After importing into Bitwarden, the dates should still be shown as 2021-11-09

### Actual Result

After importing into Bitwarden, the dates are shown as: 1636482973

### Additional Context

Versions:
1Password: 7.9.1 (70901007)
Bitwarden: 2.23.0

### Operating System

macOS

### Operating System Version

12.0.1

### Web Browser

Safari

### Browser Version

15.1

### Build Version

2.23.0

**Comment by linusaarnio** [comment]
@EmnaX I will take a look at this.

**Comment by boistordu** [comment]
Also since 1password is migrating to its version 8, the export format file is 1pux now and it's not encrypted. 
Could you look at its import ? 

https://support.1password.com/1pux-format/

**Comment by linusaarnio** [comment]
@boistordu That is out of the scope of this issue but absolutely a valid point. I think a post in https://community.bitwarden.com/c/feature-requests is the best place to request the importer for 1pux to be added.

**Comment by EmnaX** [comment]
Thanks @linusaarnio for making this happen!
