### ISSUE TITLE
UX improvement by 1-click password copy

### ISSUE THREAD

**Issue by gbalduzzi** [bitwarden/web#13]
I think adding some buttons on the homepage sites list could improve UX a lot.
I imagine something like that:
![Imgur](http://i.imgur.com/n3xp9z1.png)

where instead of black squares there are buttons to directly copy username/password OR a direct link to the site.

**Comment by kspearrin** [comment]
Not a bad idea. Some quick actions buttons could be useful! Thanks.

**Comment by kspearrin** [comment]
Available next release
