### ISSUE TITLE
Importing xml from Firefox Password Exporter

### ISSUE THREAD

**Issue by Bati4711** [bitwarden/web#131]
I don't know if the issue is from Password Exporter or from the Bitwarden import.
Wenn a user name and/or a password contains special chars like & or % the import (or the export from Password exporter) is faulty.
% is replaced with %26 and & is replaced with %25 resulting in wrong user/password.
There is an issue for password exporter: [https://github.com/fligtar/password-exporter/issues/83](https://github.com/fligtar/password-exporter/issues/83)

**Comment by kspearrin** [comment]
Seems like an issue with the exporter rather that our importer.

**Comment by kspearrin** [comment]
Closing since this is not something we can fix.
