### ISSUE TITLE
Add "Unlock with PIN Code"

### ISSUE THREAD

**Issue by rggjan** [bitwarden/web#133]
I have the web extension installed (for Android Firefox) as well as the android app. I unlock the Android app with a pin code, which is a good tradeoff between security and convenience.

However, the web extension does not have the Unlock with PIN Code option. Either I have to keep it always unlocked (very unsecure, making the PIN code in the app useless), or I have to enter my 35-character password every time I want to login to a website (very inconvenient).

Adding the "Unlock with PIN Code" option to the web version would greatly improve the situation.

**Comment by kspearrin** [comment]
Duplicate. https://github.com/bitwarden/browser/issues/101

**Comment by rggjan** [comment]
thanks, didn't see 101...
