### ISSUE TITLE
Self-hosted vault web page doesn't display correct version

### ISSUE THREAD

**Issue by castigo86** [bitwarden/web#1335]
### Steps To Reproduce

1. Update self-hosted instance to Server 2.25.0 and Web 1.45.0
2. Confirm with "docker ps" that containers are updated to indicated version
3. Access vault web page - Version at the bottom of the page is still 2.24.4

Error persists after docker and VM restart.
Error displayed on different browsers and on different machines.

Functionality is otherwise perfect, this is a minor inconsistency.

### Expected Result

Vault web page should display correct version

### Actual Result

Vault web page states is running the older version.

### Operating System

Linux

### Operating System Version

Linux Alpine

### Web Browser

Chrome

### Browser Version

latest

### Build Version

Server 2.25.0/Web 1.45.0

**Comment by k-takkar** [comment]
I was just about to create an issue with the same topic.
I can confirm the same behaviour in our setup, The old version also appears in the Bitwarden admin page.

**Comment by djsmith85** [comment]
We've just released server and web for the cloud. The self-hosted version always get released a couple of days later. We do this to ensure everything is running smooth before making it available. Please also see: https://bitwarden.com/help/article/releasenotes#release-announcements
