### ISSUE TITLE
broken link on macOS Standard Installer

### ISSUE THREAD

**Issue by jschollenberger** [bitwarden/web#1337]
### Steps To Reproduce

1. Go to '[https://bitwarden.com/download/](https://bitwarden.com/download/)'
2. Click on 'more desktop installation options'
3. Click on 'macOS (OS X Mavericks and later) Standard Installer Bitwarden.dmg'

### Expected Result

Downloads the Bitwarden dmg. Assuming from https://github.com/bitwarden/desktop/releases/download/v1.30.0/Bitwarden-1.30.0-universal.dmg

### Actual Result

Link is to https://github.com/bitwarden/desktop/releases/download/v1.30.0/Bitwarden-1.30.0.dmg which 404s.

### Additional Context

It seems like the dmg name was changed to add "-universal" in 1.30.0.

I know this repo is for vault, but I didn't see a repo for the main site.

### Operating System

macOS

### Web Browser

Chrome

### Build Version

1.30.0

**Comment by vgrassia** [comment]
Thank you for submitting this.  It should be working now.

**Comment by jschollenberger** [comment]
Looks good, thanks!
