### ISSUE TITLE
Dropdown items doesn't showing on dark mode

### ISSUE THREAD

**Issue by solxr** [bitwarden/web#1338]
### Steps To Reproduce

1. Turn Dark Mode On.
2. Go to Custom Fields
3. Try changing the field

### Expected Result

You will be able to see the other fields.

### Actual Result

A white window will appear without any text.

### Screenshots or Videos

![chrome_ZTQNKG4kEI](https://user-images.githubusercontent.com/71159832/145722852-c848a5d6-c5ac-4655-b187-470366e624ce.png)

### Operating System

Windows

### Operating System Version

21H1

### Web Browser

Chrome

### Browser Version

96.0.4664.93

### Build Version

2.25.0

**Comment by Hinton** [comment]
Closed some duplicates, and updated this title to be more generic since the issue occurs in all dropdowns in the web vault.
