### ISSUE TITLE
Feature Request: App-based push notification for two-factor auth

### ISSUE THREAD

**Issue by trparky** [bitwarden/web#135]
An app that can be installed on a smartphone would be nice to have an a two-factor authentication method. You could then authenticate yourself using just the notification that comes either on an iPhone or Android device. This could be even built into the BitWarden app itself.

Obviously this would be for Premium users only.

**Comment by kspearrin** [comment]
This is what duo push does, which we already support.

**Comment by trparky** [comment]
Alright then, I have upgraded to Premium to get this feature. By the way, your project is getting some attention over at DSLReports.com ([https://www.dslreports.com/forum/r31715686-The-Lastpass-Extension-Slows-you-down](https://www.dslreports.com/forum/r31715686-The-Lastpass-Extension-Slows-you-down)), some of us are converting over from Lastpass to BitWarden and finding that it works a whole lot better than Lastpass especially in the browser speed department when it comes to the extension.

**Comment by kspearrin** [comment]
Thanks. I will close this now.
