### ISSUE TITLE
Impossible to enter a recovery code

### ISSUE THREAD

**Issue by jetthusher** [bitwarden/web#1360]
### Steps To Reproduce

1. Try to log in at 'vault.bitwarden.com'
2. On the MFA prompt click 'Use another two-step login method'
3. On 'Two-step Login Options' modal click 'Recovery Code'

### Expected Result

Show a recovery code entering modal.

### Actual Result

It just opens https://bitwarden.com/help/article/lost-two-step-device/ if clicked anywhere on 'Recovery Code' list item or opens two of those tabs if you click 'Select'

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2.25.0

**Comment by Krychaz** [comment]
Hi,

This is the link to enter your recovery code - https://vault.bitwarden.com/#/recover-2fa

I will raise the issue to make the modal appear right after clicking on the recovery code option and add the documentation as a possible link. Thank you for brining this up
