### ISSUE TITLE
Identity server needed for web vault ?

### ISSUE THREAD

**Issue by Pschittt** [bitwarden/web#137]
Hello,

Trying to self host bitwarden. I don’t understand why the web vault need an identity server (openid if i’m correct).

Could you explain why ?

**Comment by kspearrin** [comment]
We use this for IdentityServer4 for authentication session management...?

**Comment by Pschittt** [comment]
Thanks.

We can use any openid server/provider ? Or bitwarden can only work with IdentyServer ?

**Comment by kspearrin** [comment]
It only works with the internal identity server.

**Comment by Pschittt** [comment]
Thanks

**Comment by Pschittt** [comment]
Hi again,
Is it possible to clarify the process ? Maybe you already documented this.
What is the link between the MS SQL where all datas are stored, and the Identity Server ?

On which directory the Identity Server authenticate the web vault client ?

Last question, why the ios app, and the browser plugins doesn't need the Identity Server to authenticate and access the vault ?

Thanks.

**Comment by kspearrin** [comment]
All applications need the identity server to authenticate. Can you explain what you are trying to accomplish here?

**Comment by Pschittt** [comment]
I’m trying to fully understand each components role, and the link between all of them.
So that I can determine if they are necessarly for a self hosted  light installation, and if they can ne substituted by an alternative more light.

For the moment, I don’t understand hom the identity server (openid Connect) interact with the other component.
