### ISSUE TITLE
[Bug] Browser autofills on "Item Information" page

### ISSUE THREAD

**Issue by Limero** [bitwarden/web#138]
If you have enabled autocomplete in your browser and try to add a new item or modify the username of an existing one, the browser will replace the value in Password with your password for the vault.

To fix:
Set autocomplete="off" attribute for the password field on the "Item Information" page. Username can be left alone to still allow the username to be automatically filled, useful because many people use the same e-mail for the vault and other logins.

**Comment by kspearrin** [comment]
`autocomplete="off"` is already set on the add/edit forms in the web vault. I guess it doesn't work?

**Comment by Limero** [comment]
I just noticed that, but it definitely still autocompletes. Hmm...

**Comment by bakatz** [comment]
@kspearrin I'm currently running into this and it's extremely annoying. Would you be able to prioritize a fix on this one? You most likely just have to change `autocomplete="off"` to `autocomplete="someRandomString"` according to stackoverflow anyway. If you don't have time, I'll try to find some time in the next few weeks to fix it myself. Thanks!

**Comment by kspearrin** [comment]
What browser is ignoring the `autocomplete="off"` standard? I'm trying to test this.

**Comment by Limero** [comment]
It affects at least Firefox and Chrome/Chromium.

**Comment by kspearrin** [comment]
Shouldn't you just turn off the built-in browser password manager if you are using bitwarden?

**Comment by bakatz** [comment]
@kspearrin I use autocomplete for more than just passwords i.e. my name, addresses, etc. That's why I leave it on. Affects the latest version of Chrome on Windows, not sure about other browsers.

**Comment by kspearrin** [comment]
I added a fix here: https://github.com/bitwarden/web/commit/25f2e9c1b7fbb2234463cac2f879609b3c13688d

Seems to work in Chrome with my limited tests. This is now live in production. Can you all test and confirm?

**Comment by bakatz** [comment]
@kspearrin looks like it's working for me - thank you for the quick turnaround on the fix!

**Comment by Limero** [comment]
It does work in Chrome now, but it still autofills in Firefox.

**Comment by kspearrin** [comment]
Not sure how to stop it then 🤷‍♂️ 

I'm just going by Mozilla's own documentation on the subject: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
