### ISSUE TITLE
Logging into vault

### ISSUE THREAD

**Issue by poss727** [bitwarden/web#1397]
### Steps To Reproduce

4. Click on '...'
Every time I log in to get to my vault, it goes to the vault for a few seconds and then reverts back to the log in. I cant get into the vault 

I am using Waterfox browser with the link  https://vault.bitwarden.com/#/?utm_source=welcome_email&utm_medium=email  I just opened this link in Edge and it is working. I don't mind using Edge but Waterfox is my default browser

### Expected Result

I would like to use Waterfox browser instead of Edge

### Actual Result

Every time I log in to get to my vault, it goes to the vault for a few seconds and then reverts back to the log in. I cant get into the vault 

I am using Waterfox browser with the link  https://vault.bitwarden.com/#/?utm_source=welcome_email&utm_medium=email  I just opened this link in Edge and it is working. I don't mind using Edge but Waterfox is my default browser

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

Waterfox

### Build Version

G40.6

**Comment by Hinton** [comment]
Hi @poss727,

We provide a list of officially supported browsers on our help page, https://bitwarden.com/help/article/getting-started-browserext/. Waterfox is unfortunately not supported, and while do we our best to provide support with other browsers it's not guaranteed. Do you have any error message in the console? (right click -> inspect)

**Comment by poss727** [comment]
I do not mind using Edge which works. Thanks for your help?
Sheryl

**Comment by eliykat** [comment]
I'll close this Issue because it looks like your problem has been solved. However, if you need any further help, you can contact us using our contact page, here: https://bitwarden.com/contact.

**Comment by poss727** [comment]
I am using Edge and it works. Thanks for your help!
Sheryl
