### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/web#14]
Add a feature that will allow users to recover their account through email verification. Unfortunately due to the nature of how bitwarden works, resetting a password is not an option. Allow the user to click a link that is emailed to their account email address that will completely delete the account and re-create it with a new master password of their choice.
- This will allow users to gain access to an account that has squatted on their email address
- This will allow users to gain access to an account that they have forgotten their password to
- This will allow users to gain access to an account that they have lost access to due to losing their authentication device

**Comment by joeyakaspce1130** [comment]
Yes please! I have just created an account and somehow typed my password erong twice? Not sure how I did that, since I never have before... but now I can't use my account or reset the password

**Comment by kspearrin** [comment]
@joeyakaspce1130 Just send us an email at hello@bitwarden.com and we can help you recover the account.

**Comment by kspearrin** [comment]
This is now available.
