### ISSUE TITLE
[self-hosting] Host name for outgoing email connections

### ISSUE THREAD

**Issue by alexhk** [bitwarden/web#141]
How are hostnames used for outgoing email connections assigned? On my install it seems to be "9e87863de296" and on vault.bitwarden.com it seems to be "MzMxODQ0Nw". It might not matter when using Sendgrid, but these random names are often refused by email servers to fight spam. I suggest making it same as the configured website (ie. vault.company.com) or the host name of the system that runs docker.

Here are a couple of host name patterns that are often refused on mail servers:
all localhost refuse
all user refuse
all friend refuse
all -* refuse
all *_* refuse
all #.#.#.# refuse
all *.invalid refuse
all *# refuse
all */* refuse
all *|* refuse
all ylmf-pc refuse

**Comment by kspearrin** [comment]
I am not even sure what you are referring? We don't assign a hostname that I am aware of.

**Comment by alexhk** [comment]
If you don't set a host name intentionally, I assume whatever code passes the emails tot the SMTP server set in ./bwdata/env/global.override.env sets a random one.

When Bitwarden connects to the SMTP server, it sends its own hostname via HELO/EHLO command. This is the problem. In my case it's "9e87863de296" and from what I can tell by looking at the headers from emails sent from Bitwarden.com/Sendgrid, it's "MzMxODQ0Nw" on your production server.

Per RFC2821 (emphasis added) it should be a fully qualified domain name or the address literal:

> These commands are used to identify the SMTP client to the SMTP server. **The argument field contains the fully-qualified domain name of the SMTP client if one is available.** In situations in which the SMTP client system does not have a meaningful domain name (e.g., when its address is dynamically allocated and no reverse mapping record is available), the client SHOULD send an address literal (see section 4.1.3), optionally followed by information that will help to identify the client system. The SMTP server identifies itself to the SMTP client in the connection greeting reply and in the response to this command.

Different mail servers handle such situations differently. Some just get a higher SPAM score, some refuse connections, etc.

You probably have a few choices here.

- Make **vault.company.com** (or whatever the admin enters when Bitwarden is installed).
- **Use the address literal** (the address in brackets ([192.0.2.1]))
- **Use the hostname of the docker host** (ie. the Ubuntu system where docker is installed in my case).

The last option would probably be my choice, since this pushes the responsibility of setting the correct hostname to the admin of the host system and simplifies your work.

**Comment by kspearrin** [comment]
We use [`SmtpClient`](https://msdn.microsoft.com/en-us/library/system.net.mail.smtpclient(v=vs.110).aspx) for sending email. I am not able to find a property for setting this "host name" value. Any ideas?

**Comment by alexhk** [comment]
Seems 9e87863de296 is the CONTAINER ID of the image "bitwarden/api:1.14.1". I did some googling and it seems you set the hostname in config.json. Mine is indeed set to 9e87863de296.

/var/lib/docker/containers/CONTAINER_ID/config.json

Or alternatively you could spin up the image with the -h option.

docker run -h vault.company.com -i -t ubuntu bash

Not sure how this would be done on Windows.

**Comment by alexhk** [comment]
You might also want to check this:
https://stackoverflow.com/questions/29924843/how-do-i-set-hostname-in-docker-compose

**Comment by neonardo1** [comment]
This is still an issue, I'm not sure why it was closed.

**Comment by kspearrin** [comment]
It wasn’t closed...

**Comment by neonardo1** [comment]
Yeah, lets chalk that up to a massive brain fart.

Anyway, +1 :)

**Comment by itsthejb** [comment]
Hi all,

Having this issue here also; I tried manually setting `hostname` for all containers, but still get a mail with a verify link in the form `https://localhost/#/verify-email`.

Bitwarden 1.21.0

**Comment by johnczer** [comment]
I have noticed that when I use ports 80 and 443 running Bitwarden w/Docker on Ubuntu Linux the notifications do not work. If I change these ports to something other than 80 and 443 it works.  I have nothing else running on the Ubuntu server using ports 80 and 443 so scratching my head at this one...
