### ISSUE TITLE
License downloads with incorrect name

### ISSUE THREAD

**Issue by mplorentz** [bitwarden/web#1417]
### Steps To Reproduce

1. Sign up for a Organization License, Plan: Families 2019
2. Log into your Bitwarden.com account https://vault.bitwarden.com
2. Click on your organization to the right
3. Click Settings at the top
4. Click Subscription on the left sidebar
5. Click Download license
6. Enter your installation ID
7. Click submit

### Expected Result

A file named `bitwarden_organization_license.json` is downloaded.

### Actual Result

A file named `h3EXX0EQ.txt.part` is downloaded.

### Operating System

macOS

### Operating System Version

12.1

### Web Browser

Firefox

### Browser Version

96.0.2 (64-bit)

### Build Version

2.25.1

**Comment by SergeantConfused** [comment]
HI @mplorentz,

A .part file is a partially downloaded file; This indicates that the browser did not finish downloading the licence .json file. Can you please attempt to download your subscription licence file using a different browser and let me know how that goes?


Thank you in advance,
