### ISSUE TITLE
Is it possible to fill 3 fields (sort of 2 users, 1 password)

### ISSUE THREAD

**Issue by michaldybczak** [bitwarden/web#142]
There are sites where we chose some additional options so it's like having two user names. Lastpass somehow is able to remember and fill them, although in each vault entry there is only one user box, so I have no idea where lastpass stores the additional field data.

Does bitwarden has such ability? I tried to use on such site but I can't make it remember additional "user".
An example of such site with 3 fields is:

https://phpmyadmin.ovh.net/index.php

In first filed we must give proper database name, in second out user name, in third password.

**Comment by kspearrin** [comment]
Seems like you could use custom fields?

https://help.bitwarden.com/article/custom-fields/

**Comment by michaldybczak** [comment]
Yeap, that covers it! It works now. How could I miss it? Sorry to bother you.
THANKS! :)
