### ISSUE TITLE
Where is 2.25.1 - not in docker!

### ISSUE THREAD

**Issue by gokuatkai** [bitwarden/web#1428]
### Steps To Reproduce

pull latest image or 2.25.1 and you will see that its in fact 2.25.0....
```
[wi-bitwarden@wi-bitwarden ~]$ docker pull bitwarden/web:2.25.1
2.25.1: Pulling from bitwarden/web
Digest: sha256:c9febd90bf54267b7716a9d41f57b4621281f00c70309a5849bfd5e94439ee4d
Status: Downloaded newer image for bitwarden/web:2.25.1
docker.io/bitwarden/web:2.25.1
[wi-bitwarden@wi-bitwarden ~]$ docker run --rm -it --entrypoint=/bin/bash bitwarden/web:2.25.1 -c "cat /app/version.json"
{"version":"2.25.0"}[wi-bitwarden@wi-bitwarden ~]$
```

### Expected Result

a real 2.25.1 version

### Actual Result

a 2.25.0 version

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/30238401/151982306-abd32289-0a3c-4a04-a746-54862ead879b.png)

### Additional Context

All version latest, 2.25.0 and 2.25.1 are the same.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

`latest` but `2.25.0` I guess?

**Comment by eliykat** [comment]
CC @bitwarden/dept-devops

**Comment by joseph-flinn** [comment]
@gokuatkai Thanks for catching this! It will be fixed in the upcoming release next week.
