### ISSUE TITLE
bad search results for entries with hyphens

### ISSUE THREAD

**Issue by chrpinedo** [bitwarden/web#1456]
### Steps To Reproduce

1. create two entries in the database: "githubtest-pru.com" and "githubtest.com"
2. result of basic search "githubtest" is correct: the 2 entries
3. result of basic search "githubtest." is correct: 1 entry "githubtest.com"
4. result of basic search "githubtest-pru" IS INCORRECT: the 2 entries

### Expected Result

- result of basic search "githubtest-pru" should be 1 entry "githubtest-pru.com"

### Actual Result

- result of basic search "githubtest-pru" is 2 entries "githubtest.com" and "githubtest-pru.com"

### Operating System

Linux

### Operating System Version

Arch Linux Rolling Release

### Web Browser

Firefox

### Browser Version

96.0.3 (64 bits)

### Build Version

2.25.1 and 2.26.0

**Comment by Hinton** [comment]
Hi @chrpinedo,

Thanks for reporting this. This seems like a documentation issue. We actually always try to perform a full text search which involves fuzzy-matching. But the best matching candidate should show up at the top. Relevant code: https://github.com/bitwarden/jslib/blob/master/common/src/services/search.service.ts#L124

We are working on updating the documentation to better reflect the actual behavior.
