### ISSUE TITLE
Discussion: Higher MITM Risk using webfault -> recommend using the extension

### ISSUE THREAD

**Issue by amenk** [bitwarden/web#146]
I understand it as following:

If I use bitwarden (self hosted or on bitwarden.com) an attacked could try to get the password in two ways:

# If I use only the mobile app or extension:

Attacker put some code into the app or extension which logs the master password when typed and sends it to them. Then hack the bitwarden/self hosted server and use the master password to decrypt the data. 

The attacker has to make sure that I use t he app or extension. That is not so easy as the app and extension are signed.

# If I use the web vault

Attacker has only to hack the bitwarden server and can easily introduce some code that logs the master password and then use this to decrypt all my secrets.

Thus I believe using the web vault is quite a security risk, especially if used on daily bases.
Security is a hard as the weakest joint so it is not much more secure then putting the passwords unencrypted on the central server.
But at least you have to wait until the targeted user logs in to snif their password.

That is why I would encourage everybody to use the mobile app or extension to enhance security.

**Comment by amenk** [comment]
Am I right? Maybe a recommendation like this could be added to the FAQ, for example https://help.bitwarden.com/article/what-happens-if-bitwarden-is-hacked/

**Comment by fortinj1354** [comment]
I feel like if someone manages to compromise your Bitwarden server instance and/or is able to load malicious code onto your devices, not using the web vault and only using the app/extension isn't going to help you in the slightest. If someone manages to get your master password they don't need to "hack" the server to get your passwords, they just log in as you.

**Comment by amenk** [comment]
If I do not use the web fault I do not see a way how a hacked bitwarden server can expose my master password.
If I use the web fault, it's simple to get the master password and so decode everything all secrets on the server my user has access to.

So the bitwarden server becomes the weakest part of the security chain. I thought the whole point of using an extension is, to have a not-so-sever-dependent security model. 

See also the LastPass security model

https://lastpass.com/whylastpass_technology.php
> Our policy of never receiving private data that you haven't already locked down with your LastPass
> master password (which we never receive and will never ask for) radically reduces attack vectors.

(They also seem to have a webvault which opens the same attack vector)

**Comment by fortinj1354** [comment]
Right but you're implying that someone has compromised your system to the point that they can load arbitrary code into the web vault/mobile app/extension. If any of these things happen it's game over. When you authenticate through the web UI your password database is decrypted locally the same way the extension does it, it isn't just blindly being passed to the server. It doesn't matter _how_ someone manages to get your master password, if they obtain it then nothing matters anymore.

**Comment by amenk** [comment]
No I only imply that somebody compromises the app server - not the extension, this is signed in another way.
And I do not imply somebody compromises my client system. If this happens, sure, they can get the master password.

But if somebody compromises the bitwarden server and lots of people use the web fault, the attacker can get lots of master passwords in a very short time.

**Comment by amenk** [comment]
It's actually still a thing

**Comment by dwbit** [comment]
Hey @amenk, since this is a discussion/suggestion and not an issue, further follow-up can take place on the [Bitwarden Community Forums](https://community.bitwarden.com/).
