### ISSUE TITLE
[error: cannot decrypt] in Chrome Extension

### ISSUE THREAD

**Issue by simplytech** [bitwarden/web#1463]
### Steps To Reproduce

1. Leave macOS unattended for a few hours 
2. Click on Chrome Extension icon
3. You see [error: cannot decrypt] for all entries
4. Logout from Bitwarden Chrome Extension, then log back in.
5. Everything works

### Expected Result

Since I did not modify the defaults, I expect to see that my vault was locked.

### Actual Result

I saw [error: cannot decrypt] for all entries.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/499585/153534656-30ba857f-e89d-4273-94bb-f7be98b32f2f.png)

### Additional Context

The bug reported was on a Mac Mini, macOS 10.14.6
I also observed the same bug on a MacBook Pro, macOS 10.14.6
Same Chrome version on both, same Bitwarden Extension Version on both.

Regarding Build Version, I'm not sure what you mean by "Bottom of Page", because the Chrome Extension has no concept of pages. I assumed you are asking for the version of the Chrome Extension, so I looked it up under "Manage Extensions" ==> Bitwarden ==> Details.

### Operating System

macOS

### Operating System Version

10.14.6 (18G9323)

### Web Browser

Chrome

### Browser Version

Version 98.0.4758.80 (Official Build) (x86_64)

### Build Version

Bitwarden Chrome Extension 1.56.0 (not at bottom of the page, found in "Details" under Extensions

**Comment by N0mansky** [comment]
I have the same problem after chrome extension updated.

**Comment by ktw1016** [comment]
Can confirm the same on Windows on Chrome

**Comment by N0mansky** [comment]
> Can confirm the same on Windows on Chrome

I have the same problem on Macos Big sur. The chrome automatically update extension to 1.56.0 that've occured the error,but it's doesn't show on the firefox because it still keep at 1.55.0.

**Comment by N0mansky** [comment]
Thanks,it's worked on my computer

**Comment by Bharath1910** [comment]
> A temporary workaround is to manually sync and the problem went away for me. Still a bug nonetheless.
Thank you. it worked on my computer (brave browser)
