### ISSUE TITLE
Mass Share

### ISSUE THREAD

**Issue by amenk** [bitwarden/web#147]
Is it possible to add an action to share all selected accounts?  Currently only delete is possible.
![mass-actions](https://user-images.githubusercontent.com/1087128/33705302-0715248e-db30-11e7-84a2-a7477737d9ef.png)

**Comment by kspearrin** [comment]
This is planned for an upcoming release.

**Comment by amenk** [comment]
Cool :-) which one? Would be very helpful for us to organize our legacy-import.
:christmas_tree:

**Comment by amenk** [comment]
Dupe of https://github.com/bitwarden/web/issues/97
