### ISSUE TITLE
Include "card" and "identity" types in export

### ISSUE THREAD

**Issue by rupertberk** [bitwarden/web#148]
"login" and "note" types seem to export correctly, but card type is not included.

**Comment by logic** [comment]
identities are also missing.

**Comment by setyb** [comment]
I dislike any sort of nagging, but I feel it's important to mention that it has been 6 months since this issue was last touched.

Bitwarden still does not have a comprehensive export solution to allow a round-trip export-import for all stored data.

Thus, unless you use your own server, some data remains trapped within Bitwarden and cannot be liberated without tedious copy-paste operations.

Is there a timetable for implementation of this important functionality?

**Comment by kykc** [comment]
Also, text on the tools page is misleading and simply not true:
```
Quickly import your logins and other data from a previous export or from another password management application.

You can also export all of your vault data in .csv format.
```
ATM you cannot export all of your vault data at all.

**Comment by Mentalist6169** [comment]
Not exporting IDENTITY and CARD items is a NO GO at all.
Was short before getting everything running with bitwarden.
But now I stay with ENPASS.
Problems also with BITWARDEN:
You can not click an item to open and auto fill out.
Login on office365 fails to no auto-fill out.

There seem to be big problems with BITWARDEN still after months.
Disappointing at all.

**Comment by bradyjoh** [comment]
@Mentalist6169  feel free to file issues for those other problems you are experiencing. 

@kyle can we expect any updates on this in the near future?

**Comment by Sharky444** [comment]
I have to agree. No export is an absolute no-go for any productive application.

**Comment by kspearrin** [comment]
You can certainly "export" all of your data using the CLI into JSON format rather easily. `bw list items`

As for the CSV exports, only logins and notes are supported in the forseeable future.

**Comment by p-rintz** [comment]
> You can certainly "export" all of your data using the CLI into JSON format rather easily. `bw list items`
> 
> As for the CSV exports, only logins and notes are supported in the forseeable future.

How would you reimport the json export from bw list items in the CLI? 

The following three formats are available according to the cli help:
- gnomejson
- passmanjson
- passwordbossjson

**Comment by kspearrin** [comment]
That JSON format is not currently supported for imports.

**Comment by setyb** [comment]
@kspearrin wrote "As for the CSV exports, only logins and notes are supported in the forseeable future."

I hope you can reconsider including full round-trip export/import functionality.  It really is important.

**Comment by kspearrin** [comment]
A Bitwarden JSON export/import format is supported in the next version of the apps.

**Comment by setyb** [comment]
@kspearrin That's good news!  Will it be available via the GUI in the browser extension and/or the web vault?

**Comment by psb777** [comment]
This issue was closed too quickly. What I discover is that only the json export includes *all* your data. At the very least an update to documentation and screen prompts is required. Better would be to fix the csv export.

**Comment by THEOCKID** [comment]
WOw!  I really thought when I *exported* that I would be getting everything exported (to csv).  Not missing my credit cards, attachments, etc.  Dang!
