### ISSUE TITLE
Vault Timeout does not work properly during a private session

### ISSUE THREAD

**Issue by ssol63** [bitwarden/web#1481]
### Steps To Reproduce

1. Open Safari or Firefox
2. Open a private window
3. Log into Bitwarden
4. Click on 'Settings'
5. Click on 'Options'
6. Change 'Vault Timeout' to another value

### Expected Result

My current Vault Timeout for my Bitwarden account is set to 'On Browser Refresh'. When I log in via a private window in Firefox or Safari, the Vault Timeout is always falsely displayed as '15 minutes'. If I try to change the Vault Timeout in the private window (e.g. to 1 hour), the changes are only saved for that particular private session. As soon as I log in again via a normal browser window, the previous Vault Timeout (in this case 'On Browser Refresh') is displayed.

- The actual Vault Timeout of the respective Bitwarden account should be displayed when logging in via a private browser window
- Changes made to the Vault Timeout during this private session should be applied and saved.

### Actual Result

- The Vault Timeout is always displayed as '15 minutes' everytime a new private window session is used, regardless of the actual setting
- Changes made to the Vault Timeout during this private session are not applied and saved.

### Operating System

macOS

### Web Browser

Safari, Firefox

### Browser Version

Firefox: 233048, Safari: 15.2

### Build Version

Bitwarden web 2.26.1, Bitwarden server 1.46.1

**Comment by eliykat** [comment]
I can reproduce this. I think it's because incognito mode can't access your normal `localStorage` (where we store the settings) and has its own `localStorage` cleared when you close the incognito window.

Did incognito mode work as expected in a previous release (before this month)?

**Comment by ssol63** [comment]
We were previously using Bitwarden web 2.24.2 and Bitwarden server 1.44.1, but the issue was still existing back then.

**Comment by eliykat** [comment]
Makes sense. This is a limitation of Chrome's `localStorage` API: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage.

> (localStorage data for a document loaded in a "private browsing" or "incognito" session is cleared when the last "private" tab is closed.)

We have no other way of persisting settings locally. There is a feature request thread [here](https://community.bitwarden.com/t/sync-bitwarden-settings-like-lock-after-x-minutes-or-pin/5203) for syncing settings with the server, which could help with this issue. Otherwise this is an inherent limitation in saving local data.
