### ISSUE TITLE
Verify fingerprint phrase window no longer works

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/web#1498]
### Steps To Reproduce

1. With a fresh account, start a new organization
2. Invite a new user
3. User accepts the invite
4. Confirm new user

### Expected Result

This window should appear before user gets confirmed:

![image](https://user-images.githubusercontent.com/5418577/155559642-119c61e4-93fe-4a1b-bd89-70a8af43b9a2.png)

### Actual Result

No window appears, owners and admins can't verify each user fingerprint phrase within Bitwarden's UI

### Operating System

Windows, Linux

### Web Browser

Chrome, Firefox

### Build Version

2.26.1

**Comment by Hinton** [comment]
Confirmed, @addisonbeck could this be related to the account switching work?

**Comment by djsmith85** [comment]
Closing this, as https://github.com/bitwarden/web/pull/1517 addresses this issue.
