### ISSUE TITLE
{ #1338 } Seems to not been fixed. Dark Theme dropdown menus

### ISSUE THREAD

**Issue by EnderGamingFilms** [bitwarden/web#1503]
### Steps To Reproduce

1. Switch vaultwarden to darkmode 
2. Use pretty much any dropdown selection

### Expected Result

The menu is supposed to match the dark theme.

### Actual Result

The "background-color" was set to transparent and thus it ends up showing as white. 

### Additional Context

I am using the docker version of this software.

https://hub.docker.com/r/vaultwarden/server/

Not entirely sure if this was fixe din 2.26.0 or 2.26.1, if it was I'll just wait until the docker is eventually updated 👍

### Operating System

Windows

### Web Browser

Opera

### Build Version

2.25.1

**Comment by Hinton** [comment]
Per https://github.com/bitwarden/web/pull/1351 it's included in the 2.26.0 and 1.
