### ISSUE TITLE
Import fails silently if input is malformed

### ISSUE THREAD

**Issue by kdar** [bitwarden/web#151]
I had to edit the XML manually because bitwarden doesn't allow the Notes field to be over a certain length, and I forgot a closing tag. It just hangs there without reporting an issue (though, looking at the console shows the error).

**Comment by kspearrin** [comment]
I suppose we should catch any parsing exceptions.

**Comment by djsmith85** [comment]
Closing this as solved. Any error during the parsing of the input, will result in an error message. Also detailing the position of the parse-error.
