### ISSUE TITLE
Imposible to invite someon to an Organization

### ISSUE THREAD

**Issue by godambrosio** [bitwarden/web#1527]
### Steps To Reproduce

1. Go to one organization
2. Go to Manage > Invite User 
3. Fill mail and select a role  (i tested with all options and i'm having the same issue)
4. Click on  Save

### Expected Result

The user is added to the list and a mail I sent to him

### Actual Result

A red box appear saying that there is an server side error

### Operating System

Windows

### Operating System Version

21H2

### Web Browser

Firefox

### Browser Version

97.0.2 (64-bit)

### Build Version

2.26.2

**Comment by Hinton** [comment]
Hi @godambrosio,

Is this self hosted? Or cloud?

**Comment by godambrosio** [comment]
Cloud
