### ISSUE TITLE
SECURITY.md is missing where to actually report

### ISSUE THREAD

**Issue by suterma** [bitwarden/web#1539]
### Steps To Reproduce

Unfortunately i'ts even unclear to where to report his issue at hand:

I want to report a potential security issue with the Firefox extension. However, whether on the regular website nor in the https://github.com/bitwarden/web/blob/master/SECURITY.md on this repo, there is a hint where to actually report to.

Is it expected to
- write an email? Where to?
- send a tweet?
- Open an issue here? But there seems no specific category for this?
- Open a report on hacker one? Even if it might be minor?

### Expected Result

Please update the SECURITY.md file with indications where to report security issues.

### Actual Result

There is no hint on where to send security issues.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

Its about the repo, not the code.

**Comment by cscharf** [comment]
Hi @suterma , thank you for the report and the head's up, it's great to get feedback on how we can better communicate with our community, especially around security!

We'll get something spun up here shortly, but in the meantime if you have a security vulnerability, issue, or concern, you can submit it here to our [Hacker1 program](https://hackerone.com/bitwarden).
