### ISSUE TITLE
Import from 1password .pux silently fails

### ISSUE THREAD

**Issue by datastory** [bitwarden/web#1547]
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/tools/import
2. Select format 1password .pux
3. Select .pux file
4. Click on Import data

### Expected Result

Data imported to Bitwarden vault.

### Actual Result

Nothing happens and JS console throws error:

TypeError: can't access property "passwordHistory", e.details is undefined
    parse onepassword1PuxImporter.ts:94
    parse onepassword1PuxImporter.ts:40
    parse onepassword1PuxImporter.ts:39
    import import.service.ts:109
    i main.5b8712b78959d87aa676.js:1
    t Angular
    i main.5b8712b78959d87aa676.js:1
    import main.5b8712b78959d87aa676.js:1
    submit import.component.ts:108
    a main.5b8712b78959d87aa676.js:1
    Angular 13
    <anonymous> task.js:61
    M task.js:35
    P task.js:46
[consoleLog.service.ts:53:16](webpack://bitwarden/web-vault/jslib/common/src/services/consoleLog.service.ts)
    write consoleLog.service.ts:53
    error consoleLog.service.ts:30
    submit import.component.ts:118
    s main.5b8712b78959d87aa676.js:1
    Angular 13
    <anonymous> task.js:61
    M task.js:35
    P task.js:46

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2.27.0

**Comment by djsmith85** [comment]
Hi @datastory and thank you for the report.

Did this occur with a freshly exported file from 1password (latest version) or an older one?

Looking into it now, if I can reproduce it.

**Comment by datastory** [comment]
The export was made on v. 8.3.0 for Linux.

**Comment by djsmith85** [comment]
Could you please try upgrading to 8.5 or even better 8.6 and try again.

**Comment by datastory** [comment]
It works on 8.5.0, thanks for your help! For a reference, I am attaching an a export for an test account, if you want to look at it
[8_3_0-I4YJFICOJJB7VDX2HH6EZZXSYI-20220316-100655.zip](https://github.com/bitwarden/web/files/8260542/8_3_0-I4YJFICOJJB7VDX2HH6EZZXSYI-20220316-100655.zip)
.

**Comment by djsmith85** [comment]
Thank you for the quick replies and I'm glad it's now working. I'll make sure we include the min. version in our release notes.

Also kudos for attaching an example file 👍  It has confirmed my assumption. Initially I wrote the importer against the format you attached. During testing we realized that 1password had changed the format. 

More information, regarding that change can be found at https://github.com/bitwarden/jslib/pull/714

Closing this now as it's resolved 😃

**Comment by datastory** [comment]
So after successfully testing with test account, I have tried with live one and got Import Error: SubtleCrypto.encrypt: Argument 3 could not be converted to any of: ArrayBufferView, ArrayBuffer.

Guessing that could be connected with the size of the export file (close to 200 MB)

![image](https://user-images.githubusercontent.com/2298856/158560144-84813ecd-df1a-4709-b597-81beac87ffea.png)

**Comment by djsmith85** [comment]
@datastory Thank you for opening a new issue https://github.com/bitwarden/web/issues/1548.
