### ISSUE TITLE
Import from 1password .pux fails with Import error

### ISSUE THREAD

**Issue by datastory** [bitwarden/web#1548]
### Steps To Reproduce

1. Try to import .pux export from 1password sized approx. 170 MB.

### Expected Result

Data imported.

### Actual Result

Popup informing of Import Error, stating that "SubtleCrypto.encrypt: Argument 3 could not be converted to any of: ArrayBufferView, ArrayBuffer."

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/2298856/158561143-12283205-f520-4b7f-af9a-0f7abbe7249b.png)

### Additional Context

Data exported from 1password for Linux v. 8.5.0

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

developer edition 98.0b5 (64-bit)

### Build Version

2.27.0

**Comment by djsmith85** [comment]
I don't think it has to do with the file size, as we currently ignore attachments. I've also just tested importing a file (~220MB) without any issues. 

The error indicates that something is failing while encrypting the already prepared import.

**Comment by datastory** [comment]
I am prepared to help with the debugging, of course in this case I can't provide you unencrypted backup of my password vault.

**Comment by djsmith85** [comment]
Thank you, for offering your help on this.

I've been unable to repro this on Windows using Chrome (99.0.4844.51), FireFox Dev edition 99 and Firefox 98.

Are there any errors on the console when the message appears?

Any other information you could give me about your setup?

Could you possibly test with another browser or even system?

Just trying to narrow this down.

**Comment by datastory** [comment]
So I have tried in Chrome v. 99.0.4844.51 (Official Build) (64-bit) with the same result. JS console stays empty during the import, only the Chrome reports that on the vault.bitlocker.com the "Content Security Policy of your site blocks the use of 'eval' in JavaScript`" and points to "core.umd.jss:5556  script-src  blocked".

I am using NixOS v. 21.11 (stable).

IMHO the problem is caused by some particular record in my 1pwd export, so if you can point me, which operations are done with the data before importing, I can try to simulate it and identify the perpetrator.

**Comment by djsmith85** [comment]
The only similar issue I have found is this one: https://github.com/bitwarden/desktop/issues/106

So I'm also thinking it might have to do with a particular record in the export. Haven't had any luck though, so far to find a problematic field/value.

The source code for the importers is hosted at https://github.com/bitwarden/jslib

The code for the 1pux importer is [here](https://github.com/bitwarden/jslib/blob/master/common/src/importers/onepasswordImporters/onepassword1PuxImporter.ts) and the test cases can be found [here](https://github.com/bitwarden/jslib/blob/master/spec/common/importers/onepassword1PuxImporter.spec.ts)

Thank you for your help with investigating

**Comment by thinkpoop** [comment]
In Firefox I get the same "Argument 3 could not..." error.
In Vivaldi/Chrome I get "Failed to execute 'encrypt' on 'SubtleCrypto': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'."

I narrowed it down to at least one almost empty identity record about my cat... I've attached a dummy copy of the data:
[1Pass_Error.zip](https://github.com/bitwarden/web/files/8358273/1Pass_Error.zip)

**Comment by djsmith85** [comment]
@thinkpoop Thank you very much for providing an example file. 

I've been able to reproduce it and narrow down the issue to the email fieldType. We are currently returning a string but in this case it contains a json-object. If you've not already done so, you could remove that one identity from the file and import the rest. while I look into providing a fix.
