### ISSUE TITLE
There is no two step verification for web application

### ISSUE THREAD

**Issue by ivandotv** [bitwarden/web#155]
Title says it all.
I have two factor authentication enabled, but web application only asks for username and password.

**Comment by jcolp** [comment]
I just tried this on my own bitwarden.com account and didn't encounter the same result. It asked for my Yubikey, and a link was present to fall back to an alternative method.

**Comment by kspearrin** [comment]
@ivandotv Unable to reproduce. Please provide more info about how you have 2FA configured.

**Comment by ivandotv** [comment]
On https://vault.bitwarden.com/# I'm presented with email ,and password only.
When entered correctly I'm taken directly to the app. There are no additional steps.
Android app asks for additional authentication code, web doesn't.

**Comment by kspearrin** [comment]
> Please provide more info about how you have 2FA configured.

**Comment by kspearrin** [comment]
Sounds like you clicked "remember me" on a time before when you did 2FA. You can clear your cookies or deauthorize all sessions under settings to make it prompt you again.

**Comment by ivandotv** [comment]
You are right it shows 2 step authentication login.
It it is a little bit counter intuitive.
If you are logged out and you try to log in, you should be presented with the 2step process every single time.
Thank you for your time.

**Comment by kspearrin** [comment]
Then do not select "Remember Me" and you will.

**Comment by ivandotv** [comment]
I understand that, but why?
What is the case for it? So you want to log out, have 2factor auth, and then you use "remember me"
So basically it permanently disables 2auth (unless you clear all the cookies)
I have never seen such a option anywhere.
Anyway, very confusing login flow. Hence this github issue :)

**Comment by kspearrin** [comment]
2FA will be remembered for 30 days, not forever. Here is the option being offered by Google when logging in:

![image](https://user-images.githubusercontent.com/1190944/34313051-7dbe42b6-e736-11e7-8c3a-993833cfde70.png)

This is a common option on nearly every service that offers 2FA login... ? I am surprised you have never seen it before.
