### ISSUE TITLE
Logged in as _$1_ on bitwarden.com.

### ISSUE THREAD

**Issue by piotrcichosz** [bitwarden/web#1557]
### Steps To Reproduce

1. Login
2. keep tab open, forget about it for few hours
3. get back to tab where bitwarden was open - see "Logged as $1" 

important - it not always happen to me, but can't figure out difference when it does 

<img width="892" alt="Zrzut ekranu 2022-03-21 o 09 36 23" src="https://user-images.githubusercontent.com/46444515/159262817-87d38784-41cc-4f6c-a9d6-00f0d8331b35.png">

### Expected Result

See locked bitwarden with message "Logged as <my login>"

### Actual Result

locked bitwarden with message "Logged as $1"

### Operating System

macOS

### Operating System Version

11.6.1

### Web Browser

Firefox

### Browser Version

98

### Build Version

98.0.1

**Comment by Hinton** [comment]
Clicking logout should resolve the issue for now. Will be fixed by https://github.com/bitwarden/jslib/pull/721

**Comment by justindbaur** [comment]
@piotrcichosz We are going to close this issue and if you still have this issue after our next release feel free to re-open.

**Comment by eliykat** [comment]
@justindbaur let's hold off on closing this until the PR is merged.
