### ISSUE TITLE
Importing from Kaspersky Password Manager

### ISSUE THREAD

**Issue by Ndr6** [bitwarden/web#156]
Kaspersky Password Manager in missing in the importing list. It exports a .txt file like this : 
[KPMexample.txt](https://github.com/bitwarden/web/files/1582010/KPMexample.txt)

**Comment by AlexandreBT** [comment]
Nice idea !

**Comment by djsmith85** [comment]
@Ndr6 @kspearrin  This issue can be closed. The .txt importer for Kaspersky Password manager was added with d79865f
@kspearrin Sorry for mentioning, just trying to clean up some old open issues across the repos. Any better way to let the team know? Is there a team-user?
