### ISSUE TITLE
Safari/MacOS import doesn't create URLs

### ISSUE THREAD

**Issue by karczewsky** [bitwarden/web#1561]
### Steps To Reproduce

1. Go to [Import tool](https://vault.bitwarden.com/#/tools/import)
2. Select `Safari and macOS (csv)` as `format of import file`
3. Upload file 
```
Title,URL,Username,Password,Notes,OTPAuth
title (test),https://google.com/,email@gmail.com,password,,
```
4. Finish import process

### Expected Result

When importing from files the entries contain field `URI 1` filled appropriately.

### Actual Result

Imported entries don't contain URI 1, which means autocompletion doesn't work really well for them.

### Screenshots or Videos

The actual result of import in vault:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/1348645/159781009-99cc98e7-a92d-4512-bd06-16045d171c21.png">

### Operating System

macOS

### Operating System Version

12.3

### Web Browser

Safari

### Browser Version

15.4

### Build Version

2.27.0

**Comment by karczewsky** [comment]
If it might help in any way, I've converted the safari CSV to Bitwarden CSV (using a self-made python script). 
This method worked fine, and all entries in vault had the URI 1

**Comment by djsmith85** [comment]
@karczewsky Thank you for your report. It seems that @frankeld also discovered this and has provided https://github.com/bitwarden/jslib/pull/730 to fix the issue. The PR will likely be reviewed soon.

**Comment by karczewsky** [comment]
Thanks for the verification! I've checked that it's part of jslib after reporting.

**Comment by djsmith85** [comment]
Closing this, as https://github.com/bitwarden/jslib/pull/730 has been merged into web and will be included in the next release.
