### ISSUE TITLE
Self hosted - OPTIONS http request

### ISSUE THREAD

**Issue by Pschittt** [bitwarden/web#158]
Hello,

Since this week (at least), it seems that some HTTP request are OPTIONS type request.

It happens at the user login, for the token request or the profile request.

Why is there this OPTIONS request ? It seems that before it wasn't there.

Thanks.

**Comment by kspearrin** [comment]
Sounds like you're hitting CORS scenarios. How are you deploying this?

**Comment by Pschittt** [comment]
Via Docker.
Just curious why the browsers are doing this request before the other.
Seems to be related to the browser, but I was curious if you knew why.

PS : Impressed that you answered so quick !
