### ISSUE TITLE
Not able to manipulate folder right after creation

### ISSUE THREAD

**Issue by brucehsu** [bitwarden/web#159]
For now, you simply cannot create a new folder on Vault and add/move new items to it.
It's not showed in the right sidebar, and you're not able to choose it from item `Move` dialog combo box.
You can surely see the newly created flder in the center pane, however you could not perform any operations like deletion.

**Comment by kspearrin** [comment]
This is fixed for next version coming out soon.

**Comment by brucehsu** [comment]
Thanks!
Was thinking about contributing :p
