### ISSUE TITLE
[Suggestion] Move attachment-handling to Item Information dialogue

### ISSUE THREAD

**Issue by grmp** [bitwarden/web#160]
Currently the attachment handling isn't quiet self-explaining. It took me several minutes to figure out how to upload a receipt to an item.

In my humble opinion a better or more obvious place would be right under "Custom Fields" at Item Information, or to trigger the Attachment dialogue using a clip-icon by the side of "Toggle Favorite".

**Comment by dwbit** [comment]
Hey @grmp, thanks for the suggestion! Since this relates to a change/enhancement, we'll be closing out the issue and directing any follow-up discussion to the [Bitwarden Community Forums](https://community.bitwarden.com/).
