### ISSUE TITLE
Software Requirements Specification for Web Bitwarden

### ISSUE THREAD

**Issue by NickMSD** [bitwarden/web#161]
Hey everybody. I had a project in my "Software Engineering" class which asked to create a Software Requirements Specification(SRS) for an open source project. So I created one, I tried hard for it, worked for days and now I'm presenting it to you. It's 31 pages and (unfortunately) it's written in Greek.

Regards,
Nick.
[SRS for bitwarden.pdf](https://github.com/bitwarden/web/files/1593434/SRS.for.bitwarden.pdf)

**Comment by kspearrin** [comment]
Would love to read through it but I'm afraid the translation will lose too much context for me. Pretty cool though! Thanks for sharing.

**Comment by NickMSD** [comment]
Thank you very much **kspearrin** for sharing your opinion. I really like the project, maybe i'll translate it in English after exams end(February) so that we can upload it for other users. :)
