### ISSUE TITLE
Import from 1password .pux fails with TypeError: can't access property "passwordHistory"

### ISSUE THREAD

**Issue by datastory** [bitwarden/web#1612]
### Steps To Reproduce

Try to import .1pux file from 1password export.

### Expected Result

Data imported.

### Actual Result

Import silently fails, web developer console throws:

TypeError: can't access property "passwordHistory", e.details is undefined
    parse onepassword1PuxImporter.ts:94
    parse onepassword1PuxImporter.ts:40
    parse onepassword1PuxImporter.ts:39
    import import.service.ts:109
    i main.b6c79320d077e272b347.js:1
    t Angular
    i main.b6c79320d077e272b347.js:1
    import main.b6c79320d077e272b347.js:1
    submit import.component.ts:108
    a main.b6c79320d077e272b347.js:1
    Angular 13
    <anonymous> task.js:61
    M task.js:35
    P task.js:46
    20261 task.js:84
    Webpack 8
consoleLog.service.ts:53:16

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

developer edition 98.0b5 (64-bit)

### Build Version

98.0b5 (64-bit)

**Comment by djsmith85** [comment]
Hi @datastory and thank you for the report. 

You have previously reported the same issue at https://github.com/bitwarden/web/issues/1547 

Was this not resolved with upgrading to 1password v8.5?

**Comment by datastory** [comment]
@djsmith85 My bad, I accidentally downgraded, sorry for the confusion :/
