### ISSUE TITLE
During registration, password strength does not consider minimum length

### ISSUE THREAD

**Issue by atringle** [bitwarden/web#1618]
### Steps To Reproduce

- Send user an invite to organization
- User clicks link to register and sets up an account with password that does not meet length requirements (14 minimum in this case)
- When user tries to register to organization they are asked to change master password
  - User enter in a password that meets all criteria except the length is less than the minimum length (14 characters)
  - User clicks submit

### Expected Result

- The password strength indicator should take into account the policies minimum password length requirement
- It would be ideal to show what exact requirement is failing (many account creation forms do this)

### Actual Result

User gets a generic error `Your new master password does not meet the policy requirements`

- No indication of the requirement not being met is given.
- Password strength indication tells them its strong

### Additional Context

While some users will figure out the root issue on their own other less technical users are left not knowing why this is failing and I think this can be handled in a better fashion for users with less technical prowess.

### Operating System

Windows, macOS

### Operating System Version

Windows 10, BigSur

### Web Browser

Chrome, Safari

### Browser Version

Chrome 100.0.4896.127, Safari 15.4

### Build Version

Version 2.28.0

**Comment by yashwalter12** [comment]
Hello @atringle  This is currently working as expected. 
The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one. 
Thank you.
