### ISSUE TITLE
Numbers/Counts in reports not shown in other languages __$1__

### ISSUE THREAD

**Issue by JensSpanier** [bitwarden/web#1622]
### Steps To Reproduce

1. Change language to `de` or `es` (I have not tested other languages, yet)
2. Go to reports and select a report which has some entries (e.g. Weak Passwords)

### Expected Result

> Wir haben **1** Einträge mit schwachen Passwörtern in Ihrem Tresor gefunden. Sie sollten diese aktualisieren und ein sicheres Passwort verwenden.

### Actual Result

> Wir haben **\__$1__** Einträge mit schwachen Passwörtern in Ihrem Tresor gefunden. Sie sollten diese aktualisieren und ein sicheres Passwort verwenden.

### Screenshots or Videos

English:
![image](https://user-images.githubusercontent.com/42373861/165565756-96993098-8755-4aae-8247-3064d012ddb6.png)

German:
![image](https://user-images.githubusercontent.com/42373861/165565661-5c53d8c2-f5f2-4538-8d77-197d80512d56.png)

### Operating System

macOS

### Operating System Version

12.2.1

### Web Browser

Chrome

### Browser Version

100.0.4896.127

### Build Version

2.28.0

**Comment by djsmith85** [comment]
@JensSpanier Thank you for the report. I can confirm the issue. This worked on 2.27.0 and broke with 2.28.0
