### ISSUE TITLE
Import from KeePass XML fails when passwords exceed 1000 bits

### ISSUE THREAD

**Issue by pjclutterbuck** [bitwarden/web#166]
I tried to import a KeePass 2.x database in XML format, which included thousands of passwords generated by KeePass to strengths of 128, 256, 384, 512, 768, 1024, 2048 and 4096 bits, using hexadecimal, alphanumeric, alpha+special, and alpha+special+high-ANSI character sets. The import failed.

**Comment by kspearrin** [comment]
The password field length limit in bitwarden is 1000 characters encrypted, or somewhere around 650 characters unencrypted. You'll need to change/remove those before the import will succeed.
