### ISSUE TITLE
Unparsed variable on the lock web page

### ISSUE THREAD

**Issue by vaheen** [bitwarden/web#1662]
### Steps To Reproduce

1. Go to 'https://vault.bitwarden.com/'
2. Login
3. Wait for it to timeout and redirect to 'https://vault.bitwarden.com/#/lock'

Under the master password it will say: Logged in as __$1__ on bitwarden.com. 

* It seems to show when going to 'https://vault.bitwarden.com/#/lock' directly too

### Expected Result

Expect to see the "Logged in as <<<SOME USER NAME>>> on bitwarden.com."

### Actual Result

"Logged in as __$1__ on bitwarden.com."

### Screenshots or Videos

bitwarden-lock.png
![image](https://user-images.githubusercontent.com/42509710/167769534-b9c2ec26-316d-48ed-941a-38f45c1c6ae2.png)

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Firefox

### Browser Version

Developer 101.0b3 (64-bit)

### Build Version

2.28.1

**Comment by eliykat** [comment]
This has already been reported in #1557 and will be fixed in the May release.

**Comment by vaheen** [comment]
ok, closing #1557 before it is released makes it looks like it has not been logged
