### ISSUE TITLE
[Feature Request] Ask to update password when changed for a site.

### ISSUE THREAD

**Issue by mil1i** [bitwarden/web#170]
I haven't noticed this occurring if I change a password, or use a different password than is saved in bitwarden, where it might ask me to update/change my saved password for this site.

Lastpass does this when you use a different password or change your password to a site. It is nice so that you don't have to manually go in and update your vault.

If this is implemented already and I am not using it correctly, please let me know! 

Thank you

**Comment by kspearrin** [comment]
We are tracking this feature request in the browser extension repo. It is not available now.
