### ISSUE TITLE
Wrong password is shown in webinterface

### ISSUE THREAD

**Issue by Bokxie** [bitwarden/web#171]
I created several new accounts within the Chrome extension. The new password are length 24 or 18 chars large. All created the incorporated generator.

In the iOS apps and in the Chrome extension, the correct pw is visable. But when I take a look at the web interface (vault) then password of by BW account/vault is shown. That is quite different then the ones created in the Chrome extension.

Can you verify this problem ?
Michel

**Comment by kspearrin** [comment]
This is your browser's built in password manager autofilling it in the fields. Turn off the browser's built in password manager or make it forget your bitwarden credentials.

**Comment by Bokxie** [comment]
Thanks for the fast responce. I cleared the password list in Chrome. Now I can confirm it is working as it should be.
