### ISSUE TITLE
[BUG] Collection entry disappear after editing 

### ISSUE THREAD

**Issue by scifire91** [bitwarden/web#174]
If i edit a collection entry while i´m in my vault this entry will disappear until i refresh the page.

**Comment by kspearrin** [comment]
Not able to reproduce. Please include exact reproduction steps.

**Comment by scifire91** [comment]
Self Hosted Environment v 1.16.0
Login to Bitwarden -> Scroll down till you see a Collection which is shared with you -> Enlarge the Collection -> Open an item -> klick save in the item -> item disappear in the collection until i refresh the site or browser to another site and came back.
I´ve also send you and short video via mail.

**Comment by pauldalewilliams** [comment]
I can confirm the behavior @scifire91 mentioned above.  I'm on version 1.22.0 using Chrome to access the web frontend.

**Comment by kspearrin** [comment]
Fixed for next release.
