### ISSUE TITLE
Incorrect name stored when URL ends in ".local"

### ISSUE THREAD

**Issue by steffan-red** [bitwarden/web#175]
When I tell bitwarden to save a password after logging into a site with a URL ending in ".local", the name of the website is not saved properly in bitwarden.

Steps to reproduce:
1. Go to a URL ending in ".local", e.g. https://www.mywebsite.com.mycompanydev.com.local/
2. Enter a password into a form and submit
3. Tell bitwarden to remember this password using the automatic text on top of the screen

Expected behaviour:
The name and URL of the saved password should be something like "www.mywebsite.com.mycompanydev.com.local"

Actual behaviour:
The name and URL of the saved password is "com.local"

![image](https://user-images.githubusercontent.com/20968994/36149549-0bbe0e34-10b8-11e8-897b-6eb3b7c1db32.png)

**Comment by kspearrin** [comment]
We should just use the hostname rather than trying to get the top domain.

**Comment by kspearrin** [comment]
This is the wrong repo if this a report about the browser extension. Regardless, should be fixed in latest versions.
