### ISSUE TITLE
Wrong information at "Get the Apps"?

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/web#184]
When I am in my vault (via the web browser) and click on "Get the Apps" at the left side, then I read that
- Desktop Windows (coming soon) 
- Desktop macOS (coming soon) 

But at the mail website both are available for download.

Next all links provided at "Other" are not working (nothing happens when I click them).

**Comment by kspearrin** [comment]
This is fixed in next version. We just link to the website instead.

**Comment by OLLI-S** [comment]
Updated the description
