### ISSUE TITLE
Problems filling Identity at Facebook

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/web#185]
I added in Bitwarden an identity and also filled the email address.
In the edge Browser I sync my vault (so all data is up to date).

Then I go to the German website of Facebook: https://de-de.facebook.com/
Here I fill my identity from the Bitwarden extension.

At top of the Facebook website the email address is entered (this is the login field).
But in the registration fields the email address is not filled (my first name and my last name is filled).

Here the source of the desired field:
`<input name="reg_email__" class="inputtext _58mg _5dba _2ph-" id="u_0_s" aria-invalid="true" aria-required="1" aria-describedby="js_3ky" aria-label="Handynummer oder E-Mail-Adresse" type="text" placeholder="" autocomplete="off" data-type="text" data-fillr-id="99956" data-fillr="bound">`

**Comment by kspearrin** [comment]
This happens because it finds an email address fields to fill before that one. Once a fields is filled it does not fill any more on the screen.

**Comment by OLLI-S** [comment]
At some web pages I have to enter my email address and then confirm my email address in a second field.
So I have to enter it twice (Facebook is not the only website having this problem).
So it would be perfect if both fields are filled.

**Comment by kspearrin** [comment]
This should be moved to the browser repo since it is unrelated to the web vault.

**Comment by OLLI-S** [comment]
I added my original posting to:
https://community.bitwarden.com/t/fill-in-confirm-email-fields/87/9
