### ISSUE TITLE
attachment upload and download error

### ISSUE THREAD

**Issue by marviins87** [bitwarden/web#186]
Hi Team,

I've just bought the premium license because i would like to use the attachments feature in Bitwarden. 
I'm using the online vault and uploading an attachment (2KB) finished with the following error:

"An unhandled server error has occurred."

After refreshing the page i'm able to see the files being attached to the login item but i cannot download them anymore. 

when i try to download the attachment it takes very long (60s+) before download starts and most of the time it doesn't start at all. When the attachment is downloaded the file is empty (it contains "NULL" in txt editor).

Deleting the attachment gives the exact same error again.

Please help!

**Comment by kspearrin** [comment]
Try deleting it and re-uploading it now. There is a bug in one of our SQL queries that causes these timeouts to occur from time to time, and breaks the upload process. Then it magically seems to correct itself after some period of time. Based on your posting this I was able to capture some information on the issue while it was occurring, so thanks!

I'll continue to investigate, but it should be cleared up for now.

**Comment by kspearrin** [comment]
Please reply to this issue if you notice it happening again. Since the problem is intermittent I need to know when it is occurring so that I can capture some vital info from the database regarding the problem.

**Comment by kspearrin** [comment]
Trying here now. https://github.com/bitwarden/core/issues/230
