### ISSUE TITLE
Equivalent domain form doesn't strip whitespaces

### ISSUE THREAD

**Issue by kochie** [bitwarden/web#189]
I noticed this when I was adding some custom equivalent domains. When the domains are added with a newline following the comma the domains are not parsed properly and do not register as equivalent domains.

![screenshot-2018-3-19 domain settings - bitwarden web vault](https://user-images.githubusercontent.com/10809884/37573474-68e2a1a0-2b6c-11e8-8f9f-b514d69db898.png)

However when they are added with just a comma the domains work as expected.

![screenshot-2018-3-19 domain settings - bitwarden web vault 1](https://user-images.githubusercontent.com/10809884/37573494-955eb1d8-2b6c-11e8-90bf-4c51aefd6b38.png)

The simplest fix would be to remove the newline when the form is submitted. I'm prepared to fix it unless there are any better ideas?

**Comment by kspearrin** [comment]
I think we already strip whitespace there, just not new lines. Probably a good idea to strip on save as well.

**Comment by kspearrin** [comment]
Fixed in v2.0
