### ISSUE TITLE
Built in browser save prompt is exposing password

### ISSUE THREAD

**Issue by Keetz** [bitwarden/web#19]
When saving a new site to my vault on Firefox 49.0 the "Would you like Firefox remember this login?" pop-up exposes the password in the field where the user name usually shows.

As a test i created a new site:

Site: http://test.com
Name: TestName
Username: TestUserName
Password: password123

![firefox_issue](https://cloud.githubusercontent.com/assets/6707330/19642685/b1216fbe-99e6-11e6-8e8e-c22b43cf493c.png)

My concern is not that Firefox doesn't store it correct, i guess it is not supposed to save anything at all, but my concern is that it exposes the password in clear text, so anyone looking at your screen can see it.

Also tested in Chrome version 54.0.2840.59 (64-bit), same thing happens.
![chrome_issue](https://cloud.githubusercontent.com/assets/6707330/19642903/d7a61486-99e7-11e6-87c9-e119d2a062fe.png)

**Comment by kspearrin** [comment]
Wow that's kind of weird. let me look into it and see if there is a fix. I think it has to do with the order if the input fields. In the meantime, you should probably just disable the Firefox password manager anyways since it is not necessary.

**Comment by Primokorn** [comment]
@kspearrin Any news on this issue?

**Comment by kspearrin** [comment]
Unfortunately I haven't had the opportunity to look into this yet. The work around for now is to just disable the firefox password manager.

**Comment by Keetz** [comment]
@kspearrin no, it work as intended in that preview. Username and password on the correct fields of the popup

**Comment by xhoy** [comment]
Today we started our enterprise subscription. Works great but we currently have this issue. Any solution in side?
