### ISSUE TITLE
"Unexpected error" when logging in after updating

### ISSUE THREAD

**Issue by fortinj1354** [bitwarden/web#191]
I just updated my selfhosted install to the latest docker builds (web:1.24.0 and 1.17.2 of the rest). When I try to log in via the website I get a message saying `Errors have occurred- An unexpected error has occurred.` This error happens in both Firefox and Chrome, including after disabling all extensions and clearing the cache in both browsers. I see two errors happening in the console, the first set happens on page load (I tried copy/pasting the error, but I couldn't get the formatting right):

https://i.imgur.com/Nlc62gf.png

The second error happens when I actually click log in. Here's the request

```
Request URL: https://<bitwarden domain>/identity/connect/token
Request Method: POST
Status Code: 400 
Referrer Policy: same-origin

Request Headers
:authority: <bitwarden domain>
:method: POST
:path: /identity/connect/token
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 149
content-type: application/x-www-form-urlencoded; charset=UTF-8
device-type: 9
origin: https://<bitwarden domain>
referer: https://<bitwarden domain>/
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

Form Data
client_id=web&grant_type=password&password=<password>&scope=api+offline_access&username=<username>
```

And the response

```
access-control-allow-origin: https://<bitwarden domain>
cache-control: no-store, no-cache, max-age=0
content-type: application/json; charset=UTF-8
date: Thu, 22 Mar 2018 04:58:10 GMT
pragma: no-cache
server: nginx
server-version: 1.17.2
status: 400

Response Body
{"error":"invalid_grant","error_description":"Two factor required.","TwoFactorProviders":[0,3],"TwoFactorProviders2":{"0":null,"3":{"Nfc":false}}}
```

I should note this request/response is going through an nginx reverse proxy, but I get the same results hitting the VM the bitwarden instance is running on directly. I also was successful logging in via the Firefox extension (and syncing the Chrome extension), for what it's worth (otherwise, I would have posted this to the core repo). I tried to pull logs from the bwdata folder on the VM, but the latest date on any of the logfiles is `20180317.txt` so if there's anywhere else I should look for logs I'm happy to grab them (I should note that that file in `bwdata/core/logs/Api` is massive and full of json serialization errors).

**Comment by kspearrin** [comment]
Can you update again which should now pull version 1.24.1? It seems something broke the JS during the minification process in 1.24.0

**Comment by fortinj1354** [comment]
That did the trick! Thanks for the quick turnaround.
