### ISSUE TITLE
Delete account fails with ' '

### ISSUE THREAD

**Issue by tanjianaus** [bitwarden/web#193]
Following instructions to delete account from web without login (forgotten master password)
https://help.bitwarden.com/article/delete-your-account/

Navigate to
https://vault.bitwarden.com/#/recover-delete

Enter Email
Receive Email
Click Delete Link
Click Delete Account Button
Click OK on popup warning
Error Unable to delete account

Chrome Mac OSX
Version 65.0.3325.162
Firefox 58.0.2

**Comment by tanjianaus** [comment]
<img width="364" alt="screen shot 2018-03-25 at 10 33 41 am" src="https://user-images.githubusercontent.com/37756603/37870032-1a4e14ce-3018-11e8-9dfb-a70dd8a8d52e.png">

**Comment by tanjianaus** [comment]
<img width="364" alt="screen shot 2018-03-25 at 10 33 41 am" src="https://user-images.githubusercontent.com/37756603/37870038-31f23f42-3018-11e8-880a-a061165edef4.png">
![Uploading Screen Shot 2018-03-25 at 10.33.33 am.png…]()

**Comment by tanjianaus** [comment]
<img width="515" alt="screen shot 2018-03-25 at 10 33 33 am" src="https://user-images.githubusercontent.com/37756603/37870046-443867da-3018-11e8-8177-8639a8332ad8.png">

**Comment by kspearrin** [comment]
This is most likely because you are the only owner of an organization. We will have to delete it for you. Email us.

**Comment by tanjianaus** [comment]
Why would a delete fail if you are the only owner of an organization?
Wouldn't that normally 'allow' a delete - and only if there are multiple
users/shares - would a delete fail?

Or is it a protection mechanism to prevent loss of data? (i.e. if only one
user exists require a manual interaction by bitwarden staff)

**Comment by kspearrin** [comment]
Yes, because if we allowed the only owner of an organization to delete their account the organization could then be orphaned resulting in possible unexpected data loss. The organization also has to be deleted in this case.

**Comment by tanjianaus** [comment]
Ok thanks
I have replied on a seperate thread approving the removal of my account and
associated organisations.

Please advise when done so I can re-register
