### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by UlisesTJ** [bitwarden/web#197]
Hello! I'm interested in providing a Logo for this project _for free,_ if so, i would like to know how we can get in touch. Cheers!

**Comment by kspearrin** [comment]
Wrong repo. See https://github.com/bitwarden/brand

**Comment by UlisesTJ** [comment]
I'd like to offer a new one if it interest you.

**Comment by UlisesTJ** [comment]
I wanted to say that I can offer you a better logo, if you want I can send you my proposal and if you like you can use it for free
