### ISSUE TITLE
Sidebar and multiple windows do not sync state

### ISSUE THREAD

**Issue by AMDphreak** [bitwarden/web#198]
Plugin does not sync with app's logged in status or data.
Sidebars do not sync properly with the plugin's logged in status.
Sidebars do not sync status between Firefox windows.

Videos:
1. [Plugin not synced with app](https://youtu.be/hvz4Qbf3f3U)
2. [Sidebars not synced across Firefox windows](https://youtu.be/TwvELHuFyz4)

**Comment by kspearrin** [comment]
This is not the correct repo for this. You want https://github.com/bitwarden/browser
