### ISSUE TITLE
TOTP from 1Password 1pif imports generate invalid codes

### ISSUE THREAD

**Issue by takerukoushirou** [bitwarden/web#199]
I just purchased Premium membership and tested out the TOTP functionality of the client app and web browser extensions. I've previously been using 1Password and imported two accounts via the 1pif import.

The codes generated by Bitwarden for the imported accounts are rejected by the websites as being invalid. The values that were imported into Bitwarden are URIs of the form (e.g. for Microsoft):
`otpauth://totp/Microsoft:<username>?secret=<secret>&issuer=Microsoft`

**Comment by kspearrin** [comment]
You need to change the stored key to just <secret>. Bitwarden does not currently support full `otpauth://` schemes imported from 1Password.

**Comment by takerukoushirou** [comment]
@kspearrin thank you for the quick feedback. It seems a part of the message was filtered out, but I tested this with one account and replaced the URI with the `<secret>` part and now Bitwarden generates the same codes as 1Password does.

Are there plans for supporting the `otpauth` scheme eventually?

**Comment by kspearrin** [comment]
Yes, we eventually plan to support the URL scheme so that things like algorithm and digit legnth can also be specified. We are tracking this feature request in our forums.

**Comment by takerukoushirou** [comment]
@kspearrin awesome, glad to hear that. Can you point me to the feature request? I couldn't find one on https://community.bitwarden.com regarding TOTP scheme support for voting.

**Comment by kspearrin** [comment]
Here: https://community.bitwarden.com/t/support-sha-256-totp-keys/37

I've updated the title and description to include this request.
