### ISSUE TITLE
"Copy Password" Tooltip resizes password-field

### ISSUE THREAD

**Issue by MitoG** [bitwarden/web#2]
When hovering over the "Copy Password" button inside the ValutEditSite modal until the tooltip displays the size of the "Copy Password" field changes to about 50% of its original size.

**Comment by kspearrin** [comment]
What browser are you using?

**Comment by MitoG** [comment]
Firefox v. 49.0.1 for MacOS

**Comment by kspearrin** [comment]
Resolved.
