### ISSUE TITLE
Incorrect error when saving custom field value of >687 characters

### ISSUE THREAD

**Issue by tomwassenberg** [bitwarden/web#202]
When trying to save a new secure note with a custom field that has a value of >687 characters in the web vault (using Firefox 59.0.3), I get the following error: `The field Value must be a string with a maximum length of 1000.` When trying to perform the same action using the Firefox add-on (v1.26.5) I get no error, but the note doesn't get created either.

To reproduce: I called the field "example" and filled the value of the field with 688 occurrences of the character "a".

**Comment by kspearrin** [comment]
This is because the server error is about the encrypted value sent to the server. As you discovered, 687 plaintext characters is resulting in an encrypted value larger than 1000 characters.

I am not sure why you don't get the error message in the extension. We need to look into that.

**Comment by tomwassenberg** [comment]
Aha, thanks for the quick response. For usability reasons, it might be better to do this check before encrypting the input? Then it's less confusing for users, and they might be able to change the value to fit it in.

Also, it would be more user-friendly if the error message mentioned which of the fields the message is concerning, because "Value" can apply to more than one custom field.

**Comment by kspearrin** [comment]
Yes, it was deemed a pretty uncommon edge case to hit for users, so there hasn't been much love in making the error messages clearer yet.

**Comment by kspearrin** [comment]
I have adjusted the error message to be more clear in the next version.
