### ISSUE TITLE
"All Items" view gets terribly slow

### ISSUE THREAD

**Issue by Mart124** [bitwarden/web#203]
Hi,

The Web Vault default view is the "All Items" view.
Unfortunately this view gets terribly slow to load when user has many items / shares many collections.
Which then makes Bitwarden quite unusable.

Could you then, by default, avoid to display all items ?
Perhaps the Favorites instead ?

Of course issue is also encountered when displaying an organization vault.

I'm not sure about the default view in the other applications (desktop, mobile, browser plugins...), but they could also be concerned.

Thank you !

**Comment by kspearrin** [comment]
How large of a vault do you have?

**Comment by Mart124** [comment]
More than some thousands of items in some cases :|

**Comment by kspearrin** [comment]
Does v2.0 resolve this for you? https://github.com/bitwarden/web/issues/217

**Comment by Mart124** [comment]
Yes @kspearrin it definitely helps, it's faster, thank you 👍

I however still wonder, what about giving users the opportunity to choose their "starting" (connection time) view ?
And perhaps make the Favorites view the default one ?

Thank you again !

**Comment by kspearrin** [comment]
Great. Thanks for verifying. These would be separate feature requests that you can open on the forums if you'd like.
