### ISSUE TITLE
[error: cannot decrypt] in Web Vault

### ISSUE THREAD

**Issue by Turbobommel** [bitwarden/web#205]
After upgrading to the latest Bitwarden Version 1.26.0, all items in the overview of the web vault are displayed as "[error: cannot decrypt]" instead of showing the item and folder name. By entering the detailed view, all information is displayed correctly, except the folder. All foldernames in the dropdown are "[error: cannot decrypt]", too.

On mobile devices and firefox addons, everything is fine.

**Comment by kspearrin** [comment]
It’s probably a caching issue. Try clearing browser cache.

**Comment by Turbobommel** [comment]
Tried different browser and computer, same result.
A clean install and data import got me back on line.

**Comment by Mart124** [comment]
How did you import data ?
Using the MSSQL DB backups ?

**Comment by Turbobommel** [comment]
Imported the csv backup taken before upgrading Bitwarden.

**Comment by andrejkurusiov** [comment]
It's back again with Chrome plug-in.
