### ISSUE TITLE
[Q] Why no custom cert?

### ISSUE THREAD

**Issue by AL3x3y0** [bitwarden/web#206]
Hi, just wondering why are you using cloudflare free certificate even on vault.bitwarden.com?

![image](https://user-images.githubusercontent.com/29476322/40577451-d5604528-6116-11e8-8abb-77cb7370710b.png)

**Comment by kspearrin** [comment]
All of our services are behind Cloudflare. We use Full SSL (strict). https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-mean-


We use Let's encrypt certs along with them.
