### ISSUE TITLE
Not able to access website in old systems

### ISSUE THREAD

**Issue by werunom** [bitwarden/web#207]
This is continuation of [this issue](https://github.com/bitwarden/web/issues/195) that I had raised earlier. (Since I couldnt open the old issue again, I opened a new one).

I have now some more information regarding the `scenario#2` I had mentioned earlier. I could not access bitwarden website in a desktop which was running Win XP. Below is the screenshot of Chrome showing the error

![bitwarden](https://user-images.githubusercontent.com/24664855/40598183-e4857e94-6263-11e8-9e00-23d0a91778b8.JPG)

The version of Chrome is mentioned in this screenshot - 
![chrome](https://user-images.githubusercontent.com/24664855/40598195-fd43e57e-6263-11e8-9417-fbb084a4112f.JPG)

Lastly, I was able to access other password management websites like Lastpass.

Kindly look into this as this issue is now reproducible.

**Comment by kspearrin** [comment]
As the error message is indicating, I suppose this older version of Chrome does not support new SSL cipher suites that we require since they are not considered secure. Is it not possible to upgrade to a newer version of Chrome?

**Comment by werunom** [comment]
As the second screenshot says, for XP and Vista, the latest version of Chrome are not available. 

Even if I install the latest version in this desktop, this might solve the problem of accessing bitwarden in this desktop. But what about the possibility of accessing bitwarden in other places where they might not have the required OS or Chrome version?

What I wanted to suggest through this problem is the possibility of still encountering operating-systems (Vista, XP, Millenium, etc.) or old browsers' version in various places. In all these situations, I am unable to access bitwarden. For instance, imagine,  you travel to some place and you want to access your mail account in some internet cafe. You do not want to ask the person-in-charge to update the chrome, etc. 

So, is there a solution to make bitwarden work in these cases? [As mentioned, other password services, like lastpass, opened in these situations.]

**Comment by kspearrin** [comment]
There is no solution at this time. We will have to investigate compatibility with these older browsers.

**Comment by Tmarty** [comment]
Side note: Both a system not having the latest security updates and me not
owning the device would by themselves be reasons for me not to want to log
in to my email, let alone my password manager. The thought of these two
combined... 😱

**Comment by elliotroy** [comment]
Have had a look around some forums, and people are saying they have fixed this issue by using Firefox with older operating systems. Nevertheless, I would advise against using Windows XP and Vista as they are unsupported by Microsoft and have tones of security vulnerabilities.

**Comment by werunom** [comment]
True! I personally dontuse these obsolete systems. 

All I am trying to portray here is a rare situation - when you end with an old computer and no other option, and you need to login to your mail id. (In the above case, I had to take printout for my presentation in an institute where the printer was connected to this obsolete system.) In cases like this, there is no way you can login to your mail id because only bitwarden knows the 20-char long password. 

To emphasize again, I am not painting a daily scenario where one uses XP. I am just suggesting a situation where you _have_ to access your mail id, but are stuck because of the issue mentioned.

In cases like this, only having your mobile saves you; but imagine typing this password letter by letter. But what if there is no mobile connectivity? Then there is no option of logging into your mail id at all!

I know situations like this are rare; but in the last one year, I have faced this situation twice. (In a first-world, developed country, situations like these are rare; but imagine a third world country, where XP and obsolete systems are not that rare). 

In both these situations, I noticed that lastpass website opens. I mention it here only to suggest this - if lastpass is providing service in XP, then there might be ways of implementing this securely. (Of course, lastpass might be wrong here.)
