### ISSUE TITLE
Angular Migration/Rewrite

### ISSUE THREAD

**Issue by MrBlaise** [bitwarden/web#209]
Does anyone working on migrating the web app to Angular from angularjs? Eventually angularjs will be deprecated and Angular proved to be much faster and easier to develop with. I had previously rewritten the entire frontend at my company in Angular (it was angularjs as well), so I could definitely help. 

**PRO:** Modern, faster especially on mobile devices, native TypeScript support, future proof, cleaner code structure. Relatively easy going from angularjs.

**CON:** Takes some time, depending on the size of the project and the complexity. It is possible that some libraries are missing or not yet migrated to Angular yet, but these are rare these days.

Let me know what are your thoughts on this.

**Comment by kspearrin** [comment]
Like our other client apps have done already, and Angular conversion is planned.

**Comment by kspearrin** [comment]
Angular re-write is now in master.
