### ISSUE TITLE
Make `base` href configurable?

### ISSUE THREAD

**Issue by PlaidPhantom** [bitwarden/web#215]
https://github.com/bitwarden/web/blob/c1a081837692c7c9068b27940c23aceb81396e50/src/index.html#L32

Hi I would really love to run a self-hosted Bitwarden, however my current environment is geared towards running applications a subdirectories of a common domain (proxied through Apache).  From testing, I've been able to set the domain settings to include the subdomain, but the one thing that doesn't respect that setting is this `base` declaration.  If this could be somehow configured in the docker container it seems as if everything else would work.

**Comment by kspearrin** [comment]
Base will be `<base href="" /> ` in 2.0.0 . Will that work?

**Comment by PlaidPhantom** [comment]
I bet that would work. Thank you!
