### ISSUE TITLE
Hovering on minimized sidebar

### ISSUE THREAD

**Issue by bin0** [bitwarden/web#22]
So when you minimize the sidebar (personally I really like it minimized) it shows smaller icons. When you hover over the icons, the sidebar then expands, forcing you to be then hovering over a list item that does not pertain to what you originally wanted to hover over.

On top of this, the hovering also has some glitchy-ness to it, like the containing text flashes outside the sidebar.

This seems a little silly, and I'm wondering if I can help out by removing this expand feature on hover, while providing in turn a tooltip upon hovering of an icon on the (minimized) sidebar. I think this will provide a fully minimized sidebar if the user wants, and also prevent glitchy-ness!

Thanks.

**Comment by kspearrin** [comment]
The sidebar has to expand in order to get to the real navigation options. I do agree that the while hover thing is a big glitchy feeling though.

What do you propose? Clicking the icon will then expand? Seems reasonable.

Another improvement that could be made here is to remember the collapsed setting via a local storage variable or something.

**Comment by bin0** [comment]
Okay, I see what you are saying, and you're right. Options with sub-options would be quite affected by my proposal.

Something we can look into is a dropdown appearing on hover. I know Bootstrap dropdowns are very flexible and can be put in just about anywhere.

As for local storage variable, yes! I agree with this.

**Comment by kspearrin** [comment]
Seems possible to get dropdowns working with AdminLTE. Check out https://almsaeedstudio.com/themes/AdminLTE/pages/layout/boxed.html

**Comment by bin0** [comment]
Yeah I love this!

I can get working on this if you'd like.

**Comment by kspearrin** [comment]
Go for it!
