### ISSUE TITLE
[2.0preview] Ease up on the favicon loading

### ISSUE THREAD

**Issue by da2x** [bitwarden/web#220]
Firefox is giving me a spinning mouse cursor as the page tries to download hundreds of favicons at the same time. For me it’s 1.2 megabyte of favicons. People on slower connections and more expensive data plans than me don’t appreciate loading resources they might not need. E.g. this would be painful to load over satellite.

How about only loading favicons progressively. It’ not like you loose a whole lot of functionality if an icons is delayed and loads a bit slower. Maybe only load for three times the number of sites that are visible on screen? (So currently visible sites plus two screens of scrolling worth of favicons.)

**Comment by kspearrin** [comment]
Please keep discussion regarding the preview in the designated issue.
