### ISSUE TITLE
Importing from Password Agent

### ISSUE THREAD

**Issue by falcon50soars** [bitwarden/web#221]
<! I have been using freeware Password Agent for many years but want to start using Bitwarden, as a free, cross-platform, open source password manager. Password Agent is no longer free and is far behind other PM managers now, so I want to get off of it even if Bitwarden doesn't work for me. But from what I've read, you have added the ability to import from other password managers not on your current list, so I'm hoping that you might be able to do the same with PWA. I exported one small, relatively public category of login info as a .csv file and disguised the id's and passwords. The .txt file is attached. I also attached a screen shot of the export window showing the fields included in the .csv (all the fields available in PWA). 
I'll be happy to send you anything else you might need.
Website: http://www.moonsoftware.com/password_agent
Thanks much!
[2018-0723 PWA spiritual.txt](https://github.com/bitwarden/web/files/2220980/2018-0723.PWA.spiritual.txt)
![pwa screen shot](https://user-images.githubusercontent.com/41594698/43102276-a9f8ec14-8e98-11e8-9e68-aa29b59161a7.jpg)

-->

**Comment by kspearrin** [comment]
I added an importer for this in web vault 2.0. You can test it here:

https://github.com/bitwarden/web/issues/217

**Comment by falcon50soars** [comment]
It works great. What an incredibly fast response! Thanks so much!
