### ISSUE TITLE
JavaScript Error trying to log into vault via web using yubikey and Firefox

### ISSUE THREAD

**Issue by cadecairos** [bitwarden/web#229]
I'm using Firefox 63 and a Yubikey Security Key. When the u2f prompt loads I see this in the console

```
 [Show/hide message details.] TypeError: setting getter-only property "u2f"[Learn More] u2f.js:697:5
<anonymous>
https://vault.bitwarden.com/scripts/u2f.js:697:5
<anonymous>
https://vault.bitwarden.com/scripts/u2f.js:14:2

```

It works fine in Chromium, and logging into Fastmail using the key works fine in Firefox 63.

**Comment by kspearrin** [comment]
Does it work in Firefox Stable?

**Comment by cadecairos** [comment]
One minute, I'll give it a go!

**Comment by cadecairos** [comment]
It appears to be fully implemented, but according to [this wiki page](https://wiki.mozilla.org/Security/CryptoEngineering#Web_Authentication) it will remain behind a "user-controllable preference". It seems they might be waiting for Google and Facebook to support the standard before making it widely available, since most folks wil lblame Firefox for not working with their keys when it's really the site that's not implementing the standard.

Is the site using a 3rd party u2f library that might need an update?

**Comment by kspearrin** [comment]
We only try to set u2f if the browser doesn't support window.u2f already. Something must be different in 63. I don't have nightly installed on this machine, so I'll need to install it and check out whats going on.

**Comment by kspearrin** [comment]
Here is the check we use:

```
    var root = window;
    var isFirefox = navigator.userAgent.indexOf('Firefox') !== -1 || navigator.userAgent.indexOf('Gecko/') !== -1;
    var browserImplementsU2f = !!((typeof root.u2f !== 'undefined') && root.u2f.register);

    if (isFirefox && browserImplementsU2f) {
        root.u2f.isSupported = true;
        console.log('u2f is supported already');
    } else {
        console.log('u2f is NOT supported');
       // do other stuff and try to set window.u2f, should never happen on Firefox
    }
```

Can you try to run this in dev console?

**Comment by cadecairos** [comment]
I'm sorry, this was me. I had a user-agent modifying extension running from unrelated testing that was messing up the u2f check!

This issue is not valid!
