### ISSUE TITLE
multiple import categories duplicate

### ISSUE THREAD

**Issue by tykayn** [bitwarden/web#231]
after doing several imports from lastpass csv, i expected the web vault to populate the already existing categories, instead it created a duplicate for each category.
i have deleted all entries and reimported all with the same csv, but categories were duplicated again.
how could we fix that ?

**Comment by kspearrin** [comment]
Imports will not detect existing categories. You will need to make sure all of your data is in 1 import file with an empty vault when you do the import to avoid duplicates.

**Comment by tykayn** [comment]
yes, the import manager will not handle that, it was not clear but my post was about suggesting to add this feature
