### ISSUE TITLE
Yubikey password modal are not the same size

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/web#236]
When asked for master password to manage the 2FA settings, the Yubikey modal is larger than any other.

**Comment by kspearrin** [comment]
Yes, this is on purpose since there is more content than all the others.

**Comment by Crocmagnon** [comment]
I do not see more content at the password step 🤔 
<img width="516" alt="capture d ecran 2018-08-04 a 11 35 22" src="https://user-images.githubusercontent.com/3630554/43674881-988bdc16-97da-11e8-863a-cca4c5d10ea5.png">
<img width="811" alt="capture d ecran 2018-08-04 a 11 35 30" src="https://user-images.githubusercontent.com/3630554/43674882-98a20df6-97da-11e8-8454-39c49433bfd2.png">

**Comment by kspearrin** [comment]
You have to go to the next step, where you input your keys.

**Comment by Crocmagnon** [comment]
Hm ok, I thought the master password modal was a separate modal than the next one. I find that a bit odd but I guess I'm alright with this. At least it's intentional, so it's not a bug an therefore could be closed 🙂
