### ISSUE TITLE
Increase cache time significantly for static resources

### ISSUE THREAD

**Issue by da2x** [bitwarden/web#239]
The vault is slow to load on a slow connection even with a primed cache.

The static assets in the web vault (images, fonts, stylesheets, and scripts) are only cached for four hours (except favicons which are cached for a week). Please increase the cache duration for these static resources to at least a month. You’ve already got unique names for scripts and stylesheets which means you can already deploy changes and bypass caching if the need arises.

Likewise the vault login page should be increased up from five minutes to several hours.

**Comment by kspearrin** [comment]
I adjusted cache control headers to 2 weeks for js/css/fonts and 5 days for images.
