### ISSUE TITLE
Add a Web App Manifest and a Service Worker

### ISSUE THREAD

**Issue by cdata** [bitwarden/web#24]
_As a Bitwarden mobile web user,
when the network is flakey or non-existent,
I would like to retain access to my vault,
so that I can remain productive regardless of the network state._

Bitwarden is pretty great (kudos on the awesome work you're doing). I love that it has a web interface that is usable on both my laptop and my phone. However, if I'm on my phone and I lose network connectivity (and I don't have the Android app installed), I basically lose access to my vault.

There are new standards-based features available in some browsers today that might allow the app to remain functional even without network connectivity.

Service Worker allows an app to control caching so that the static assets and the vault are consistently available when the user is offline (depending on your architecture, possibly restricted to a read-only mode).

Web App Manifest isn't necessary for offline availability, but it would allow users in some browsers to easily add the web app to their homescreens and launch it without browser chrome.

As a user who always prefers web-based apps to native ones when available, it would be really delightful to me to have these features implemented in the Bitwarden web client.

**Comment by kspearrin** [comment]
Thanks for the feedback. The extension and mobiles apps will function just fine without connectivity. I definitely had not anticipated that people would want to use the web vault in this way.

I'll leave this open as an idea to start thinking about it.

**Comment by cdata** [comment]
Thanks for the response. I'm happy just to know that you're considering the idea.

> I definitely had not anticipated that people would want to use the web vault in this way.

Do you perceive architectural barriers to making the offline web flow work?

**Comment by kspearrin** [comment]
Potentially. It would likely require a good chunk of refactoring to make it work. I'm not familiar with service worker at all, so I would need to do some investigating first to see if it is possible.

**Comment by cdata** [comment]
Note: the following comment is speculation from a position of complete ignorance about this app. So, take it with a grain of salt.

Much of the web app appears to be static, so there is a good chance that a Service Worker that satisfies the basic use case of offline availability can be added without severe refactoring. Service Worker can be thought of as a network proxy that can observe network requests as they are made and optionally decide to cache the responses so that they can be served from cache when the same requests are made offline. In some cases, it is sufficient to apply a Service Worker that uses a consistent serve-from-network-first, serve-from-cache-if-offline strategy for all resources.

**Comment by kspearrin** [comment]
Doesn't sound too bad. The majority of the work would probably have to be in regards to the API calls and vault data then. Moving to a structure like the apps and extensions do where the vault data is stored and read from locally and kept in sync with the sever during certain key events.

**Comment by cdata** [comment]
There are also [tools available](https://github.com/GoogleChrome/sw-precache) that will generate advanced Service Workers for you based on a static analysis of your site's assets, so it might be easy enough to integrate it as part of a future optimizing build step.

Anyway, thanks for thinking about it :)

**Comment by graingert** [comment]
@kspearrin service workers can also be configured in a way that the code cannot be changed without the user initiating the update.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
