### ISSUE TITLE
Adding item while collection is selected - will add it to unassigned collection

### ISSUE THREAD

**Issue by mohligschlaeger** [bitwarden/web#241]
Adding a new item in the vault of our organization while a collection is selected the item allways will be added to unassigned collection.

That appears wrong to me. Currently we are doing our initial import to different collections. That should be fixed.

**Comment by bradyjoh** [comment]
+1 on this. I also haven't figured out how to add items to collections from anywhere other than the web interface. The browser plugin and desktop client don't seem to support the "share" option as far as I've found
