### ISSUE TITLE
Mobile version of vault not presented on windows mobile (edge)

### ISSUE THREAD

**Issue by bvli** [bitwarden/web#242]
I don't really know when this happened, but lately I've been presented for the desktop version of [my vault](https://vault.bitwarden.com) when accessing it via my windows phone (windows mobile 10) browser (edge).

The desktop version is almost not usable from a phone.

**Comment by kspearrin** [comment]
This is expected. There is no longer a mobile optimized version of the web vault. However, the desktop version should be perfectly usable from a mobile device still. It just requires some zooming. What part about it is not usable?

**Comment by bvli** [comment]
Sorry to hear that. It **is** usable (sorry of I was a bit harsh) - except that I need to zoom a lot, and that it asks for my yubikey (as it should on the desktop, but isn't supported on the WP). 

I just was so happy about the mobile optimized vault - and as there's no bitwarden app for WP I hoped this was an easy to fix thing.

Thanks for your answer!
