### ISSUE TITLE
Fix bug where attachment gear icon does not show up

### ISSUE THREAD

**Issue by joelparkerhenderson** [bitwarden/web#246]
I found an issue using Bitwarden web that seems like a bug. 

When I view the main page "My Vault", then I see my item as I expect, with the item name, share icon, paperclip attachment icon, etc.

But there's no icon to use the attachment.  

Chrome inspector shows that there's a CSS overlap issue: the "Organizations" box is visually obscuring the attachment button.

When I put the item into a folder, and view the folder, the item shows up correctly, and does the typical behavior e.g. when I mouse hover over the icon, then the attachment icon appears.

Suggestion 1: fix the CSS.

Suggestion 2: make the paperclip icon usable, i.e. when I click the paperclip icon, then the web page could prompt me to download the attachment.

Suggestion 3: make the "Organization" box dismissable, or smaller, or moved to the left, anywhere that the box doesn't obscure the items.

Suggestion 4: change the workflow so it doesn't depend on hover, i.e. show some kind of usable icon all the time; my opinion is this is also a better UI for discoverability for new users and intermittent users.

**Comment by kspearrin** [comment]
Could you post a screenshot? The options box is suppose to open the opposite direction of the organization box, so I am a little confused as to what you are describing.

**Comment by joelparkerhenderson** [comment]
Thanks for the fast response. I emailed the screenshot to hello@bitwarden.com, rather than post it here, because it contains identifying info. If you definitely need the screenshot posted here, let me know and I can scrub the identifying info.

**Comment by kspearrin** [comment]
From your screenshot, the massively long name of the last item appears to be breaking the design. Try giving it a shorter name and it should fix it.

**Comment by joelparkerhenderson** [comment]
> From your screenshot, the massively long name of the last item appears to be breaking the design. Try giving it a shorter name and it should fix it.

If I understand what you're writing, you're suggesting that forcing the name to be shorter is a  workaround for CSS that breaks the design. Yes?

What this seems to indicate to me is that there's a missing test: it sounds like the Bitwarden CSS is intended to display the cog, but has not been tested with long names. This in turn shows that there's a test missing for sanitizing inputs, e.g. testing when a particular fuzzing of input can trigger a bug that disrupts functionality of other unrelated items.

If you're correct about your diagnosis, then the workaround is not actually bug fix, because the workaround doesn't fix anything in the code, e.g. any user in any org that does a similar set of items will trigger the breaking CSS.

What's the next step to a bug fix i.e. fix the CSS so it works as intended? Or to move the cog icon from he right to the left? Or to move the "Organization" box elsewhere?

**Comment by kspearrin** [comment]
Yes, the suggestion is a workaround, not a fix. The fix is to truncate long names in the listing.

**Comment by kspearrin** [comment]
Fixed in next version with text wrapping.
