### ISSUE TITLE
Error 1006

### ISSUE THREAD

**Issue by rakshazi** [bitwarden/web#252]
Hello!
Sorry for posting it here, but I have no access to ANY of bitwarden websites (including forum).
I got following error:

```
Error 1006 Ray ID: 45160c7b5df8b6da • 2018-08-28 10:21:02 UTC
Access denied
What happened?
The owner of this website (community.bitwarden.com) has banned your IP address (37.233.52.140).
```

And the same error for all websites, including desktop client (can't login or do anything, developer tools shows 403 error with the same text on `/prelogin`)

Steps to reproduce:
1. Use Yandex.Browser
2. Try to import passwords from that browser and fail (because that feature disabled in hardcode)
3. Try to add all your passwords manually in bitwarden
4. On 39th password (I started to hate browser on 10th, but...) you will receive that error

Please, whitelist my ip (it's "white" static IP belongs to office).

Best regards,
Nikita Chernyi.

**Comment by kspearrin** [comment]
Hi,
This should automatically clear up after 30 minutes. Are you able to access now? It seems something that you did triggered our abuse detection system (false positive maybe?).

**Comment by rakshazi** [comment]
Yep, it works.
I did a lot of requests (tried to create and update 39 passwords manually) and CF banned for that, but it's weird - I didn't ddos bitwarden.
May be you can increase requests limit or show more info about that in desktop and mobile clients? Something like "Sorry, request limit exceeded, try again in 30 mins", because current error message is not friendly at all :)

**Comment by gotson** [comment]
Just chiming in as the same problem just happened to me. I just started to use Bit Warden, and coming from Chrome password manager i had a lot of duplicates to manually dedupe, hence all the manual actions.

That's a bit un-welcoming :|

**Comment by rakshazi** [comment]
Yep, seems the problem still present. It's not a bug, just unfriendly situation :/

**Comment by sebastiand16** [comment]
Same here. Just edited lots of my passwords and Error 1006 poped up :(

**Comment by rakshazi** [comment]
Guys, please, add more infromative text. Something like "Sorry, request limit exceeded, try again in 30 mins", because current error message is not friendly at all

**Comment by sebastiand16** [comment]
Exactly. Especially that after buying premium account, I started to move all my passwords to the new place, so it's quite expected that it will increase number of requests from single IP.

**Comment by kspearrin** [comment]
@rakshazi We have added a better, more informative page when this happens to people in the future.
