### ISSUE TITLE
Enpass import has quirks 

### ISSUE THREAD

**Issue by AnthonyGiorgio** [bitwarden/web#257]
I tried importing my Enpass vault in CSV format, and encountered some difficulties.  Specifically, the "Username" and "username" fields prevented many of my logins from being recognized as such, and caused Bitwarden to import them as a note field.  I edited the CSV and renamed these fields to "Email", and continued with the import.

The next problem I encountered was that any login that had a "password" field was imported as a note.  I updated the CSV so that these fields were all named "Password", and the import completed successfully.

Perhaps the Enpass import logic should be case insensitive for the field names, as well as realizing that email and username indicate a login item?

**Comment by kspearrin** [comment]
I found some checks that were case sensitive that might have caused this. Should be fixed next version.
