### ISSUE TITLE
Ability to edit in the "current tab" - Browser Extension

### ISSUE THREAD

**Issue by st167** [bitwarden/web#26]
Add edit button next to Copy Username/Password option - in the "Current Tab". 

![edit](https://cloud.githubusercontent.com/assets/23350116/20141237/6cdeedc6-a65d-11e6-9f02-f171303b902f.png)

Also, have ability to delete when the edit window opens - similar to  #25

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/40

**Comment by st167** [comment]
Sorry didn't see that in search, thanks for logging it.
