### ISSUE TITLE
Microsoft Edge - Vault - Collections checkbox won't click

### ISSUE THREAD

**Issue by BayerInteriorWoods** [bitwarden/web#265]
When trying to share an item to a collection on Edge, the checkbox next to the collection will not respond to a click. Using "Select All" and "Unselect All" works though.

Works just fine in Firefox, don't have Chrome to try.

Edge version is 42.17134.1.0

![image](https://user-images.githubusercontent.com/43070329/45959944-b2508100-bfe0-11e8-8753-a4b26f4fa3fb.png)

**Comment by kspearrin** [comment]
Thanks. Will be fixed next version. As a workaround, just don't click the actual checkbox itself. Click somewhere else in the row.
