### ISSUE TITLE
Use of CloudFlare is concerning

### ISSUE THREAD

**Issue by dentych** [bitwarden/web#268]
Hello.

I have seen that Cloudflare has been mentioned in a few other issues, but nothing directly asking the question: Why is Bitwarden using Cloudflare? To me, it seems like a Password Manager should have full end-to-end encryption of all data transmitted. With Cloudflare, all requests are intercepted and SSL is terminated at the Cloudflare edge servers, before being re-encrypted from edge server to Bitwarden server. To me, this seems very troublesome. Who knows what happens to the data while in unencrypted state? What will be logged?

Has this been considered?

**Comment by ids444** [comment]
While I'm not the dev, I think you are conflating two different encryptions. Bitwarden like the other password managers encrypts your vault on your devices with your passcode and then send it to the server using SSL. Even if cloudflare is intercepting the data maliciously all they will get is your encrypted data and would need your passcode to decode it. The passcode never leaves your devices so even the bitwarden devs can't decode your vault even if they wanted to.

**Comment by mprasil** [comment]
There's still a valid concern though. Cloudflare could modify the JavaScript to access your passwords. I don't think it's very likely though.

**Comment by ids444** [comment]
No they can't, the same way Bitwarden devs can't. The data leaves your computer encrypted with your passcode. THEN it's transmitted over an encryped SSL connection. The SSL connection has no relation to your data being encrypted already.

**Comment by mprasil** [comment]
The issue is filled under Vault source code. With Vault they can in theory modify the JavaScript to send all your passwords to their DB once you enter your password.

**Comment by kspearrin** [comment]
We use a variety of Cloudflare's services such as DNS, CDN, firewall, page rules, rate limiting, etc. These services are critical to protecting and scaling our cloud service. If Cloudflare is an issue with your threat model you should consider hosting Bitwarden on your own servers.
