### ISSUE TITLE
Bulk Site to Folder Move

### ISSUE THREAD

**Issue by Xarkam** [bitwarden/web#27]
Hello,

Can you add the possibility to make a massive folder change for a list of password ?

Thanks.

**Comment by kspearrin** [comment]
Can you give an example please?

**Comment by Xarkam** [comment]
Yes; I have imported my chrome passwords and I have no possibility to move multiple entries in a folder.

I will create a folder named Atlassian for moving my all Jira entries in this folder in one time.

**Comment by kspearrin** [comment]
I see. Yes, this is not possible at the moment. I will backlog this as a good idea to add in the future.

**Comment by simonknittel** [comment]
Maybe it would be cool to Drag and Drop entries around. To drag multiple entries around at the same time they we should be able to selected them with Ctrl. When that is possible an other cool addition would be to have a "drop zone" to create a new folder "on the fly".

**Comment by zQueal** [comment]
> Maybe it would be cool to Drag and Drop entries around.

Serious 👍 for this. 

@kspearrin any timeline, or is this feature not even on the radar yet?

**Comment by kspearrin** [comment]
@zQueal I haven't planned it yet, but I'll look into it. The web vault needs several bulk actions for move, delete, share, etc.

**Comment by kspearrin** [comment]
Bulk options for deleting and moving logins will be available in next release.

See screenshot:

![capture](https://user-images.githubusercontent.com/1190944/26978382-5f54ec30-4cf9-11e7-8c9b-dcf1ed4df53f.PNG)

**Comment by zQueal** [comment]
@kspearrin Looks perfect! Thanks for the great work.

**Comment by Unknow0059** [comment]
@kspearrin This is not available in the web extension. Are there plans?

**Comment by c02y** [comment]
This feature is not available in browser and desktop(Linux) application, any plan?
