### ISSUE TITLE
Incomplete Export

### ISSUE THREAD

**Issue by lorenzschmid** [bitwarden/web#274]
Exporting your passwords from a vault is unfortunately incomplete missing the following items:

- Credit cards
- Identities

Furthermore, the following item settings are not exported:

- Domain match detection
- Properties of a custom field (hidden, text, etc.)

**Comment by Sharky444** [comment]
This needs to be fixed ASAP. If you export your "complete" vault, you have to rely on that export to be 100%. Everything else is unacceptable.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/web/issues/148
