### ISSUE TITLE
Strange (but non-blocking) error message when trying to subscribe as Premium using Paypal

### ISSUE THREAD

**Issue by ewjoachim** [bitwarden/web#278]
Hello,

I was trying to switch to a premium account. When I clicked on the Paypal radio button at first, nothing specific happened and so I clicked Submit and got this error (top line is correct in French, bottom is... not):

<img width="339" alt="capture d ecran 2018-10-16 a 19 46 32" src="https://user-images.githubusercontent.com/1457576/47036370-a63d8680-d17c-11e8-9f7d-c1b4a5095b7b.png">

A few seconds later, the paypal button appeared between the radio button and the Submit button, and pressing the Submit button again, this time I get a "normal" error (albeit untranslated)

<img width="333" alt="capture d ecran 2018-10-16 a 19 51 36" src="https://user-images.githubusercontent.com/1457576/47036500-f7e61100-d17c-11e8-9a5a-959d1aa8ab45.png">

Once the paypal authorization was given, it worked as expected. I'm just reporting the first error (when you're about to pay money and you get something that looks like a bug, it can be complicated).

I was able to reproduce by following the same steps. In order to reproduce, you may need to throttle your connection, I suspect that the time between selecting paypal and having the button appear depends on an ajax call, so on your connection speed.

**Comment by kspearrin** [comment]
Thanks for the info. It would seem that the Braintree PayPal script had not loaded fully on the page yet. I am not sure what we could do to resolve this at the moment. I'll keep the issue open.

**Comment by ewjoachim** [comment]
(I'm wondering if at first, the script wasn't blocked by Ghostery)
