### ISSUE TITLE
Two-factor fallback?

### ISSUE THREAD

**Issue by a-m-s** [bitwarden/web#28]
If I enable two-factor authentication, and then lose/break/explode my phone, am I permanently locked out of my account?

There doesn't seem to be any fallback mode in the website login process. Presumably an SMS/telephone based solution is a bit out of scope for a project your size, so it would have to be some kind of email verification, or second super-secret password, or maybe a print-out-and-keep-safe single-use password like Google use.

**Comment by kspearrin** [comment]
@a-m-s This is being tracked here and we are planning to release it this week. https://github.com/bitwarden/core/issues/21
