### ISSUE TITLE
Master password not accepted when locked.

### ISSUE THREAD

**Issue by MarkJeronimus** [bitwarden/web#285]
When BitWarden is logged in and locked (because of "On Browser Restart", configured in settings) the 'Verify Master Password' does not accept my password on Linux but works fine on Windows. On both platforms, logging out and in works flawlessly.

Linux: Ubuntu 18.04, Firefox 63.0
Windows: 10 Pro, Firefox ESR 60

**Comment by kspearrin** [comment]
That's weird. It's the same code.

Can you try backspacing the password field to make sure it is clear of any whitespace/invisible characters or anything like that before typing your password?

**Comment by MarkJeronimus** [comment]
I do that always when I re-enter a password.

**Comment by kspearrin** [comment]
The only thing I can think of is that somehow a character on your keyboard that is used in your password is being treated differently between the two environments.

**Comment by MarkJeronimus** [comment]
The problem hasn't happened to me anymore.
