### ISSUE TITLE
Recovery code empty

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/web#29]
Hi,
The filed for the recovery code is empty:
![](http://imgur.com/EQkyX37l.png)

Tested on my Android phone and 2 web browsers (Iridium and Firefox).
Thanks.

**Comment by kspearrin** [comment]
Can you contact me on the website via the contact form with your account's email address so I can look?

**Comment by kspearrin** [comment]
This should be fixed now. I forgot to rebuild the database view after the release to include the new backup code column.
