### ISSUE TITLE
Circular JSON error when creating user

### ISSUE THREAD

**Issue by jfreak53** [bitwarden/web#294]
I've got the web vault built and it runs fine, goes to login screen. When I enter my info and click Register it gives me this JS error:

```
TypeError: Converting circular structure to JSON
 /app/polyfills.ac4de4605e1c223534bc.js:16
```

Running v2.5.0 from GIT compiled. Needless to say it won't create a new user.

**Comment by kspearrin** [comment]
Never seen that happen before... not sure really. What version of node are you trying to run with?

**Comment by jfreak53** [comment]
8.12.0. Strangely enough the mobile app works for creating an account and logging in. But I also can't login to the web vault after creating the user in the mobile app.

**Comment by jfreak53** [comment]
Web vault gives me this error when trying to login with the user I created in the mobile app:

```
Cannot read property 'importKey' of null
```

**Comment by kspearrin** [comment]
Sounds like you aren’t using https

**Comment by jfreak53** [comment]
No, is it required??

**Comment by kspearrin** [comment]
Yes.

**Comment by jfreak53** [comment]
Ok, where in the documentation does it tell me how to configure the https? I'm not finding it anywhere.

**Comment by kspearrin** [comment]
It’s already preconfigured for https. Just do ‘npm run build:watch’ as outlined in the readme.
