### ISSUE TITLE
"Purge Vault" does not delete collections

### ISSUE THREAD

**Issue by Swonkie** [bitwarden/web#299]
As the title says. I was left with about 200 (empty) collections. I needed everything gone before doing a fresh import.

Furthermore there is no bulk delete option for collections in the web interface and the CLI doesn't support deleting collections, even though the documentation says otherwise (I'll report the issue in CLI).

**Comment by kspearrin** [comment]
This is expected at the moment. We don't intend to delete collections since they could have user and group assignments. Maybe we should anyways?

**Comment by Swonkie** [comment]
In my opinion "purge" should get rid of all objects in the account (but don't remove the users).

Anyway it would also help if you could at least "select all" collections and then delete them all at once.

I had to extract a list of all collection IDs from the web interface (parse the raw JSON data from the browser request), then write a script which makes a DELETE request with all IDs, also sending the bearer token in the auth header. It was very cumbersome and most people won't even be able to do that.

**Comment by DirtyCajunRice** [comment]
@Swonkie Im in your situation right now. Id love a sanitized copy of your script if you have it?

**Comment by jdgregson** [comment]
I wrote a bit of JavaScript to do this on the Collections page in the vault. It's a bit buggy and caused a few 500 internal server errors, but if you run it a couple of times in the JavaScript console all of your collections will eventually be deleted:

    let deleteBtns = document.querySelectorAll('.dropdown-item.text-danger');
    for (let i = 0; i < deleteBtns.length; i++) {
      deleteBtns[i].click();
      let yesBtn = document.querySelector('.swal-button.swal-button--confirm');
      while (!yesBtn) {
        yesBtn = document.querySelector('.swal-button.swal-button--confirm');
      }
      yesBtn.click();
    }

**Comment by jeffbrite** [comment]
In the same situation. I imported my Lastpass data, which created a ton of collections and I wanted to remove it all and modify the Lastpass export and organize it better before importing it again. Now I have 100s of collections to remove by hand. 

Seems like some sort of multi selection should be available for collections. Maybe this is a feature request?

Jeff

**Comment by jeffbrite** [comment]
@jdgregson Thanks for that script. It was painful, but better than by hand.

**Comment by nmdemarco** [comment]
Understood that purging a vault can have user and group implications. I should be able to make those decisions when I'm purging the vault. The command needs additional process(es). If vault contains collections, how is it purged? If it contains groups, how are they purged?

**Comment by smcyr** [comment]
I made this script and it's working nicely:
```
let i = 0;
let deleteBtns = document.querySelectorAll('.dropdown-item.text-danger');

function deleteEntry(entry) {
    entry.click();
    i++;
    setTimeout(function () {
        document.querySelector('button.swal2-confirm').click();
        setTimeout(function () {
            if (i < deleteBtns.length) {
                deleteEntry(deleteBtns[i]);
            }
        }, 100);
    }, 100);
}

deleteEntry(deleteBtns[i]);
```
