### ISSUE TITLE
Master password strength 

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/web#3]
Currently the user is required to have length 8, 1 letter, and 1 number or special character. This was an easy way to prevent users from using dictionary words as passwords.  There is a desire for this rule to be more intelligent for users that create very long alpha passwords that are not dictionary terms.

**Comment by rafibaum** [comment]
Maybe using a Meyer like this: https://github.com/dropbox/zxcvbn to determine password strength. Uses more complex algorithms to determine strength than checking length and special characters (correcthorsebatterystaple compatible).

**Comment by cybercyst** [comment]
If you allow spaces, you get an easy win on this too -- (correct horse battery staple) being even more secure :)

**Comment by KWottrich** [comment]
It is important to provide feedback to the user to encourage stronger passwords.  However, I would suggest you consider allowing users to choose _any_ password.  Those that choose a weak password would do so at their own risk, but putting in strict requirements such as numbers or special characters could potentially reject otherwise-acceptable passwords.  This way, the user would be making an informed decision, but ultimately retains the freedom of choice.

**Comment by alexturpin** [comment]
+1, this is the only thing that prevents me from switching from LastPass.

**Comment by Plonq** [comment]
I agree with KWottrich. Inform the user of strength, but allow anything. Although, having a minimum of 8 characters is still fine.

**Comment by kspearrin** [comment]
I have relaxed this a bit for now with https://github.com/bitwarden/web/commit/440032ed4a9f398d009c0306ce29c4ac32ac184e to go out next release. I still need to look into providing warnings and strength indicators though,

**Comment by KanteLabs** [comment]
Yeah I think users should just have a length requirement maybe 6 characters long and then it you could have a strength indicator or warning

**Comment by ErikDahlinghaus** [comment]
I recommend you use zxcvbn for password strength validation and metering. It is the "industry standard" and they have ports for many languages.

https://github.com/dropbox/zxcvbn

**Comment by kspearrin** [comment]
`zxcvbn` looks great, however, it is almost 1mb in size, which is gigantic for JS library (more than all the assets on the website combined today). Not as much of an issue for the browser extension though since that is all downloaded and local.

Also, the C# port for it is way out of date and full of bugs so it wouldn't work for the mobile app. Will have to investigate more.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/warn-users-about-using-a-weak-master-password/233

This issue will now be closed. Thanks!
