### ISSUE TITLE
Importing files with multiple extensions broken

### ISSUE THREAD

**Issue by Plonq** [bitwarden/web#30]
What I did: Imported a file named "Enpass_2016-12-27_21-34-52.csv.txt" (exported from Enpass obviously)
What happened: I got a lot of sites in my vault with all fields empty except all their names were "--"

Removing the ".txt" from the filename resulted in a successful import.
I have only tested this with Enpass export/import.

**Comment by kspearrin** [comment]
Having multiple extensions probably isn't the issue (I just tested it and it worked fine for me). What's probably happening is that the file is is originally saved in a different encoding format that the importer cannot properly read and when you rename it on your computer it causes it to be re-saved with a proper encoding (UTF-8). Are you by-chance using a non-English language on your operating system?

**Comment by Plonq** [comment]
I think I've figured it out. I had some left-over from KeePassHttp which added field values like `{""Allow"":[""twitter.com""],""Deny"":[]}`. I removed all of these and didn't touch anything else, and my whole vault imported correctly.
