### ISSUE TITLE
Restrict icon size

### ISSUE THREAD

**Issue by michield** [bitwarden/web#301]
With sites having favicons like this, it would be useful to limit their size to one block only

https://icons.bitwarden.net/testi.at/icon.png

**Comment by kspearrin** [comment]
I'm not sure how I would do that. I'm also not sure why a website would make that their favicon. Seems weird...

**Comment by kspearrin** [comment]
I see. I misunderstood the issue initially. Yes, we just need to set a max height.

**Comment by kspearrin** [comment]
Should be fixed in 2.7
