### ISSUE TITLE
Incorrect TOTP codes are generated for some entries

### ISSUE THREAD

**Issue by tomwassenberg** [bitwarden/web#302]
_(I wasn't not sure of the best repo to open this issue on, since it's also occurring on the Firefox extension. Feel free to move it how you see fit.)_

I just needed to login to a certain website for the first time in a few weeks, using Firefox on Windows. However, the TOTP codes that the web vault derived for this entry, proved to be incorrect. When viewing the same entry in the iOS app simultaneously, I saw different codes being derived.

The stored TOTP "master" key is the same in both clients, and I performed a manual sync to make sure of this. The timestamp of the entry also corresponds on all clients. I also synced the time of my Windows PC.

The Firefox extension is also deriving the incorrect codes for this entry. The only client I tried that shows the **correct** codes for this entry, is the iOS app. Note that the problem isn't occurring for all entries with a TOTP key (tried one other which works normally).

**Comment by kspearrin** [comment]
Sounds like the system time on the device is incorrect, which would result in incorrect TOTP code generation.

**Comment by tomwassenberg** [comment]
Thanks for the quick response, but as mentioned I already synced the time of my PC, and manually verified that it isn't off (+/- 1s), compared to my iOS device.

**Comment by MatyCZ** [comment]
I have the same issue with Microsoft Account or GitHub. All web browser extensions generate the same invalid TOTP code. Tested in Chrome, Vivaldi and Firefox. Reinstall extension or browser doesnt work (remove user profile).

Only my Android app generates valid TOTP codes.

**Comment by TapeWerm** [comment]
My Windows Phone and Android phones were used. My Windows Phone's system clock was ~25 seconds behind the Android ones, leaving a 5 second grace time. There should be more leniency in timing, being off by less than a minute should not break TOTP auth.

**Comment by Crocmagnon** [comment]
> being off by less than a minute should not break TOTP auth

Well, it's not up to BW to handle this. The TOTP codes are generated according to the protocol and the basis of this protocol is that the code *changes over time*. So time is important. And it wouldn't be very user friendly to present one value in the past and one in the future just in case your device might not be on time. Better just sync it.

Some services though accept some values in the past, like 1 to 3 codes, so you can be off by a minute and you can still log in. But it's up to the service to decide what gap it accepts.
