### ISSUE TITLE
Custom Fields Type after Import

### ISSUE THREAD

**Issue by mcp11** [bitwarden/web#309]
Steps to reproduce:
1. Create Entry with "Hidden" Custom Field (For example an additional Password). (Now the value of the custom field is only shown when clicking the eye-symbol)
2. Export the vault using the export function of the Web-Vault
3. Import the CSV-file into a new Account

Expected behaviour:
The Custom field of the Entry should be "hidden", meaning that the input value should be represented by stars and only be visible when clicking the eye-symbol (Same as the normal password-field of the entry)

Actual behaviour:
The custom field is shown in cleartext

**Comment by kspearrin** [comment]
Yes, unfortunately this is a detail that is not exported in the CSV file at this time. Hopefully in a future update we will introduce JSON exports/imports which can include additional data like this.

**Comment by sov-j** [comment]
I've verified this to work ok now with the JSON export format (bitwarden.com web version 2.15.1, FWIW), so I guess this can be closed now.
