### ISSUE TITLE
Only show folders that contain sites which match search

### ISSUE THREAD

**Issue by ysshah** [bitwarden/web#31]
When I search for a site and the matching site is in one of the last folders (I have ~20 folders), I have to scroll through a bunch of folders that all say "No sites in this folder." It would be nice if these folders were automatically hidden while I am searching.

**Comment by kspearrin** [comment]
Done for next release: https://github.com/bitwarden/web/commit/45d0f43e90cde4976d7c603afede4ea7ab1117cf
