### ISSUE TITLE
Rotate encryption key doesn't work

### ISSUE THREAD

**Issue by micbase** [bitwarden/web#311]
I was trying to change master password with rotate encryption key checked at https://vault.bitwarden.com/#/settings/account. But I don't see the API request calling /accounts/key, the encrypted data was not changed. 
Interestingly, I checked out this repo, running at my local actually works. Not sure what causes this.

**Comment by micbase** [comment]
I checked out v2.7.1, hosted on-prem, worked as expected. I didn't spend too much time debugging the prod version, but seems this is failing https://github.com/bitwarden/web/blob/master/src/app/settings/change-password.component.ts#L105 although I got HTTP 200 for that request. Very weird. I will wait for your next release/deploy to see if this issue persist.

**Comment by djsmith85** [comment]
Hi @micbase, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
