### ISSUE TITLE
No U2F on Mobile

### ISSUE THREAD

**Issue by ghost** [bitwarden/web#313]
I am unable to use my Fido key on mobile. There is a new feature part of Google authenticator exposing this API on mobile.

**Comment by danteissaias** [comment]
https://developers.google.com/identity/fido/android/native-apps

**Comment by danteissaias** [comment]
It's just the same I think: windoelw.u2f

**Comment by kspearrin** [comment]
I am talking about how to configure it with Google Authenticator and Chrome as you have suggested.

**Comment by djsmith85** [comment]
Closing this as WebAuthn was implemented on mobile. For more information about the topic please see here: https://bitwarden.com/help/article/setup-two-step-login-fido/
