### ISSUE TITLE
RoboForm Import - Missing Custom Fields

### ISSUE THREAD

**Issue by AndrewBucklin** [bitwarden/web#317]
Custom fields are not imported from RoboForm CSV.

Sample CSV:
https://pastebin.com/6trJUQwb

**Comment by kspearrin** [comment]
Can you help me understand the format here?

It looks like most are like this:

```
pr_city:txt:Dallas
```

Three pieces of data split by two colons.

I assume the first part (pr_city) is the key/name, the second part (txt) is the type of data, and the last part (Dallas) as the value.

However, it looks like there are other formats in your example, like:

```
explanation_delinquent:are:Late   rent reason
```

and

```
question_lawsuit:on:rck:*
```

**Comment by AndrewBucklin** [comment]
Yes, each of those are different input types. Here is the source code for each of those input types:

`<input type="text" name="pr_city" id="pr_city" class="gui-input" placeholder="Previous City">`

`<textarea class="gui-textarea" id="explanation_delinquent" name="explanation_delinquent" placeholder="Your explanation"></textarea>`

`<input type="radio" name="question_lawsuit"  value="on" class="smartfm-ctrl" data-show-id="ctr_explanation_lawsuit" >`

**Comment by kspearrin** [comment]
Any idea what a checkbox field looks like?

**Comment by kspearrin** [comment]
Also, any idea what the `rck:*` part means on the radio button field?

**Comment by AndrewBucklin** [comment]
Ahh, sorry, doesn't look like my example dump has an checkbox elements. Pasted below is another example, coming from [Exchange OWA](https://webmail05.mycloudmailbox.com/owa/), that includes checkbox elements.

https://pastebin.com/amE4hcbR

It looks like all **radio** elements AND **checkbox** elements use this format in the RoboForm CSV export:
`<NAME>:<VALUE>:rck:*`

**Comment by kspearrin** [comment]
Is this a radio with value 4?

```
trusted:4:rck:*
```

Is this the checkbox?

```
-no-name-:chk:0
```

Looks like it uses `chk` in the second position. Is value either 0 or 1?

Is this is correct it would seem that `rck:*` is only for radio buttons.

**Comment by AndrewBucklin** [comment]
No, it's a **checkbox** with value 4.
`<input id="chkPrvt" onclick="clkSec()" name="trusted" value="4" type="checkbox" class="chk" checked="" role="checkbox" aria-labelledby="privateLabel">`

No, it's also a checkbox, just with no **name** property.

I linked to the OWA login page in my last reply if you want to see for yourself. Tnx.

**Comment by kspearrin** [comment]
OK, should be all fixed in next web vault update.
