### ISSUE TITLE
Decrypting is slow in Firefox compared to Chrome

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/web#320]
My account is setup to use 100000 iterations for KDF as per minimum recommendations.
I found the vault decryption very slow in FF, so I decided to take my stopwatch and here are the results.

I measured the time between hitting enter in the web vault master password and the appearance of the first item :
- Firefox : 10.8s
- Chrome : 3.0s

Setup info :
- MacBook Pro 2017
- macOS Mojave 10.14.2
- Firefox Developer Edition 65.0b8
- Chrome Version 73.0.3642.0 (Official Build) dev (64-bit)
- Timing done on a separate device, no automation. Just eyes and react time.

**Comment by kspearrin** [comment]
How many items are in the vault?

**Comment by Crocmagnon** [comment]
How can I know ?

**Comment by kspearrin** [comment]
The mobile app and browser extension will give you some number counts and you can kind of guesstimate.

**Comment by Crocmagnon** [comment]
339 items total (307 logins)

**Comment by kspearrin** [comment]
Honestly I am not sure why. I just tested this on my old Cacbook pro (2011) with High Sierra. I have a vault with 400-500 items in it. Results were about the same on both Firefox and Chrome with ~2-3 seconds to load the vault after logging in.

**Comment by Crocmagnon** [comment]
I can not reproduce it in Firefox 64.0, but I can in Firefox Developer Edition (65.0b9)

**Comment by Crocmagnon** [comment]
I can not reproduce it in Firefox 64.0, but I can in Firefox Developer Edition (65.0b9). I did some testing in Safe Mode (no addons) with even worse results (~20s to load vault in FF dev edition with safe mode)

**Comment by kspearrin** [comment]
Is the delay network related or with decryption? Look at the network tab logs in the console.

**Comment by Crocmagnon** [comment]
Network does not seem to be involved. By looking at the network tab I only have calls to gravatar and icons.bitwarden.com. Only one call to vault.bitwarden.com to get an image.

**Comment by kspearrin** [comment]
You should see the call to log in, and another call to sync.

**Comment by Crocmagnon** [comment]
Results were filtered for images only...
Here's what I get now :

![image](https://user-images.githubusercontent.com/3630554/50970050-9960d280-14e0-11e9-9cbb-996f271d97c8.png)

**Comment by kspearrin** [comment]
Seems pretty normal there. I guess the slowdown is with decrypting the data.

**Comment by djsmith85** [comment]
Hi @Crocmagnon, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Comment by Crocmagnon** [comment]
Hello @djsmith85. I just tested and haven't been able to reproduce the original issue. I measured a total time (enter -> data available) of ~3.5s on Firefox 91.0b9 so it seems to be back to acceptable levels.
