### ISSUE TITLE
Yikes! "Purge Vault" on personal account (not organization) purged items in shared collections?

### ISSUE THREAD

**Issue by jikquantopian** [bitwarden/web#321]
One of our users just did a "Purge Vault" on their personal vault -- NOT on our organization -- and in addition to purging all the credentials from their personal vault, it ALSO purged all the credentials in any collection that they had access to in the organization.

SURELY this can't be the intended behavior? We just lost a lot of credentials because of this.

**Comment by kspearrin** [comment]
Just tested this on vault.bitwarden.com and am not able to reproduce. Are you?

**Comment by jikquantopian** [comment]
On further investigation I think this is probably a PEBKAC issue. Closing for now will reopen if I find evidence to the contrary.
