### ISSUE TITLE
Import Lastpass export doesn't convert nested folders

### ISSUE THREAD

**Issue by gene1wood** [bitwarden/web#322]
Lastpass exports delimit nested folders with the `\` character. Bitwarden import is looking for `/` characters to indicate a folder is nested below another folder. As a result if you export from Lastpass and import to Bitwarden all of the nested folders are instead unnested folders with `\` in them.

For example, these folders in Lastpass
```
Travel\Business
Travel\Personal
```

when exported from Lastpass and imported into Bitwarden are carried across unmodified. The Bitwarden web vault import process should detect Lastpass export format and convert `\` to `/`. This way they'd show up in Bitwarden as nested folders with names like
```
Travel/Business
Travel/Personal
```

# Steps to reproduce

1. In Lastpass create a nested folder called `foo\bar`
2. Save a credential in that nested folder
3. Export to CSV
4. Import the CSV into Bitwarden

# Expected results

A nested folder of `bar` under `foo` with a full name of `foo/bar`

# Actual results

A non nested folder called `foo\bar`

**Comment by kspearrin** [comment]
Can you provide a raw example of what a row from the LastPass export looks like when there are nested folders?

**Comment by gene1wood** [comment]
Sure, just did an export, here's one of the lines (with the username and password changed)
```
http://www.zoneedit.com/auth/,usernameredacted,passwordredacted,,Zoneedit,Personal\DNS and Hosting,0
```

**Comment by kspearrin** [comment]
https://github.com/bitwarden/jslib/commit/80c0da766e549d519f91c0b9ab6db925a93ab55a should fix it
