### ISSUE TITLE
When "New Collection" button is clicked, focus should start on collection name

### ISSUE THREAD

**Issue by jikquantopian** [bitwarden/web#324]
When I click the "New Collection" button in the web vault, the next thing I'm going to need to do is obviously to type the name of the new collection, so focus should start there without my having to tab or click into it.

**Comment by birksy89** [comment]
Is this the same as adding a new "Folder" - As I was about to raise an issue myself.

**Comment by jikamens** [comment]
Folders and Collections are not the same thing.

**Comment by sov-j** [comment]
I can confirm this behavior on both current Chrome and Firefox: when creating a new folder or collection the creation form does not have a cursor in it at all. It would be a better UX if it was set to the Name field in both cases.

**Comment by cscharf** [comment]
Agreed, would be a better UX. We'll look at this likely during Q4 unless someone wants to take a crack at beforehand, should be pretty easy to accomplish.

**Comment by paulussujono** [comment]
I'm not sure how to link with this issue, but I have raised a [PR](https://github.com/bitwarden/web/pull/667) that should close this.

**Comment by cscharf** [comment]
> I'm not sure how to link with this issue

@paulussujono , I have edited your PR description to include the `"closes #<issue number>"` text which in Github will auto-link the PR with the issue and when the PR is merged, will automatically close the related issue.
