### ISSUE TITLE
Web UI claims "User not valid." when attempting to confirm user

### ISSUE THREAD

**Issue by jikquantopian** [bitwarden/web#326]
I sent out a bunch of invitations to new users. While in the web UI sending out additional new invitations, I noticed that the account of users displayed on the "Accepted" tab header was non-zero, so I clicked on it and attempted to approve a recently accepted user. I got this:

![image](https://user-images.githubusercontent.com/41483888/51216070-1c26ca80-18f1-11e9-9d7f-8123b0aa1bdf.png)

This happened more than once with different users.

**Comment by kspearrin** [comment]
The only time this error would occur is if the user's status is not in the "accepted" state once it hits the server (i.e. likely already "confirmed").

Is there perhaps someone else confirming users at the same time, or maybe another browser window open where you may have already accepted this user prior? According to the server, the user is already accepted and the UI you are looking at hadn't refresh yet to see this new state.

**Comment by jikquantopian** [comment]
Update on this... It doesn't appear to be related to having just recently accepted an invite, as I initially thought. Rather, it appears to be related to trying to confirm to users in a row. While displaying the "Accepted" tab of the Manage People page which I had just loaded, I attempted to confirm two users who had accepted their invitations hours before. The first one worked, the second one got the "User not valid." error.

**Comment by jikquantopian** [comment]
>The only time this error would occur is if the user's status is not in the "accepted" state once it hits the server (i.e. likely already "confirmed").
>
>Is there perhaps someone else confirming users at the same time, or maybe another browser window open where you may have already accepted this user prior? According to the server, the user is already accepted and the UI you are looking at hadn't refresh yet to see this new state.

No, that is not what happened.

I think what is happening is that when I confirm two users in a row, the second time I confirm a user the web code is trying to re-confirm the user I previously confirmed.

**Comment by brianredbeard** [comment]
Possibly related to this, when a user creates an account and then logs in (but is not confirmed yet) they get the error message 

> Unable to accept invitation.  Ask an organization admin to send a new invitation.

This was _during_ the confirmation process.  Furthermore, the error message really distracted things.  Potentially having the following would be useful:

1. A message stating that the account was in an unconfirmed state
2. A link to the settings page so that the user can more easily supply their fingerprint phrase.

![problem](https://user-images.githubusercontent.com/57542/52749060-01ea1600-2f9d-11e9-8e20-b436cbeda30b.jpeg)
