### ISSUE TITLE
U2F in Chrome may return self-signed certificates instead of attestation certificate from device

### ISSUE THREAD

**Issue by dani-garcia** [bitwarden/web#336]
According to https://www.chromium.org/security-keys, from Chrome 66 onwards, the U2F API was changed to be more in-sync with the webauthn API, which won't return the device's attestation information by default, but instead return a self-signed certificate. This is to avoid privacy problems and the reasoning is explained in the link above.

This is a problem with our server implementation because our U2F library verifies that the certificate is trusted, which fails with self-signed certs. I figured you might want to be aware of it, as it took us some time to find the cause.

This can be changed by adding `attestation: 'direct'` to the `u2f.register` call [here](https://github.com/bitwarden/web/blob/eb99fe58dd1dfb7f24dc5ee45f4af13c52053cac/src/app/settings/two-factor-u2f.component.ts#L128) to:
```ts
(window as any).u2f.register(u2fChallenge.appId, [{
    version: u2fChallenge.version,
    challenge: u2fChallenge.challenge,
    attestation: 'direct',
}],
```

**Comment by kspearrin** [comment]
Thanks for the info. I’ll look into this a bit more.

While on this subject, I am looking to try to move away from u2f-api (window.u2f) to the newer webauthn APIs. This would also allow us to support u2f logins in the desktop app. I haven’t been able to figure out how to use the webauthn apis for U2F, however. I have an open question on StackOverflow here: https://stackoverflow.com/questions/53640407/how-do-you-implement-fido-u2f-using-webauthn-apis

**Comment by dani-garcia** [comment]
I thought the webauthn APIs were just the standard interface to talk to FIDO devices (both U2F and FIDO2 devices)? So it should work simply using the webauthn API just like that, it's meant to be backwards compatible.

Looking at the spec (https://www.w3.org/TR/webauthn), it seems all the U2F specific things are meant to be handled by whatever library the server is using, like this one for .net, which mentions supporting fido-u2f and also has a demo: https://github.com/abergs/fido2-net-lib.

Here is also an article that talks about webauthn, that also has a couple of examples: https://medium.com/@herrjemand/introduction-to-webauthn-api-5fd1fb46c285. The last examples go into passwordless, but the first two seem pretty similar to how the u2f API is being used now.

Looking it quickly, instead of `register` you would use `navigator.credentials.create`, and instead of `login` you'd use `navigator.credentials.get`.

**Comment by kspearrin** [comment]
I know it is possible. I am just looking for some example that explains what functions and params from the old u2f apis map to the web webauthn apis. Every example I find seems to always be based on passwordless signin, not U2F.

> instead of login you'd use navigator.credentials.get

Did you mean `u2f.sign` => `navigator.credentials.get`?

**Comment by dani-garcia** [comment]
Yeah, I meant sign, sorry.

The process is about the same in both, the way I see it:
- User clicks 'Add two factor device', request sent with login info
- The server returns a challenge and some other info
   - In the old u2f, this is just the version
   - In webauthn, this is an object with more info, like relying party and user details (id and display name)
- The client calls the local API with the info received from the server.
  - u2f: `u2f.register`
  - webauthn: `navigator.credentials.create`
- This gives a response that is sent to the server, where it's verified and added to the user

Then later, when logging in:
- The user logs in, which returns a challenge.
  - In old u2f, this is passed to `u2f.sign`
  - In webauthn, it's passed to `navigator.credentials.get`
- The response from this is sent to the server to validate

The example from the blog post is published here, and I think it shows pretty well how to do the client-side part: https://github.com/herrjemand/FIDO2WebAuthnSeries/blob/master/WebAuthnIntro/BasicExample.html

**Comment by kspearrin** [comment]
> The server returns a challenge and some other info
> In the old u2f, this is just the version

There is also an `appId`, which I don't see a place for. Is the `appId` the relying party? https://www.w3.org/TR/webauthn/#sctn-appid-extension

> The user logs in, which returns a challenge. 

There is a challenge, appId, and an array of keys (handle and version).

**Comment by dani-garcia** [comment]
> Is the appId the relying party?

My understanding is that yes, the RP is the alternative to the old appId. To keep backwards compatibility with the already registered U2F keys, there is an extensions object that has an appid field that can be used when using the `navigator.credentials.get` (that way, newly registered devices use the new Relying Party while the old devices use the old AppID.
Some more info here: https://www.imperialviolet.org/2018/03/27/webauthn.html#supporting-keys-created-with-the-u2f-api

> There is a challenge, appId, and an array of keys (handle and version).

That same page also contains an example of the exact parameters received: https://www.imperialviolet.org/2018/03/27/webauthn.html#getting-assertions. There is also an example in the blog post I mentioned above: https://medium.com/@herrjemand/introduction-to-webauthn-api-5fd1fb46c285#cff2

So, copying one of the examples above, the resulting code would look something like:
```js
var publicKey = {
    challenge: challenge,

    allowCredentials: [
        { type: "public-key", id: credentialId }
    ],
    extensions: {
        appid: "https://vault.bitwarden.com/app-id.json",
    }
}

navigator.credentials.get({ 'publicKey': publicKey })
  .then((getAssertionResponse) => { ... })
```

Note that `credentialId` would be calculated by the server when the keys are being registered and would be returned with the challenge.

**Comment by herrjemand** [comment]
I would strongly suggest dumping U2F API and just moving to WebAuthn. It is certainly a bit of work, but would pay off by:

a) Not dealing with NON-Standardised behaviour
b) Availability on all browsers

**Comment by herrjemand** [comment]
Regarding RPID and AppID:

AppID is still supported through the extensions in FIDO2/WebAuthn.
RP ID functioning through the "Parent Law". Which means that root domain can claim for it submodomains:

example.com ORIGIN can request with RPID authentication.example.com.
authentication.example.com ORIGIN can NOT request for RPID example.com

**Comment by Nigatsu** [comment]
Hi any estimation when FIDO2 will be supported?

**Comment by beerisgood** [comment]
Any updates?

**Comment by Hinton** [comment]
Since we no longer use u2f, and migrated everything over to WebAuthn, I'm going to close this issue. Feel free to open a new issue if you are still encountering this issue.
