### ISSUE TITLE
Numbers seems to be replaced by _____

### ISSUE THREAD

**Issue by Jacalz** [bitwarden/web#337]
When logging in to Bitwarden web vault on my IPad Air 2 using iOS 12 seems to not show almost any numbers on the page, they are just replaced with  ____.
![a888537d-803e-44ba-a3e5-037ee228d952](https://user-images.githubusercontent.com/25466657/51791429-2a070600-21a3-11e9-9626-72a1ae38e4bc.jpeg)

**Comment by Jacalz** [comment]
This is seen pretty much everywhere on the page, even on the log in screen where you couldn’t see the version number of the web client 😬

**Comment by kspearrin** [comment]
Weird. Does it show like this if you change to another language under Settings > Options, such as english?

**Comment by Jacalz** [comment]
Same issue in both Safari and Brave browser

**Comment by kspearrin** [comment]
Ok, got it. I can reproduce on my iPhone as well.

**Comment by kspearrin** [comment]
Should be fixed now. That was a weird one...

Thanks!

**Comment by Jacalz** [comment]
You are welcome! Thanks for fixing it so quickly 👍
