### ISSUE TITLE
Incorrect year on the login page

### ISSUE THREAD

**Issue by Rakleed** [bitwarden/web#339]
Incorrectly specified year on the [login page](https://vault.bitwarden.com). It should already be replaced by 2019.
<details><summary>Screenshot:</summary>

![screenshot-vault bitwarden com-2019 01 29-19-08-57](https://user-images.githubusercontent.com/19418601/51922152-882d2680-23f9-11e9-9ddc-bcb2e9c96803.png)

</details>

**Comment by kspearrin** [comment]
fixed in next update. thanks.
