### ISSUE TITLE
An unhandled server error on attempt to delete a lot of sites

### ISSUE THREAD

**Issue by spontaliku-softaria** [bitwarden/web#34]
Due to lack of delete for folders, I've tried to do it "myself": called `click` on every button in a folder and confirmed all delete dialoges. This lead to some success deletes but mostly (> 100) failed with error 500.
Response: 
```json
{"Message":"An unhandled server error has occured.","ValidationErrors":null,"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Object":"error"}
```
Screenshot:
![bitwarden_many_deletes](https://cloud.githubusercontent.com/assets/6647438/21657306/327f8b7c-d2f4-11e6-80c3-317c8b84873f.png)

**Comment by kspearrin** [comment]
You are probably getting throttled by the API since you are probably called it very quickly. I will look into it.

**Comment by kspearrin** [comment]
Resolved with bulk delete in next release.
