### ISSUE TITLE
Import from KeepassX 0.4.3

### ISSUE THREAD

**Issue by ZugBahnHof** [bitwarden/web#340]
I've got a very old pc with keepassx version 0.4.3. Ist there any way to import the data (either .xml or plain text)

**Comment by kspearrin** [comment]
No, I don't think so. Can you not update KeePassX to the latest?

**Comment by djsmith85** [comment]
Hi @ZugBahnHof , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

For further information about which file-formats we support out of the box please check out: https://bitwarden.com/help/article/import-faqs/#q-what-file-formats-does-bitwarden-support-for-import
