### ISSUE TITLE
Vault Web not loading on iPad 3rd Generation

### ISSUE THREAD

**Issue by philippeboyd** [bitwarden/web#341]
I have an iPad 3rd Generation (iOS 9.3.5) and the Web version of the Vault doesn't load on either Safari, Google Chrome or even Firefox. The loader (to get to the login form) just keeps spinning...

![img_1509](https://user-images.githubusercontent.com/3239656/52166607-5a87fc00-26dd-11e9-83b9-e4af2a78cf6d.PNG)

**Comment by kspearrin** [comment]
Unfortunately, Safari 10 or greater is required to use the web vault.
