### ISSUE TITLE
Popped out window in browser does not see website url

### ISSUE THREAD

**Issue by Fealthas** [bitwarden/web#345]
Use the pop out into a new window button. Generates a new window. The plugin neither:
1: Sees the correct website to suggest logins for.
2:Grabs it to save into a new login.

![image](https://user-images.githubusercontent.com/25716039/52515581-7adb1d80-2beb-11e9-975d-169ca7ef23ab.png)

**Comment by kspearrin** [comment]
This is expected. Since the popup window is now disconnected from a browser window, it no longer has context.

**Comment by Fealthas** [comment]
It would be much nicer for users if it acted smart, rather than "doing what is expected".

Maybe a feature request rather than bug?

**Comment by kspearrin** [comment]
I am not sure this could work. What happens when multiple windows are open. What URL do we use?

**Comment by Fealthas** [comment]
Last focused main window maybe. Or the window it was popped out from. 

Anything would be an improvement.

**Comment by Fealthas** [comment]
Oh and I realized this should be in /browser not /web. Sorry.
