### ISSUE TITLE
Import from GNOME passwords - script no longer works

### ISSUE THREAD

**Issue by spookylukey** [bitwarden/web#347]
There are some issues with the import from GNOME on the web interface
 https://vault.bitwarden.com/#/tools/import

I was surprised and pleased to find you were linking to a script I myself wrote a good while ago:

>  GNOME Passwords and Keys/Seahorse (json) instructions
Make sure you have python-keyring and python-gnomekeyring installed. Save the [GNOME Keyring Import/Export python script](https://bitbucket.org/spookylukey/gnome-keyring-import-export/raw/db0c7ce80e60c3aaa223b6ffd800c8cd6275d2f0/gnome_keyring_import_export.py) to your desktop as pw_helper.py. Open terminal and run chmod +rx Desktop/pw_helper.py and then python Desktop/pw_helper.py export Desktop/my_passwords.json. Then upload the resulting my_passwords.json file here to Bitwarden.

However, the script has bit-rotted - it doesn't work on modern GNOME, and the library it depends on has been dropped.

So, I wrote a new one for you :-) (well, me really).
See: https://bitbucket.org/spookylukey/gnome-keyring-import-export

This outputs JSON in the same format. It kind of works when I import into the web vault. However, most of my secrets are not imported. Specifically, it seems that secrets that were originally created with Chrome are imported, but others manually created are not. These tend to look like this in the JSON:

    {
      "display_name": "my secret name",
      "secret": "my secret",
      "mtime": 1543734264,
      "ctime": 1543734264,
      "attributes": {
        "xdg:schema": "org.gnome.keyring.Note"
      }
    }

The schema field can also be `"org.freedesktop.Secret.Generic"`

It would be cool if these could be supported too!

Thanks so much for the awesome software.

**Comment by kspearrin** [comment]
Thanks. I have updated the instructions link. The current import script will only import if the `display_name` starts with http, meaning it is a website. Do we want to import others as well. I am not familiar with what may be coming out of the keying here.

**Comment by spookylukey** [comment]
The example I gave above was a manually created 'note' in the keyring. You could map this and anything else that isn't recognised, to a 'Secure note' in Bitwarden.

**Comment by Dashon1** [comment]
Any progress on this. I am having trouble importing stored notes as well.
