### ISSUE TITLE
Lastpass importer fails on basic import

### ISSUE THREAD

**Issue by mirraj2** [bitwarden/web#348]
Here's an example import that doesn't work:

url,username,password,extra,name,grouping,fav
http://www.website.com/,abc@gmail.com,password123,,somewebsitename,,0

**Comment by kspearrin** [comment]
Seems to work for me:

![image](https://user-images.githubusercontent.com/1190944/52796090-226bac00-3041-11e9-95cb-bba3f86133f3.png)

**Comment by mirraj2** [comment]
It was failing for me with an invalid file format error.  And then mysteriously like 10 minutes later it started working.  Maybe there is some kind of obscure bug where the import doesn't work for new accounts, and the error message is inaccurate.

I almost ended up giving up on the software due to this bug, and I wonder if other new users coming from lastpass have had the same issue.

**Comment by kspearrin** [comment]
Maybe your file was not saved in the correct CSV format. Try copy/pasting the data into Bitwarden's importer rather than saving to a file. If you can provide any further details as to how to reproduce the error, I'll be happy to reopen this issue.

**Comment by mirraj2** [comment]
I did copy paste - I swear I checked and double-checked to make sure I did everything properly.  Oh well

**Comment by mirraj2** [comment]
@kspearrin which file in the repo is responsible for handling the data import.  I can take a look around the code and see if I find the problem.

**Comment by ShirokaiLon** [comment]
It's this one: https://github.com/bitwarden/jslib/blob/master/src/importers/lastpassCsvImporter.ts

**Comment by mjvanderveen** [comment]
It only worked for me when I changed my language to en-GB instead of standard
