### ISSUE TITLE
9GAG icon

### ISSUE THREAD

**Issue by Neurotoxin001** [bitwarden/web#350]
Hello, icon for 9gag.com is transparent so I can't even see it.
![image](https://user-images.githubusercontent.com/39812401/52900662-89d45800-3209-11e9-8411-cee12c75d6f3.png)
https://icons.bitwarden.net/9gag.com/icon.png

Maybe better change it to this:
![image](https://user-images.githubusercontent.com/39812401/52900655-77f2b500-3209-11e9-8db2-e4927c32e403.png)

**Comment by Neurotoxin001** [comment]
Similar issue with www.pochta.ru:
https://icons.bitwarden.net/www.pochta.ru/icon.png

I suggest use this:
![image](https://user-images.githubusercontent.com/39812401/52900777-6a3e2f00-320b-11e9-8dc1-5ce62f2c3b1d.png)

**Comment by kspearrin** [comment]
Unfortunately we don't hand pick these icons. They are pulled from the website's favicon.

**Comment by kspearrin** [comment]
ex: `https://assets-9gag-fun.9cache.com/s/fab0aa49/5a8c274f8284eb30af00be809bd61dd9b8c4e1f3/static/dist/web6/img/sprite-logo.png`

**Comment by kspearrin** [comment]
https://github.com/bitwarden/server/commit/594c9e9e3e3a856dd31c38d6498b228f5979b1e8 should fix it in next version
