### ISSUE TITLE
Trying to load an undefined file

### ISSUE THREAD

**Issue by setyb** [bitwarden/web#351]
When logging into the web vault, a packet log review indicates that the browser is requesting a connection to:

`https://vault.bitwarden.com/undefined`

The vault loads fine, and everything I tested seems to work.  I'm guessing, however, there may be some sort of bug that is causing bitwarden to try to load that URL.

**Comment by kspearrin** [comment]
not able to reproduce on chrome and firefox, w10.

**Comment by setyb** [comment]
I'll do some additional testing and post again.

**Comment by setyb** [comment]
OK Kyle, I checked my notes and invested some time into conducting additional testing.

I don't think there's an issue, but given the nature of bitwarden, it's probably best to dot the i's and cross the t's.

Here's what I did.  I ditched the low level packet inspector, just for the moment.  I found a couple of bugs in it (not bitwarden) while performing additional testing, so I don't feel it's a reliable source for data for this issue.

Instead, I used two high-level loggers that *should* give accurate results:

The first is the developer tools built into Mozilla's Firefox, which are known to be very reliable and powerful.  I ran extensive tests and scoured the logs.  I tried multiple different cases.  I didn't see anything abnormal.

The second, just out of curiosity, is the logger built into uBo (uBlock Origin).  The uBo logger shows something unusual, but given that devtools didn't find a problem with bitwarden, I'm guessing it's an issue with uBlock Origin.  I'll let you decide.

To be on the safe side, here are steps to reproduce.  I get 100% reproducibility.
  1. Test box: w7, Firefox v65.0.1 64-bit, bitwarden v1.38.0, uBo v1.18.4.
  2. Turn off all third-party cookies in FF (that's how test box was configured).
  3. Open the bitwarden web vault.
  4. Open the uBo logger.
  5. Go back to the bitwarden web vault tab.
  6. Log in to the bitwarden web vault; don't select the option to remember the email address.
  7. Wait for the bitwarden web vault to load.
  8. Switch to the uBo logger tab.
  9. Find the entry `https://vault.bitwarden.com/undefined` in the log.

What are your thoughts?

**Comment by kspearrin** [comment]
I am not sure. Since I am not seeing anything in the dev tools in either browser, I assume this is a problem with uBO. Going to close.

**Comment by setyb** [comment]
Filed issue ticket with uBo: https://github.com/uBlockOrigin/uBlock-issues/issues/432

**Comment by setyb** [comment]
@kspearrin If you're interested, there has been activity at https://github.com/uBlockOrigin/uBlock-issues/issues/432 where this issue is further discussed.  The last comment by the uBO primary developer reads "It could very well be a bitwarden site issue".  Not sure if we will ever know (unless someone looks into it).

**Comment by kspearrin** [comment]
@setyb  I am not really sure how to debug this since nothing is shown in the browser dev tools.

**Comment by jjlin** [comment]
@kspearrin I can reproduce this with Firefox 73 on Windows 10, no ad blockers. It doesn't happen in Chrome. You just have to go to `Settings -> My Account` or `Settings -> Organizations` and it shows up consistently in the dev tools network log.

**Comment by setyb** [comment]
@kspearrin Perhaps reopen issue?

**Comment by jjlin** [comment]
If it helps, here are dev tools screenshots.

Firefox 74 headers:
![headers](https://user-images.githubusercontent.com/203380/78466899-c12af000-76bb-11ea-8ac3-aa8f5ffc730c.png)

Firefox 74 stack:
![stack](https://user-images.githubusercontent.com/203380/78466901-c720d100-76bb-11ea-9cd7-2ed2650a4271.png)

Chrome 80 stack:
![stack-chrome](https://user-images.githubusercontent.com/203380/78466904-cc7e1b80-76bb-11ea-9f0c-f2b8d24ef578.png)
