### ISSUE TITLE
Please update github releases

### ISSUE THREAD

**Issue by marviins87** [bitwarden/web#358]
Kyle, why isn't the web code updated for almost 2 months on github? Currently we have no clue what code v2.9 is running online.

**Comment by marviins87** [comment]
?

**Comment by mountainash** [comment]
The [latest release](https://github.com/bitwarden/web/releases) was [Version 2.16.2](https://github.com/bitwarden/web/releases/tag/v2.16.2)  - 4 days go? Old issue? Close @marviins87 ?

**Comment by eliykat** [comment]
I'm not sure I understand what the original issue was here, but all code on Github reflects the current releases, so I'm closing this as resolved.
