### ISSUE TITLE
Change to React?

### ISSUE THREAD

**Issue by jamby** [bitwarden/web#36]
From a user perspective, the website is pretty sluggish. I've started using it any when I want to add a new login, new folder, even move the pane away, it moves REALLY slowly.

I noticed it is because the website is using Angular over faster libraries (such as React).

I'm looking at the code and may try to move things over to React if I get a blessing on this. Would love to make a much snappier website using new technology.

**Comment by kspearrin** [comment]
Can you please give reproducible examples where it is slow? I have not experienced this or received any reports from users about this either. The only time I have noticed a noticeable performance issue with the web vault is when you have a vault with thousands of logins in it and the folder/login repeaters have a hard time displaying that much data in screen at once.

**Comment by jamby** [comment]
So I just started with Bitwarden, but was just judging by a user experience view, that things run slow. I believe the main culprit is the use of Angular.

![bitwardensidebarslow](https://cloud.githubusercontent.com/assets/250728/22125923/a5662d92-de63-11e6-8f0f-1b612a96b131.gif)

The gif above is just a snippet of what I saw. This is the sidebar. Any time I click something that slides up or down with options, it is jagged with movement.

Similar things with clicking the `New Login` or `New Folder` options under `My Vault`: The popups show up and go away really jaggedly.

From what you've said with the thousands of logins, that seems like something in line with what I've seen with Angular and lots of data being represented. I had to fix a feature at my company with a similar problem where we used Angular and made it over into React, and now it runs really smooth.

Maybe this is just me being picky with user experience and that I've seen how much good React can do. I don't want it to seem like I want to change everything, but I've had good interactions with React (and it's the way the JavaScript community is going, Angular looks like it's going down - but Angular 2 seems more promising than Angular 1). But I do want to try and remake this in React and see if things like this can be fixed. It would be a pretty big rewrite - and in the end if you don't want it, that's fine.

**Comment by kspearrin** [comment]
How many logins are in your vault when recording the above gif?

**Comment by jamby** [comment]
25 logins currently in my vault.

**Comment by kspearrin** [comment]
That's odd. I have only see that type of behavior with thousands of logins in the vault. I have over 500 in mine and it's nice and snappy on every system I have used. What type of device are you using? What OS/browser?

**Comment by jamby** [comment]
Brand new Touch Bar MacBook Pro. Using chrome. Latest version I believe, unable to check at the moment.

**Comment by kspearrin** [comment]
I do see a small blip of lagginess on my 2012 Macbook Pro (Chrome), but nothing like what you posted. Regardless, I'm fairly confident that I know a few tweaks that I have been meaning to do that may alleviate the lagginess you are seeing.

Thanks for the detailed report.

**Comment by jamby** [comment]
If it's okay, I would like to build this in React and maybe send a PR and let you guys decide (who knows how long it will take). Whether or not you say yes or no, it is great experience, and I already love building stuff in React.

**Comment by kspearrin** [comment]
My all means if you want to take an undertaking on like that feel free, however, I don't really have any experience with React. It would be a good learning opportunity though.

**Comment by kspearrin** [comment]
Also, I would be more open to a rewrite on Angular2 rather than React since I prefer more opinionated frameworks.

**Comment by kspearrin** [comment]
Perf improvements coming in next web vault release.
