### ISSUE TITLE
Cannot create another collection

### ISSUE THREAD

**Issue by michieriffic** [bitwarden/web#361]
Testing out bitwarden today. I created a first collection in my organization which was successful. Then I created a second collection with a different name and i'm having this error. 

Is this a bug? Or do I need to move up to premium in order to create more than 2 collections?

![screen shot 2019-03-07 at 5 50 44 pm](https://user-images.githubusercontent.com/12575688/53947922-b6d9a380-4101-11e9-9324-426cf7ab7b0f.png)

**Comment by kspearrin** [comment]
There was an issue with the error message display. Try again and you should get a actionable error message.

**Comment by michieriffic** [comment]
Thanks @kspearrin saw the new error. If I moved up to a paid account, I wouldn't be limited to just 2 collections? Thanks :) 

![screen shot 2019-03-07 at 11 15 04 pm](https://user-images.githubusercontent.com/12575688/53966950-32057e80-412f-11e9-87d2-b45f7906195f.png)
