### ISSUE TITLE
[error: cannot decrypt]: shared entries on Firefox ESR Linux

### ISSUE THREAD

**Issue by lowtower** [bitwarden/web#365]
I have created a collection and shared some items to the collection.
Since then, the shared items are not being decrypted, even the name of the collection is not visible.
All shared entries are "[error: cannot decrypt]" now.
That is only in Firefox (v60.1.0esr) under Linux (Red Hat 6, Kernel 2.6.32).
In Firefox (60.3.0) and IE11 under Windows 10 all is fine.

**Comment by kspearrin** [comment]
I have moved the issue here to the web vault repo. I will have to test this. I don't have ESR installed currently.

**Comment by kspearrin** [comment]
I tried this tonight on Ubuntu 18 with Firefox ESR and was not able to reproduce the problem. Unfortunately I don't have a redhat VM available at this time,

**Comment by sov-j** [comment]
I just checked CentOS 6, which is a free equivalent to RHEL6. By now it has Firefox ESR 68.11, so I guess RHEL6 does as well. And in 68.11 everything works fine, items shared with collections decrypt properly.

**Comment by lowtower** [comment]
Not relevant anymore

**Comment by EigenTheory** [comment]
> Try logging out and back in?

This worked on 2 MacBooks in Chrome for me! Restarts didn't work or reboots. I had to log in, get the message, about decrypt, then actually log out and log back in.
