### ISSUE TITLE
Override for Inactive 2FA Report

### ISSUE THREAD

**Issue by LouisMT** [bitwarden/web#366]
I want to use the Bitwarden reports periodically to improve the security of my accounts. So I run the reports, fix any issues until the list is empty and do this again a few weeks later.

The Inactive 2FA Report seems to be based on the "Authenticator Key (TOTP)" field of vault entries. However, not all sites listed in the report support TOTP. Some only support SMS authentication, so they stay in the list while I have 2 factor enabled already (for example eBay and PayPal).

# Proposal 1
Add an option to vault entries to mark them as 2FA protected without TOTP.

![Bitwarden_Proposal_1](https://user-images.githubusercontent.com/1782761/54681026-a7982400-4b0b-11e9-9e1a-c1f67d51a688.png)

# Proposal 2
Add an override button to the report. These entries will then appear in a separate list at the bottom of the report so the override can be removed by the user.

![Bitwarden_Proposal_2](https://user-images.githubusercontent.com/1782761/54681027-a7982400-4b0b-11e9-93c3-bcb10a4ad6ce.png)

**Comment by kspearrin** [comment]
You can simply place a `-` character in the TOTP field. Since this is not a valid base32 character, it won't generate codes. And since the field has a value, it won't be included in the reports.

**Comment by LouisMT** [comment]
Ah, that's great! Thanks!
