### ISSUE TITLE
Searching the vault does not take care for notes

### ISSUE THREAD

**Issue by magicsunday** [bitwarden/web#372]
While searching the vault records for a specific site and its credentials, the search filter does not take care about notes I added to an entry. So you always need to know the name you entered for an entry.

Applies for all kind of clients.

**Comment by kspearrin** [comment]
Search includes notes. Can you provide an example?

**Comment by magicsunday** [comment]
You are right, I tested it again. But I have to enter an asterisk as wildcard to perform a partly search. Maybe the asterisk could be avoided as extra Input?

**Comment by kspearrin** [comment]
Wildcard searches are expensive to perform, therefore, they are only automatically applied to certain fields. See https://help.bitwarden.com/article/searching-vault/

**Comment by magicsunday** [comment]
Maybe the notes Field should be added to the List? As search is done on Client side the performance impact is not as much as feared unless you have thousands of passwords. According to the Lunr docs only leading wildcards should be avoided if possible.

**Comment by kspearrin** [comment]
@magicsunday There are many people with thousands of passwords, so we have to create a solution that works for everyone.
