### ISSUE TITLE
Activity log broken for Organization's items that don't belong to any Collection

### ISSUE THREAD

**Issue by pachulo** [bitwarden/web#375]
If I take an Organization's item out from all the collections it belongs to, viewing the activity log for it does not work anymore.
In the browser devtools I've seen that the server returns a 404.

When the item is back in any collection, I can see the activity log again.

**Comment by kspearrin** [comment]
Should be fixed next version with https://github.com/bitwarden/server/commit/fa463843bb4dfc81a1d1c2d61878f80957bd52d4
