### ISSUE TITLE
Can't change 2FA method in newest chrome beta with U2F enabled

### ISSUE THREAD

**Issue by djohannes** [bitwarden/web#379]
With the newest chrome beta the browser supports native WebAuthn on windows. 
This means you get the windows own popup to authenticate yourself with a U2F key, but there is a problem:
I enabled more 2FA methods, also U2F, but when I now go to the web vault and try to change the 2FA method it doesn't work, because I can't close that popup window. 
When I click on cancel it's instantly coming back, I need to authenticate myself with the U2F key (which is just at home, I only have my Yubikey OTP keys with me on the go) or I need to force close the chrome browser.

Now you might think this is a chrome issue, but other websites don't generate this loop.. they just give you an error page when you closed that windows own U2F popup.

Here a screenshot of this popup:
![image](https://user-images.githubusercontent.com/44353290/56089747-f5e4dc80-5e97-11e9-8d9b-e98583511a05.png)

.. it's in German but it should help understanding my problem. When I click on "Abbrechen" (Cancel in English) it just instantly comes back so you don't get the chance to change the 2FA method. For other websites it just gives you an error page.

**Comment by djohannes** [comment]
![image](https://user-images.githubusercontent.com/44353290/56089720-866eed00-5e97-11e9-94cc-a0373733af8e.png)
this is the popup I'm talking about, it's in German but it should help understanding my problem. when you click on "Abbrechen" (Cancel in English) it just instantly comes back so you can't click on "change 2FA method".

**Comment by kspearrin** [comment]
This is probably because we re-initiate U2F on a loop when it times out. Maybe we need to just add a "try again" button instead.

**Comment by jurjenoskam** [comment]
This also occurs on latest released Firefox and Windows 10 1903. I get the "Windows Security" popup screen, and when I cancel, it almost immediately pops back up. There is a *very* short interval where I can try to select another MFA method.

**Comment by damianh** [comment]
I've had to disable FIDO U2F Security Key two step login provider because of this. Seperately, looking forward to WebAuthN support ;)

**Comment by zcz3** [comment]
I get this on Firefox on Windows - I have both U2F and Authenticator app as two factor methods.

You have about 1/2 a second to click on the "Use another two-step login methd" link after closing the "Windows security" popup, before it reappears, and it continues to pop up even when showing a list of alternative two step methods.

If you are are lucky, and quick with the mouse, you can then select the Authenticator option, and it stops.

This bug effectively means that multiple two-step logins isn't supported on Windows, if one of your options is U2F.

**Comment by Hinton** [comment]
I believe this was resolved with the move to WebAuthn. The behavior in the browsers I've tested will immediately cancel the action if the user clicks cancel on the prompt. Which allows for selecting a different 2fa method. Feel free to open a new issue if this still occurs using WebAuthn.
