### ISSUE TITLE
change to main e-mail isn't applied to 2-step verification

### ISSUE THREAD

**Issue by usernameandpassword1** [bitwarden/web#382]
This issue has only been tested using the Bitwarden website using 2-step verification. When the main e-mail is changed and verified the new e-mail does not change globally. I can log in with the new e-mail but the old e-mail will receive e-mail for passcodes. 

An example would be as such, I change my main e-mail to a new e-mail. I logout from the website and when I log back in using 2-step verification with the new e-mail, my passcode is sent to my old e-mail.

**Comment by kspearrin** [comment]
This is expected since they are configured independently. This allows you to configure an email for 2-step login separate from your email used to log in.

Maybe we can add a checkbox to the email change form or something that says "Change my two-step login email too".
