### ISSUE TITLE
when web vault times out, doesn't request U2F key with master password

### ISSUE THREAD

**Issue by hoidsflute** [bitwarden/web#385]
If U2F key is required for log-in, then why after the web vault times out, and I log back in with master password, does it not ask for my U2F key?  I shouldn't have to manually log out to make sure it asks for the key upon next log-in.

Firefox browser

**Comment by kspearrin** [comment]
Unlocking your vault is not the same as logging in. Unlocks are a client-side action, which doesn't contact the server (required for 2FA). Logging in sends a request to the server to authenticate.
