### ISSUE TITLE
Deauthorise sessions - no warning when logging back in on previously "known" device

### ISSUE THREAD

**Issue by Laurisade** [bitwarden/web#386]
Hello!

I'm not sure it is necessarily a web bug, but the situation is as follows:
1. Deauthorise all sessions.
2. Log back into your account on device that previously gave you "New Device Logged In From..." e-mail alert.
3. You get no e-mail alert after logging in in previously known machine. What I mean by that: I already got login notification email once (a while ago) about this particular device(s), but not 2nd time.

I think deauthorising should also void any known logins. Theoretically if my account is hacked, and I change master password + deauthorise all login sessions, the potential hacker could still sneak in without me knowing about it (be it via keylogger or what not).

**Comment by kspearrin** [comment]
The email is about a new device logging in, not that you are logging in again after being logged out before. If it is the same device, you will only get that email once (or until the client identifier for that device changes (clearing local storage in the browser, for example).
