### ISSUE TITLE
Unsharing a previously Shared-Password result in assigning to default Org vs unassigned

### ISSUE THREAD

**Issue by Trouffman** [bitwarden/web#388]
A password created in a personal vault is shared to a collection in an Organization.

Removing the shared collection result in the entry being assigned to the default organisation collection.
Should it be "unassigned" ?

Behaviour done few minutes ago, from Chrome on the Web Vault at bitwarden.com

**Comment by kspearrin** [comment]
If you remove all collection assignments from an item, it should show up under the "Unassigned" filter.

**Comment by Trouffman** [comment]
This is seems to be solved as tested on version 2.27.0.

Can be closed and marked as resolved.
