### ISSUE TITLE
Nested collections not displaying correctly if “parent” collections does not exist

### ISSUE THREAD

**Issue by pachulo** [bitwarden/web#389]
We created some nested collections following the documentation instructions:
- https://help.bitwarden.com/article/collections/#nested-collections-sub-collections

But they do not show nested in the Organization Vault view if the “parent(s)” Collection(s) do not exist. For example:

- `C01/C02/Test_collection01`
- `C01/C02/Test_collection02`

Do not show as nested collections of `C01` when Collections `C01/C02` and `C01` do not exist...is this the expected behavior?

**Comment by kspearrin** [comment]
Yes, this is expected behavior and is covered in the linked article.

> If a collection’s name contains the forward slash delimiter, yet no “parent” collection exists (or the user does not have access to the parent collection), its name will be displayed in its entirety.

**Comment by pachulo** [comment]
Ops, sorry for not reading properly...Thanks!
