### ISSUE TITLE
Option to quickly delete multiple / all logins

### ISSUE THREAD

**Issue by flawiddsouza** [bitwarden/web#39]
Is there an option to quickly delete multiple logins? Or am I just missing it?

**Comment by kspearrin** [comment]
There is no option for this currently, you are correct. Thanks for the feedback. We'll plan on adding it at some point.

For now, if you messed up on an import and need to purge everything from your account you'll hav to use the delete account feature and re-register.

**Comment by flawiddsouza** [comment]
Thanks. I guess that's that.

**Comment by kspearrin** [comment]
Available next release.

**Comment by bernd-wechner** [comment]
That's a year ago. Is that next release not out yet? I can't find a way to delete multiple logins and would love one.

**Comment by kspearrin** [comment]
Yes, it has been available for over a year now.

**Comment by BurninU** [comment]
I am  unable to find it as well.

**Comment by medizinmensch** [comment]
You can login into your [Vault online ](https://vault.bitwarden.com/#/vault). There you can select multiple Entries and delete them all at once.
There, under "Settings" -> "My Account",  you can also wipe your whole Bitwarden-Account ("Purge Vault", at the very bottom in the "Danger Zone" section).
Hope that helped

**Comment by Garconis** [comment]
How do you delete/purge from the Organization though? I imported records into the Organization without assigning it to a collection. Now I see no way to bulk update to a Collection. Nor do I see a way to delete these (so that I can reimport with a Collection assigned).
