### ISSUE TITLE
URL is lower-cased when importing 1Password 6/7 for Windows

### ISSUE THREAD

**Issue by scy** [bitwarden/web#390]
Hi there!

I'm in the process of migrating from 1Password to Bitwarden, mainly because it's open source and has a CLI client, and I like what I'm seeing so far.

One thing I've noticed while importing my existing passwords though: When you're using the CSV import feature in the web vault to import from 1Password 6/7 for Windows, the website URL will be converted to all lower-case. Usually that's not a problem, but for some sites it is. For example, one of my bank accounts uses https://www.gls-online-filiale.de/ptlweb/WebPortal?bankid=4967 as its login form, and when you replace `WebPortal` by `webportal`, you get a 404 error back instead.

Of course I made sure that the URL in the CSV file is correct before reporting this issue. 😉

**Comment by kspearrin** [comment]
Should be resolved in next version with https://github.com/bitwarden/jslib/commit/dff634d25e4f12dd9c9df5e077c9d9ce6f2a2f71

**Comment by sov-j** [comment]
@kspearrin I can confirm this now works OK, just tested on Bitwarden.com (web version 2.15.1) and URL case is preserved. I used KeePass import, but as far as I can see the fix was in a base class, so 1Password vs KeePass should make no difference.

**Comment by cscharf** [comment]
@sov-j , yes, this has been released across the board so should be resolved now.
