### ISSUE TITLE
Login to extension fails right after U2F dialog

### ISSUE THREAD

**Issue by jurjenoskam** [bitwarden/web#391]
I just installed a fresh copy of Win 10 1903 and Firefox 67, so I had to log in to the Bitwarden extension again. I have a Yubikey attached to my account as a second factor. After entering my master password in the extension, a Windows Security window pops up that instructs me to touch my security key:

![image](https://user-images.githubusercontent.com/39823959/58367179-6ee64380-7edc-11e9-85de-3abcf5edf9a6.png)

After pressing the button on the Yubikey, the window disappears but the extension is not logged in. From that moment on, clicking the extension icon in Firefox results in the message: "Unfortunately this window is not available in private mode for this browser".

Since I can't select any other MFA method (seems similar to #379), I can't login to the extension at all. Fortunately login to the web vault works with the yubikey.

**Comment by kspearrin** [comment]
Is this a problem in the browser extension? You are posting this in the web vault repo.

**Comment by jurjenoskam** [comment]
Shoot, you're right, this should have been in the browser extension repo...

**Comment by kspearrin** [comment]
Please create the issue in the browser repo if the problem resides there.
