### ISSUE TITLE
U2F error 1 on Firefox Android

### ISSUE THREAD

**Issue by PvdBerg1998** [bitwarden/web#395]
When trying to log in using FIDO U2F on Android with Firefox, it just spams red popups with "U2F Error 1".

**Comment by ericlingit** [comment]
I'm also getting this on Firefox 69 on Ubuntu 19.04. After I've entered the password, a red message with "U2F Error 1" keeps poping up.
![Screenshot from 2019-09-09 11-02-01](https://user-images.githubusercontent.com/25865675/64498892-99280980-d2f1-11e9-9ef9-831f91ff78af.png)

**Comment by djsmith85** [comment]
Hi @PvdBerg1998 , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
