### ISSUE TITLE
Deleting vault item is slow

### ISSUE THREAD

**Issue by breyed** [bitwarden/web#399]
In a vault with about 1000 items and 100k total data, deleting one takes 3.5 seconds.

The problem may be related to the slow load time of the vault web page (about 4 seconds).

Downloading and processing 100k of data at 4 seconds works out to 0.025 MB/s, which is really bad. A good goal would be for a vault this size to open in under 300 ms and operations to likewise complete in that time frame.

**Comment by kspearrin** [comment]
When you delete an item, the vault is reloaded. Reloading the data means it has to be decrypted. Decrypting and rendering 1000 items is an expensive process on your local client. I don't believe that slow download speeds is the problem unless this is what you are seeing in the network console.

**Comment by breyed** [comment]
You're right that download speeds aren't making loading slow. Chrome dev tools show traffic for about 200 ms, followed by a 3000 ms "eternity" of no traffic, followed by about a second of loading icons. The 3 seconds in the middle looks like the decryption you're referring to.

That decrypting timing isn't consistent with other client-side decryption timing, however. If I paste a 100k string into any of the [web crypto samples](https://mdn.github.io/dom-examples/web-crypto/sign-verify/index.html) on MDN, the browser encrypts and decrypts in the blink of an eye.

So it looks like there are two speedup opportunities. One is to not reload everything on delete, but instead just remove the deleted item. The other is when loading, to use a way faster decryption implementation.

**Comment by kspearrin** [comment]
Decrypting 1 blob totaling 100kb data is likely going to be a lot different than thousands of blobs totally 100kb. There is overhead involved with invoking the decryption method that gets realized much more the more times you call it.

**Comment by breyed** [comment]
Since loading the full vault is a common operation on all platforms, it would be good to optimize the way the vault is stored so that loading is always snappy fast. A standard way to approach this is to periodically store a baseline of the entire vault as a single encrypted block, with changes to recent individual items stored incrementally. The is the [write-ahead logging](https://en.wikipedia.org/wiki/Write-ahead_logging) approach that has been used to optimize databases for decades.

For example, if the vault contained the encrypted baseline plus 10 separate encrypted changes to the baseline, a load would need to perform only 11 decryptions, which it sounds like would be almost 100 times faster than the current 1000 decryptions currently required for a 1000-item vault.
