### ISSUE TITLE
[Feature request] Option to disable Gravatar

### ISSUE THREAD

**Issue by jonathonf** [bitwarden/web#4]
Gravatar is currently used by `vault.bitwarden.com` to provide an avatar image. This is conceivably a privacy breach; I know many people who don't want Gravatar to have a log of every "enhanced" website they visit.

Please default to Gravatar=off and have it as an option in the user's account settings.

**Comment by kspearrin** [comment]
Gravatars are removed in the next version and replaced with Microsoft/Google style "letter avatars".

**Comment by kspearrin** [comment]
Example:

![image](https://cloud.githubusercontent.com/assets/1190944/24728985/43fe2106-1a2a-11e7-83b4-1820023dfd59.png)
