### ISSUE TITLE
My Web Vault has "no items to list" in Chrome and FF on macOS

### ISSUE THREAD

**Issue by chriswayg** [bitwarden/web#400]
Yesterday my Web Vault still showed 3000+ items, but today it is empty on Firefox and on Chrome (macOS Mojave).

>There are no items to list.

The 3000+ items are still shown on iOS and in the Firefox extension.

I double-checked, that I’m using the same account. I did not change the Master Password.

Is there a problem with the Web Vault right now?

Other troubleshooting steps I tried:

- deleted bitwarden cookies
- disabled uBlock Origin adblocker
- connected with a VPN, in case there are any filtering or DNS problems

None of these changes made 'My Vault' visible. It is still empty on FF and Chrome.

**Comment by kspearrin** [comment]
Maybe there is some error preventing display from
occurring. Anything in dev tools console?

**Comment by chriswayg** [comment]
Hi Kyle, thanks for replying quickly!

I saw no relevant errors in the FF console. I tried about half a dozen times in each browser.

As I had recently imported about 1800 items, I tried the same vault in Safari and it works, but it loads pretty slowly.

I then deleted all items from the recent import, leaving only 1590 items. Now it loads again in Firefox 68 and Chrome 75 on macOS. You might be able to reproduce it with a sufficiently large vault of **about 3400 items**. I suspect, that one of the scripts had a timeout. (Location is in the Philippines  connected via fiber with a ping of 240 ms to the US and some packet loss.)

The items were imported from 1Password and therefore contain a number of custom fields as well as a good number of TOTP.

**Does bitwarden have a limit to the number of items it can handle in the Web Vault?**

**Comment by kspearrin** [comment]
There is no limit on the number of items you can have in your vault, so that should not be the issue. Obviously, the more items you have in your vault the more CPU/time it takes to decrypt that data. How long does it take to load your vault with the working 1500?

**Comment by chriswayg** [comment]
> How long does it take to load your vault with the working 1500?

Just a few seconds. The delay was only strongly noticeable when I had 3000+ items in the vault. In Safari it took maybe about 10 seconds on a Core i7 4770K, while it failed in the other browsers. I did not measure the time and have since reduced the number of items, as I was just testing different versions of the import from 1Password. 

I'm on the individual Premium account and we are still evaluating, if Bitwarden is a good fit for us and our missions ministry. I've recommended Bitwarden to others, as it is currently the best free option for our church members in the Philippines.

**Comment by 2lazy2debug** [comment]
Hi, joined a bit late to the party, but we had the same exact problem + the accounts weren't in the organisation anymore. 
I don't know how nor why but it turned out to be a disk space problem. Expanding the allocated space made everything appear again.
