### ISSUE TITLE
Refreshing the vault page logs me out / locks my vault

### ISSUE THREAD

**Issue by RohanTalip** [bitwarden/web#402]
Steps to reproduce:
1. Use Chrome (v75, on a Mac, in a regular or guest window) to log into the vault website --> the browser shows the URL is https://vault.bitwarden.com/#/vault
2. Refresh the page (I had recently verified my email and wanted to see that it changed the call-to-action / prompt).
3. I'm shown the https://vault.bitwarden.com/#/lock page which shows the text "Your vault is locked" and I am prompted to enter my master password again.

I'm not sure if this is intentional, but either way, it's not a good user experience.

**Comment by kspearrin** [comment]
This is the expected behavior. Encryption keys are only held in memory while the application is unlocked. When you refresh the page, memory state is purged causing the keys to drop and the vault to lock. Therefore, an unlock is required.

**Comment by zenVentzi** [comment]
I don't know if it's expected but it's not for the users. First time user here. I see in settings there you can setup the timeout, be it on refresh or in 30 minutes. I set it to 30 minutes and on refresh I still get locked out of the vault. Not expected.

**Comment by RohanTalip** [comment]
See also https://www.reddit.com/r/Bitwarden/comments/md8lz5/refreshing_web_vault_on_bitwarden_rs_causes_log/

I think this could be solved with a (background) web worker: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API

I also just voted on https://community.bitwarden.com/t/improve-lock-and-log-out-settings/17906
