### ISSUE TITLE
Search results wrong after doing something that changes the search results

### ISSUE THREAD

**Issue by jikamens** [bitwarden/web#403]
1. Put something in the "Search Vault" box to filter the search results.
2. Do something to one of the items in the search results that causes it to no longer be part of the search results.
3. The search results are completely cleared, and the only way to get back the previous search results is to erase and redo the search.

Example: delete an item in the search results.

Example: search for `>-organizationid:*` to find unshared items and then share one of them.

**Comment by jikamens** [comment]
Actually, the problem is even worse than described above. The search results are cleared even if you do something as simple as editing an item and then saving it without making any changes to it.

**Comment by kspearrin** [comment]
Resolved in next version. Thanks.
