### ISSUE TITLE
KeePassXC import best practice

### ISSUE THREAD

**Issue by thomai** [bitwarden/web#406]
I'd love to switch over from KeePassXC but after researching some time, I was not able to find any possibility that worked for me.

Importing the kdbx file directly ends in a general error message in the web UI. It states that the file cannot be parsed. I also tried to export a CSV file but this either did not work with the same error message.

Do you have any best practice regarding that issue? I found a few people stating that a CSV file import should work as it should for KeePassX. Unfortunately, this didn't work for me.

**Comment by thomai** [comment]
Just solved it utilizing KeePass 2 itself as described in the web UI

>  **KeePass 2 (xml) Instructions**
Using the KeePass 2 desktop application, navigate to "File" → "Export" and select the "KeePass XML (2.x)" option. 

Full description of the workaround:
1. Close KeePassXC
2. Open the `kdbx` file with KeePass 2
3. File => Export => KeePass XML (2.x)
3. Bitwarden => Tools => Import Data => Select "KeePass 2 (xml)" as the import format.
4. Import the previously exported XML file
5. Profit!

**Comment by ihnorton** [comment]
Note for anyone else who comes across this and doesn't have KeePass 2 available:
- use the KeePassXC CLI to export`keepassxc-cli export Passwords.kdbx > export.xml`
- then use `bw import keepass2xml export.xml` or the web import interface
