### ISSUE TITLE
Display whether an item is part of a collectionin edit view

### ISSUE THREAD

**Issue by tobias--** [bitwarden/web#409]
The edit dialog of an item does not show whether this item is a shared item and to which collections it belongs. You should be able to view and even edit to which collection it belongs. 

Especially since item names don't have to be unique, it is hard to tell items apart without knowing to which collection they belong.

**Comment by ruffy91** [comment]
This is especially true for the exposed passwords report where it is impossible to find out which entry really is the right one because the collection is not shown.
