### ISSUE TITLE
Importing 1Password export w/ CC data fails

### ISSUE THREAD

**Issue by chiefy** [bitwarden/web#41]
When exporting your 1Password vault, you can "export all..." which includes things like bank accounts and credit cards. When I include credit card exports, the website throws a JS error when trying to import the `.1pif`:

```
app.min.js?v=xqdea5rk9:formatted:1312Uncaught TypeError: s[r].split is not a function
    at o (app.min.js?v=xqdea5rk9:formatted:1312)
    at FileReader.c.onload (app.min.js?v=xqdea5rk9:formatted:1340)
o @ app.min.js?v=xqdea5rk9:formatted:1312
c.onload @ app.min.js?v=xqdea5rk9:formatted:1340
```

I'm not sure if bitwarden should support storing CC info, or if the documentation on exporting 1Password data should include this caveat?

**Comment by kspearrin** [comment]
Thanks. This is a known bug with the 1Password importer when exporting 1pifs from a Mac. I was told that the same problem did not occur when exported on Windows, which seems kind of odd.

**Comment by kspearrin** [comment]
Resolved https://github.com/bitwarden/web/commit/a20e8b62283a5b1eaa28a3d70b73dd6ed671c919
