### ISSUE TITLE
Expand folder button is shown even for empty folder

### ISSUE THREAD

**Issue by stilettk** [bitwarden/web#414]
The "expand" icon is shown even for folders without children. This is confusing because user is trying to expand the folder to see its subfolders, but then he discovers that there is nothing there. If I had 50 folders, how would I determine which of them have children? By clicking each of them?
![image](https://user-images.githubusercontent.com/7068016/66041680-188caf80-e523-11e9-8582-a0fb0d33e5ce.png)

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/web/pull/410

**Comment by stilettk** [comment]
Oh, there is already a pull request! But it's 1 month old now... When it's gonna be merged?
