### ISSUE TITLE
Unable to import data from RoboForm CSV (plain text vs encrypted value)

### ISSUE THREAD

**Issue by sunk818** [bitwarden/web#419]
For privacy reasons, I obviously can't disclose the contents of the file. If you could explain what Ciphers[847] means, I can look at the CSV myself and see what length is over 10k. Is 847 referring to the CSV line itself, or is it referring to a record row that may span multiple lines? I've been using password manager for over 10 years so there's some cleanup I should do. ;)

![191007-00](https://user-images.githubusercontent.com/6989799/66322730-6dd81080-e8d7-11e9-9cef-47b7d98d2aea.jpg)

**Comment by kspearrin** [comment]
This article should help.
https://help.bitwarden.com/article/import-data/#troubleshooting-import-errors

**Comment by sunk818** [comment]
Notepad++ says the note is only 1,208 characters long. Does the encryption multiply the length of the field beyond 10k? Realistically, how much plain text data can we have then... about 1,000 characters?

**Comment by kspearrin** [comment]
Did you offset by 2 to include the header and 0 index? 847 would be at line number 849, for example.

**Comment by sunk818** [comment]
> Did you offset by 2 to include the header and 0 index? 847 would be at line number 849, for example.

Thanks for explaining of the offset of 2.

That row is 8,914 characters for notes field. There must be some overhead going from plain text to encryption value?

For example, if I use text to base64, the character count changes to 11,640 after conversion.

**Comment by kspearrin** [comment]
About 6k plaintext characters will become 10k when encrypted.

**Comment by sunk818** [comment]
Okay, thank you for explanation. I see why the import failed for those records. Time for some cleanup!
