### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by lolo88l** [bitwarden/web#42]
I cannot log in to access my vault from the web client for some days. But the android and browser apps works, I can unlock them with my password.
I use Firefox, but I have the problem on Chrome too. Not tried on other browsers.

I did nothing special :-s Any idea ? Did you need some additional info ?

Request:
```
POST /connect/token HTTP/1.1
Host: api.bitwarden.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: application/json, text/plain, */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://vault.bitwarden.com/
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Content-Length: 141
Origin: https://vault.bitwarden.com
Connection: keep-alive
```
```
client_id=web
grant_type=password
password=XXXXX
scope=api+offline_access
username=XXXXX
```

Response:
```
HTTP/2.0 400 Bad Request
Date: Wed, 15 Feb 2017 11:34:31 GMT
Content-Type: application/json
Set-Cookie: __cfduid=XXXXX; expires=Thu, 15-Feb-18 11:34:28 GMT; path=/; domain=.bitwarden.com; HttpOnly
Cache-Control: no-store, no-cache, max-age=0
Pragma: no-cache
Access-Control-Allow-Origin: *
x-rate-limit-limit: 1m
x-rate-limit-remaining: 59
x-rate-limit-reset: 2017-02-15T11:35:28.6538999Z
X-Powered-By: ASP.NET
Server: cloudflare-nginx
CF-RAY: 3318736cdebc4433-BRU
X-Firefox-Spdy: h2
```
```
{"error":"invalid_grant","error_description":"invalid_username_or_password","ErrorModel":{"Message":"Username or password is incorrect. Try again.","ValidationErrors":null,"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Object":"error"}}
```

Thanks !

**Comment by kspearrin** [comment]
Have you ever changed your master password in the history of your account or is it the same since you first registered?

**Comment by lolo88l** [comment]
Thanks for the fast response.
I never changed my password. It's the same since I registered.
Thanks !

**Comment by kspearrin** [comment]
Well that's concerning...

Can you please contact me via email so we can work on debugging this issue offline? https://bitwarden.com/contact/

**Comment by lolo88l** [comment]
I'ts resolved !
Thanks for the fast reply and fix !

**Comment by unix786** [comment]
How did you resolve it? I got the same issue.

**Comment by anaganisk** [comment]
@kspearrin @lleleux Would be great if you pasted how it was resolved

**Comment by unix786** [comment]
The issue no longer reproduces for me. Maybe Hinton's commit actually fixed it. Or maybe it's because I changed the vault password at some point. Don't know what else could it be.
