### ISSUE TITLE
KeePass2 xml import does not unwrap REFs

### ISSUE THREAD

**Issue by Ciantic** [bitwarden/web#420]
If I import a KeePass2 XML file with REFs the BitWarden can't unwrap them.

Refs are documented here: https://keepass.info/help/base/fieldrefs.html

Mostly they are useful to get over KeePass's single URL limitation. I have dozens of entries with reference e.g. {REF:P@I:46C9B1FFBD4ABC4BBB260C6190BAD20C} pointing to password in the UUID 46C9B1FFBD4ABC4BBB260C6190BAD20C, only thing differing is the URL.

**Comment by jampe** [comment]
@Ciantic I've created my own KeePass 2.x importer which solved this issue for me. It supports reference unwrapping for usernames and passwords. See #426 for more info.
