### ISSUE TITLE
Cannot create Recovery Code

### ISSUE THREAD

**Issue by paradeiser** [bitwarden/web#421]
Using a selfhosted Bitwarden instance (2.12.0 / 1.10.0-ae8bf954) I recently run into an odd problem:
Duo is working fine for multiple accounts, for now I also activated Mail as 2FA.
I just wanted to view my Recovery Code (lucky me just for a test-account) and got the reply:
"No 2FA activated. After you activate 2FA you can view code here…"

There are defenitly checkmarks for Duo and Mail, they also work properly. Also tried to kick all active sessions and re-activate Duo.
I still get no recovery code. (Using my main account it works as expected tho.)

any ideas?
thanks,
paradeiser

**Comment by kspearrin** [comment]
Could you please provide a screenshot of this error message?

**Comment by paradeiser** [comment]
This is the german message:
<img width="495" alt="Bildschirmfoto 2019-10-14 um 17 08 46" src="https://user-images.githubusercontent.com/43011936/66762030-75825100-eea5-11e9-8071-b64caaf7d5fa.png">

Anyways - I got rid of this message by also activating the 1st 2FA option "Authentication-App" (like Authy, Google Authenticator). Now I can access the recovery code.

Before, only "Duo" and "Mail" was active and I did not get the recovery code.
Strange thing now: After deactivating all 2FA options (or also after resetting 2FA in the Admin Panel) I _still_ can view the recovery code (tho there is no 2FA active).

Hope this helps,
best regards,
paradeiser

**Comment by kspearrin** [comment]
I am trying to reproduce this. I created a new account with no  2FA enabled yet, viewing the recovery code results in the error message you posted. This would be expected since you have not setup 2FA yet. Once I enabled 2FA via email, the recovery code is now visible.

With Duo, were you using Duo configured at the organization level or configured for your account personally?

**Comment by paradeiser** [comment]
I used the global Duo keys
<To use the global Duo keys, please leave these fields untouched> I defined in the config.

I just reproduced the issue in two different ways:

A)
1. Invite user
2. Register new user
3. Activate 2FA with Duo
4. re-login / proceed with Duo setup
5. open Settings > 2FA > Recovery Code
6. same error message as described

B)
Same with a new user and Email instead of Duo.
Same using both 2FA options.

Only after also activating "Authentification-App" (6-digit-code) I can view the recovery code.
Then I can view it even after deactivating all 2FA options (confirmend in the Admin-Panel).

maybe its my instance - dont know (bitwarden_rs in docker)?
still thanks for looking into it!

**Comment by kspearrin** [comment]
Yes, please open the issue with bitwarden_rs folks. This is not a problem with official Bitwarden.
