### ISSUE TITLE
twofactorauth.org integration not working

### ISSUE THREAD

**Issue by Bluetexon** [bitwarden/web#422]
I wanted to check my 2FA accounts and saw that it thinks that all possible accounts have 2FA enabled. Some weeks ago it listed some accounts and I haven't changed the 2FA's since.
In Chrome DevTools it showed me the following:
![image](https://user-images.githubusercontent.com/22718113/67700141-b1d9a500-f9ad-11e9-87ec-ab42dd08af31.png)
Other browsers couldn't work either.

Just write me in case you need any additional information.
Thank you :)

**Comment by kspearrin** [comment]
Fixed for next version. Thanks

**Comment by OLLI-S** [comment]
> Fixed for next version. Thanks

@kspearrin when will the fix be released?

**Comment by romprod** [comment]
This currently doesn't work for me as well.

Self hosted with docker containers on Ubuntu 20.04

![image](https://user-images.githubusercontent.com/3393004/108912605-c620c700-7620-11eb-9000-1951edf94219.png)

**Comment by cscharf** [comment]
It's fixed now, v2.18.2 is live.
