### ISSUE TITLE
Keepass XML import does not import images

### ISSUE THREAD

**Issue by psoberoi** [bitwarden/web#426]
Keepass XML import seems to silently ignore images. This makes me worry what else might be excluded that I haven't noticed yet.

**Comment by kspearrin** [comment]
Binary files are not imported from any of the importers.

**Comment by psoberoi** [comment]
It would be nice if the importer generated warnings for content that was not imported.

**Comment by jampe** [comment]
@psoberoi I had the same issue and solved it by writing my own KeePass 2.x importer using python and bw cli. Check it out at https://github.com/jampe/kp2bw 

Hope it works for you as well.

**Comment by psoberoi** [comment]
I used the importer that @jampe implemented (see above), and that worked well for me. I don't need further help.

I would still recommend that your importer should at least issue a warning if it encounters data that it cannot handle.
