### ISSUE TITLE
Downloaded attachment always has txt file extension

### ISSUE THREAD

**Issue by schroenser** [bitwarden/web#428]
When downloading attachments via the web vault, the file extension is always changed to `txt`.
The entry in the attachment list contains the file name with the correct extension.
Saving the attachment with the desktop client (Windows 10) produces a file with the correct extension as well.

Renaming the file manually seems to work, at least for all files and types that I have tested with, so probably the content is correctly encoded.

**Comment by kspearrin** [comment]
I am not able to reproduce in Firefox or Chrome.

**Comment by schroenser** [comment]
The fact that you cannot reproduce the problem gave me a hint: I'm using Chrono Download Manager in Chrome. If I disable it, the download starts with the correct file name.
So either it's Chrono's fault or some weird interaction between Bitwarden and Chrono.

Either way, I'm sorry to have taken up your time. Thanks for reacting this fast.
