### ISSUE TITLE
Upgrade to API V3 of https://haveibeenpwned.com/

### ISSUE THREAD

**Issue by moulip** [bitwarden/web#429]
Hi,

When clicking on Check Breaches in the Data Breach Report section, we get a failed to fetch.
This is due to the API V2 BitWarden is using being deprecated. 
It suggests to update to API V3 :

This version of the API has been discontinued, please use V3: https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/

**Comment by kspearrin** [comment]
We already use v3. Is this self-hosted? Are you using the latest server?

**Comment by moulip** [comment]
Yes I'm self-hosted and have updated to the latest version.

**Comment by kspearrin** [comment]
Did you provide your hibpApiKey in the environment variable settings under `bwdata`?

**Comment by moulip** [comment]
Hi,

That I didn't do.
I will do that right now.
But I assume I wouldn't get an API version error if that was just the lack of the key.
No ?
11 décembre 2019 02:20 "Kyle Spearrin"  a écrit:
	Did you provide your hibpApiKey in the environment variable settings under bwdata?

**Comment by mountainash** [comment]
>But I assume I wouldn't get an API version error if that was just the lack of the key.

Sounds like the issue is with API, not BitWarden. Task closed?
