### ISSUE TITLE
To increase security, add bitwarden.com to HSTS Preload List

### ISSUE THREAD

**Issue by setyb** [bitwarden/web#432]
To increase security, can you add 'bitwarden.com' to the HSTS Preload List?

See: https://hstspreload.org/

**Comment by kspearrin** [comment]
![image](https://user-images.githubusercontent.com/1190944/70803927-295b6c00-1d83-11ea-8b03-b29a72a0bdc8.png)

**Comment by andrazznidar** [comment]
There might be a regression. _bitwarden.com_ might not be on HSTS Preload List any more and subdomains like _vault.bitwarden.com_ are not preloaded.

<img width="710" alt="2022-01-30 17_28_24-HSTS Preload List Submission — Mozilla Firefox" src="https://user-images.githubusercontent.com/8482843/151708137-bb90d9be-db85-48b2-98f5-46a9bdb90ff8.png">
<img width="710" alt="2022-01-30 17_27_45-HSTS Preload List Submission — Mozilla Firefox" src="https://user-images.githubusercontent.com/8482843/151708145-7452bbcc-24b7-479d-a572-07950da9c54f.png">

**Comment by kspearrin** [comment]
@joseph-flinn @sneakernuts Not sure what happened here.

**Comment by sneakernuts** [comment]
![image](https://user-images.githubusercontent.com/671942/151890424-f2590f44-37a3-4e30-9401-b2e618d1e0c1.png)

Thanks @ljbw
