### ISSUE TITLE
Disable search vault suggestions/predictions in chrome extension

### ISSUE THREAD

**Issue by rmcs2002** [bitwarden/web#433]
Is it somehow possible to disable the suggestions/predictions in the google chrome extension? It always shows me something like this:

![bitwarden-suggestions](https://user-images.githubusercontent.com/6650207/71068573-4a530100-2177-11ea-8058-9f086f32b086.jpg)

Clicking anywhere in the extension screen and it's gone, but it's annoying :)

**Comment by kspearrin** [comment]
Fixed in next version.
