### ISSUE TITLE
Bug while importing Dashlane 's data (JSON format)

### ISSUE THREAD

**Issue by Marcounet** [bitwarden/web#435]
Hi!
I have a problem while importing Dashlane datas in JSON format. And sorry for my average (style F--) english.
Export from Dashlane in JSON format is very easy. Import the JSOn file in my safe-box easy ? Non. Because, all links are not the correct link. Example :
    Link in Dashlane : https://setiathome.berkeley.edu//edit_passwd_form.php
    Translate link in Bitwarden : https://www.berkeley.edu/
You see the problem ? Bug in all my password recorded !!! How can I resolve that ?

**Comment by kspearrin** [comment]
Can you post an example data export from dashlane that theodicies this problem?

**Comment by Marcounet** [comment]
OK, here compressed.
[Dashlane Export.json.zip](https://github.com/bitwarden/web/files/3992646/Dashlane.Export.json.zip)

**Comment by kspearrin** [comment]
@Marcounet As you can see in your exported file, Dashlane does not include the full URLs. We only get hostname data from their export.

**Comment by yak0n** [comment]
@Marcounet just want to inform you that u uploaded all your credentials here. seems to be an older export, but better to remove :)

**Comment by Marcounet** [comment]
Thanks. I've modified the password twice already. But I didn't know how to delete the archive. Can you help me ?
