### ISSUE TITLE
copy/paste password not working on Chrome/Safari in version 2.12.1 from git

### ISSUE THREAD

**Issue by pdarcos** [bitwarden/web#436]
Hi,

I just compiled the web vault today from latest master for testing on my self-hosted installation.

Everything compiled fine (except for the known sweetalert bug where I used your workaround) [see here](https://github.com/t4t5/sweetalert/issues/890)

But now when using the newly compiled web-vault (with no changes from the git code master branch) I noticed something really strange that happens with Chrome browser (apparently also happens on Safari although I haven't tested Safari much yet).

Basically I can no longer copy/paste the password from within the vault entry even though I get the usual "Password copied" confirmation message.Although I get the usual confirmation, in reality the password is not copied to the clipboard. If I go back to the vault listing and use the drop down menu to Copy Password it works as expected, just not within the Item itself.

Strangely on Firefox all works as expected.
Even stranger is the fact I just tested the same browsers on vault.bitwarden.com and on your site they work normally. I see your vault is using version 2.12.1 same as the one I just compiled so I don't understand why the behavior seems different when the code should be the same.

Any clues?

Cheers

**Comment by kspearrin** [comment]
The copy code should be the same. I don't think that has changed recently. I will have to test this on my macine and see if I can reproduce.

**Comment by pdarcos** [comment]
FYI and to save you some time: I just recompiled and instead of master, this time I used the 2.12.0 tag and now copy/paste works as expected on Chrome.
I'm about to test on Safari but I suspect something broke in these last few months.

BTW, npm warns about lots of security vulnerabilities in the packages when compiling 2.12.0 (2.12.1 only gave 3 or 4 vulnerabilities) and if you try to fix them the changes are breaking.

**Comment by pdarcos** [comment]
Just tested it with Safari on a MacBook and indeed it works fine with 2.12.0

I think these tests confirm something broke since the 2.12.0 release in September.
What HEAD are you using in the web-vault? It says 2.12.1 in web.bitwarden.com but I don't think it's the latest master branch or else I'd expect you to have the same issues.

Let me know if you need me to do some testing

**Comment by pdarcos** [comment]
@kspearrin were you able to reproduce?

**Comment by kspearrin** [comment]
@pdarcos Yes, I can reproduce. Will have to look into it more.

**Comment by kspearrin** [comment]
Should be fixed with https://github.com/bitwarden/web/commit/45c07b7c394f33abca2d35b1689743e493a824d8

**Comment by pdarcos** [comment]
I can confirm your patch fixed it.

Thanks and Happy New Year!
