### ISSUE TITLE
Launch button icon missing in Safari

### ISSUE THREAD

**Issue by ntimo** [bitwarden/web#438]
Hello,
when editing a entry using the web vault (vault.bitwarden.com) the launch button on right side of the curl is missing. The copy button gets displayed correctly.

Safari version: Version 13.0.4 (15608.4.9.1.3)

<img width="792" alt="Screenshot 2020-01-02 at 16 38 02" src="https://user-images.githubusercontent.com/6145026/71675788-e176a600-2d7e-11ea-8d5d-c7b509934eb8.png">

**Comment by kspearrin** [comment]
I am not able to reproduce the issue with Safari 13.0.4. Did you try refreshing?

**Comment by ntimo** [comment]
Okay I found the the problem. It was 1Blocker messing it up. Sorry, I wish you a nice day.
