### ISSUE TITLE
Fritz.box - Missing Icon

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/web#439]
I have a router called Fritz!Box that I can configure under the URL http://fritz.box/
When I open that URL I see an icon in the browser tab:

![image](https://user-images.githubusercontent.com/8037790/71725749-4987c380-2e35-11ea-8ad8-88629afc572b.png)

In my web vault I see no icon.
Please load the icon also from this website (http://fritz.box/favicon.ico)

**Comment by kspearrin** [comment]
http://fritz.box/ seems to only be available on your LAN. I cannot access it. The website has to be accessibility over the public internet for it to be served by our icons server.

**Comment by OLLI-S** [comment]
It is a website provided by the router (internal network).
So the custom-icons feature (I can manually upload an icon) will help here.

**By the way:** KeePass in combination with the plugin "Favicon Downloader" can download the favicon (I know that KeePass is running locally, so he can access the icon on the router).
