### ISSUE TITLE
CSS rule hides the item actions button for screen readers

### ISSUE THREAD

**Issue by tyrylu** [bitwarden/web#440]
The following CSS rule causes the actions button in the items table, at least for screen readers not to be visible (no idea whether the rule is the exact rule in the CSS file, but this came out of Firefox developer tools):
```
.table.table-list td.table-list-options > .dropdown:not(.show) button {
	visibility: hidden;
}
```
And it does it exactly as you would expect - the button is hidden and you have no idea that the item has some actions at all. Pressing space on the right place works, but that's not my definition of good UX.

**Comment by kspearrin** [comment]
What would be the proper way to handle this in an accessible-friendly way while achieving the same effect for non-accessible users (don't show until hover)?

**Comment by tyrylu** [comment]
Very likely some positioning tricks, but not sure exactly, e. g. start from for example this article: https://a11yproject.com/posts/how-to-hide-content/
And when at it, you could add an aria-label to the button as well, it is not obvious what the thing does.

**Comment by kspearrin** [comment]
Should be fixed for next version with https://github.com/bitwarden/web/commit/bd2cba1f31d46fcbffb5c2dc91c70109abacec8b

Thanks for the feedback.
