### ISSUE TITLE
Enpass import doesn't work

### ISSUE THREAD

**Issue by lucian303** [bitwarden/web#441]
Importing a CSV file generated by enpass imports all the entries without passwords. So it's useless.

Version 1.16.6
Shell 5.0.8
Renderer 73.0.3683.121
Node 12.0.0
Architecture x64

**Comment by lucian303** [comment]
Yes. Also, sorry if this issue maybe should have been in the server repo?

```
"10.0.0.1","Username","admin","E-mail","","*Password","fakepw","Website","http://10.0.0.1/Main_Login.asp","ADDITIONAL DETAILS","","Phone number","","TOTP","","Security question","","*Security answer",""
```

**Comment by lucian303** [comment]
I saw that there was a JSON option as well, so I tried using that. I got this error. I'm not sure what it means, but I am certain that I do not have a password anywhere near that length and that the json is valid json. I don't know which entry it's erroring out on so I'm not sure which json to sanitize and provide in this case.

```
An error has occurred.
Ciphers[367].Login: The field Password exceeds the maximum encrypted value length of 1000 characters.
```

**Comment by lucian303** [comment]
This page talks about the error but doesn't help much: https://help.bitwarden.com/article/import-data/. This is JSON so which entry is #367? How do I find the part that's wrong?

**Comment by kspearrin** [comment]
@lucian303 You need to locate the item in the JSON at index 367 and see why it has such a long password.

**Comment by djsmith85** [comment]
Hi @lucian303, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
