### ISSUE TITLE
Ability to create collections in the organization from an employee account.

### ISSUE THREAD

**Issue by jdgregson** [bitwarden/web#444]
(I apologize if this is considered a "feature request", but to me it seems more like modifying existing features.)

**Background**
At my company we have a main Bitwarden account which owns the organization. Inside the organization there are collections with all of our shared passwords. These collections are then shared to individual employee's Bitwarden accounts. Nobody actually uses the main company account on a daily bases.

**The issue**
The issue with this setup is that users with full control over a collection cannot add additional collections to the collections they can access. For example, suppose we have some collections like  `IT/Servers/Server01` and `IT/Servers/Server02`. One day we buy another server and want to keep track of its passwords in the same way. In order to create the `Server03` collection inside of the `IT/Servers` collection, I need to log into the main company account, browse to the settings for the organization, and add the new collection from there.

**The solution**
Ideally, if a user has full control of a collection which is owned by the organization, they should be able to create sub-collections inside of those company-owned collections.

**Comment by kspearrin** [comment]
@jdgregson Does the "Manager" role not solve this problem for you? Managers can create new and manage the collections they are assigned to.

**Comment by jdgregson** [comment]
Oh nice, that does solve the problem. Honestly I've never noticed the option to set my account as a manager or an admin, and I've been running as a user this whole time. However, I do remember setting the "This user can access and modify all items" option on my account, so I've been thinking that's the closest to an admin I could make myself.

![bitwarden](https://user-images.githubusercontent.com/3778841/73044883-7b7ebb00-3e20-11ea-80d4-d6d054dcd66a.png)
