### ISSUE TITLE
"Go Premium" still visible when you're already Premium(Enterprise user)

### ISSUE THREAD

**Issue by ruant** [bitwarden/web#447]
When you're an enterprise user, you get Premium user automatically.
Why does the web (and also Chrome plugin) have the option to "Go Premium"?
(I haven't checked the other apps, if it's shown there as well)

The premium features however seams to work fine (like 2FA).
Just a bit confusing/misleading that it's shown when you actually have it.

**Comment by kspearrin** [comment]
It is possible to purchase a premium membership subscription independently from your organization membership (which gives you premium access as well). Some people may be temporarily in an enterprise organization and still need to maintain their premium status. We provide a note at the top of the page that let's the user know that they already have premium access from their organization membership.

**Comment by Mart124** [comment]
See this related "issue" report / enhancement request : https://github.com/bitwarden/server/issues/387

**Comment by ruant** [comment]
Cheers for the quick reply.
What you say makes sense, and since it's already tracked in the other issue I'm happy with closing this 😃
