### ISSUE TITLE
Localization issues: Missing plural form

### ISSUE THREAD

**Issue by mKoonrad** [bitwarden/web#449]
There are many missing plural form in your strings. Texts like "item(s)" looks bad. In many languages translators need to have one, few (2-4 etc) and also many (>4 etc) forms.

See grammar rules: https://www.unicode.org/cldr/charts/33/supplemental/language_plural_rules.html#pl

Updated issues 20.05.2020:
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L224
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L747
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L756
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L765
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L1327
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L1348
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L1372
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L1387
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L1405
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L1426
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L1472
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L3083
https://github.com/bitwarden/web/blob/da2e740e652ccf136a2cbe4fb9004ff2d908f073/src/locales/en/messages.json#L3122

**Comment by mKoonrad** [comment]
@mKoonrad Issue still present

**Comment by mKoonrad** [comment]
@dwbit All already reported since last 2 years

**Comment by dwbit** [comment]
Thanks for confirmation, if there aren't any currently open, please create a new issue for review.

**Comment by mKoonrad** [comment]
@dwbit Ok. I will check it in coming days.
