### ISSUE TITLE
[bug] Max password length accepted is not 300

### ISSUE THREAD

**Issue by LivingWithHippos** [bitwarden/web#45]
Spent a couple of hours trying to import my Keepass database but it wouldn't let me, saying there was a password longer than 300 characters. After running a regex I couldn't find it, so today I imported one group at time and I found it was a 193 characters long password. I tested some numbers and the maximum length for this field is 191, even if the error message says otherwise. I tried to create a new login for the vault and I still get this error so I'm pretty sure it wasn't an import problem

**Comment by kspearrin** [comment]
The is a server error that is firing due to a API call validator on the **encrypted** length being less than 300. This is why you are seeing the difference vs your unencrypted password. I plan to remove these limitations in the future.

**Comment by kspearrin** [comment]
This was raised to 1000.
