### ISSUE TITLE
Importing from 1Password added the trashed entries

### ISSUE THREAD

**Issue by MacTwister** [bitwarden/web#451]
I am in the process of migrating from 1password (v6.8.7) to Bitwarden and tested out the export/import. 👍 

After import, I realized that I had a lot of extra "passwords", which looked like my old deleted entries from 1password. The solution for me was to empty my trash in 1password and export again. So I thought I would share, that for future people, 1password imports could handle trashed entries.

I did notice the `.1pif` the file had an extra property in the "json entry" to indicated trashed, like so:
```
{"trashed":true}
```

Thank you

**Comment by kspearrin** [comment]
Can you provide a full example of the trashed property in the context of the json object itself? Is it at the root? Your existing example seems to imply that.

**Comment by MacTwister** [comment]
```
{"uuid":"073B0641DBCF435DA5E1BE9C583F36C7","updatedAt":1580844441,"locationKey":"example.com","securityLevel":"SL5","contentsHash":"9dc6d016","trashed":true,"title":"Test webapp","location":"https:\/\/example.com","secureContents":{"URLs":[{"label":"","url":"https:\/\/example.com"}],"fields":[{"value":"myusername","name":"username","type":"T","designation":"username"},{"value":"uniquepassword","name":"password","type":"P","designation":"password"}]},"txTimestamp":1580844441,"createdAt":1580844407,"typeName":"webforms.WebForm"}
***5642bee8-a5ff-11dc-8314-0800200c9a66***
```

**Comment by kspearrin** [comment]
Should be resolved with https://github.com/bitwarden/jslib/pull/64
