### ISSUE TITLE
Importing from 1Password does not preserve "last updated" date time

### ISSUE THREAD

**Issue by MacTwister** [bitwarden/web#453]
After importing successfully my 1password into Bitwarden, I noticed all the **Updated** labels had the date/time of when the import was preformed. 

I was not sure if there was any reasoning behind not reading the last updated timestamp from import data. If this was intended then ignore this as a bug.

I feel overall, I miss the ability to some see/sort the date of passwords were created/updated so if one has not been updated in X time. For example, I always though it was encouraged to update your critical, ie email, passwords yearly.

- Created - not show anywhere
- Updated - shows date of import or if the changed date when making changes in Bitwarden
- Password updated - not shown after imported all entries. Show when you change a password in Bitwarden after import.
- Password history - Shows the number of times password was changed and dates in popup. Not shown if password was never changed on entry.

Thank you for your time.

**Comment by MacTwister** [comment]
To simplify, I was wondering why import does not read "createdAt" or "updatedAt" properties in the import JSON and apply to the Bitwarden "last updated" property. I could also imagine the updated at field is getting automatically updated during the "saving" process of the entity, which may make it difficult to manually update it.

```
{"uuid":"B8E8B97058674909BEDEDEFAB21B4CBC","updatedAt":1404300771,"locationKey":"","securityLevel":"SL5","openContents":{"tags":["sam"]},"contentsHash":"b5064173","title":"Test PIN","location":"","secureContents":{"URLs":[{"label":"website","url":""}],"password":"0000"},"txTimestamp":1404300771,"createdAt":1404298486,"typeName":"passwords.Password"}
```

**Comment by kspearrin** [comment]
Creation and update dates are generated by the Bitwarden server and are critical to certain functionality of how the server operates. We cannot support those values from a historical import.
