### ISSUE TITLE
Lock Options are not saved after logout

### ISSUE THREAD

**Issue by elias-pap** [bitwarden/web#456]
Steps to reproduce:

1. Go to Settings -> Options.
2. In Lock Options section, select "On Browser Refresh" and click Save.
3. Log out, close browser.
4. Reopen browser and log in again.

The selected value in Lock Options has been reset to default (15 minutes) instead of keeping the previously selected one (On Browser Refresh) that should have been saved.

I've reproduced this on Firefox and Brave, using Private Browsing mode.

**Comment by kspearrin** [comment]
This is expected hwne using private mode. These values are stored on local storage on the browser. When using private mode, local storage does not persist.

**Comment by elias-pap** [comment]
Would be nice if they were stored server side. Local storage could be purged anytime, e.g. for privacy reasons.
