### ISSUE TITLE
No entries shown on one machine in Firefox

### ISSUE THREAD

**Issue by zoechi** [bitwarden/web#467]
I have several Linux and Windows VMs on my main machine and 2 Bitwarden accounts and use it with Chromium and Firefox and native client. It's working fine everywhere.

Now I set up a notebook with Linux and Bitwarden is working fine in Chromium and native client, but in Firefox it shows no items. The vault is completely empty. 
I can access all items just fine with Web vault in Firefox, but not with the plugin.
I also can access all items with the plugin of my 2nd Bitwarden account in Firefox.

Removing and re-adding the plugin 
and synchronizing manually
didn't help. The vault is still empty.

**Comment by kspearrin** [comment]
Can you check developer tools and see if any errors are reported in the console?

**Comment by zoechi** [comment]
The machine is currently not booting (Macbook where I tried to install Linux)
I'll respond when I find time to continue working on the setup.

**Comment by zoechi** [comment]
I don't think I'll be able to work on this anytime soon. 
I'll reopen if I see it again. 
Thanks for the help and patience.
