### ISSUE TITLE
import from firefox

### ISSUE THREAD

**Issue by Joel-Costamagna** [bitwarden/web#47]
when I try to import my dump from passwordExporter, I have this issue: 
```
Sites[0].Password: The field Password must be a string with a maximum length of 300. Logins[0].Password: The field Password must be a string with a maximum length of 300. 
```

The export from passwordExporter is good, and importing in keepass works.

**Comment by kspearrin** [comment]
It appears that there is a login with a really long password that is breaking the import. It looks to be the very first login in the file. Can you open the file and look at the data? How long is this password?
