### ISSUE TITLE
nothing was imported message when importing Enpass CSV

### ISSUE THREAD

**Issue by jeroen7s** [bitwarden/web#48]

**Comment by kspearrin** [comment]
Can you view the console when trying it and see if there are any errors?

**Comment by jeroen7s** [comment]
![bitwardenerror](https://cloud.githubusercontent.com/assets/10954827/24096289/647672ec-0d61-11e7-8a09-86bc7c189302.png)
this is the error message that appears in the console when i try to import it

**Comment by jeroen7s** [comment]
the first row in my csv file is:
`"Title","Field","Value","Field","Value",.........,"Note"`
not sure why it says there is a quoted field that's not terminated
i do however have a few notes in the file which it mayhave an issue with?
also i have a few wifilogins in the file, which look a bit different from the rest,
and after them the file has some XML in there, maybe that's causing an issue?
looks like this:
`"Bureau-5G","SSID","Bureau-5G","Password","*********","Connection Type","ESS","Connection Mode","auto","Authentication","WPA2PSK","Encryption","AES","Use 802.1X","false","Key Type","passPhrase","Protected","false","<WLANProfile xmlns=http","//www.microsoft.com/networking/WLAN/profile/v1>","<MacRandomization xmlns=http","//www.microsoft.com/networking/WLAN/profile/v3>","//www.microsoft.com/networking/WLAN/profile/v3"""">
<enableRandomization>false</enableRandomization>
</MacRandomization>
</WLANProfile>"`

**Comment by jeroen7s** [comment]
i'll try removing the notes and XML from the file and importing it then later today, i don't really have the time to test it now
will keep you up to date if it works then or not.

**Comment by kspearrin** [comment]
Please let me know if you find the exact offender and provide an example if possible. I'd like to patch it regardless.

**Comment by jeroen7s** [comment]
i've been able to import it by deleting the wifi entries:
`"Bureau-5G","SSID","Bureau-5G","Password","1122334455","Connection Type","ESS","Connection Mode","auto","Authentication","WPA2PSK","Encryption","AES","Use 802.1X","false","Key Type","passPhrase","Protected","false","<WLANProfile xmlns=http","//www.microsoft.com/networking/WLAN/profile/v1>","<MacRandomization xmlns=http","//www.microsoft.com/networking/WLAN/profile/v3>","//www.microsoft.com/networking/WLAN/profile/v3"""">
<enableRandomization>false</enableRandomization>
</MacRandomization>
</WLANProfile>"
"TelenetWiFree","SSID","TelenetWiFree","Connection Type","ESS","Connection Mode","auto","Authentication","WPA2","Encryption","AES","Use 802.1X","true","<WLANProfile xmlns=http","//www.microsoft.com/networking/WLAN/profile/v1>","<OneX xmlns=http","//www.microsoft.com/networking/OneX/v1>","<EAPConfig><EapHostConfig xmlns=http","//www.microsoft.com/provisioning/EapHostConfig><EapMethod><Type xmlns=http://www.microsoft.com/provisioning/EapCommon>25</Type><VendorId xmlns=http://www.microsoft.com/provisioning/EapCommon>0</VendorId><VendorType xmlns=http://www.microsoft.com/provisioning/EapCommon>0</VendorType><AuthorId xmlns=http://www.microsoft.com/provisioning/EapCommon>0</AuthorId></EapMethod><Config xmlns=http://www.microsoft.com/provisioning/EapHostConfig><Eap xmlns=http://www.microsoft.com/provisioning/BaseEapConnectionPropertiesV1><Type>25</Type><EapType xmlns=http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV1><ServerValidation><DisableUserPromptForServerValidation>false</DisableUserPromptForServerValidation><ServerNames></ServerNames><TrustedRootCA>fc f0 be 34 8a 3d ef cd f2 43 f4 ca f9 80 a3 1e e2 cc 52 dd </TrustedRootCA></ServerValidation><FastReconnect>true</FastReconnect><InnerEapOptional>false</InnerEapOptional><Eap xmlns=http://www.microsoft.com/provisioning/BaseEapConnectionPropertiesV1><Type>26</Type><EapType xmlns=http://www.microsoft.com/provisioning/MsChapV2ConnectionPropertiesV1><UseWinLogonCredentials>false</UseWinLogonCredentials></EapType></Eap><EnableQuarantineChecks>false</EnableQuarantineChecks><RequireCryptoBinding>false</RequireCryptoBinding><PeapExtensions><PerformServerValidation xmlns=http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV2>true</PerformServerValidation><AcceptServerName xmlns=http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV2>true</AcceptServerName><PeapExtensionsV2 xmlns=http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV2><AllowPromptingWhenServerCANotFound xmlns=http://www.microsoft.com/provisioning/MsPeapConnectionPropertiesV3>true</AllowPromptingWhenServerCANotFound></PeapExtensionsV2></PeapExtensions></EapType></Eap></Config></EapHostConfig></EAPConfig>","<MacRandomization xmlns=http","//www.microsoft.com/networking/WLAN/profile/v3>","//www.microsoft.com/networking/WLAN/profile/v3"""">
<enableRandomization>false</enableRandomization>
</MacRandomization>
</WLANProfile>"`
now they all seem to be imported,which is awesome
3 entries in enpass had "Gebruikersnaam" en "Wachtwoord" instead of "Username" and "Password" (which are Dutch translations of Username and Password)
these are then imported by BitWarden as a note instead of in the Username and Password field.
but this is easily manually solvable

**Comment by kspearrin** [comment]
Thanks. I'll use that to try and reproduce.

**Comment by kspearrin** [comment]
@jeroen7s This is actually an issue with Enpass. That CSV that you pasted is invalid. It has the XML note broken up into several columns. Noticed the first few parts of the note:

`..."<WLANProfile xmlns=http","//www.microsoft.com/networking/WLAN/profile/v1>",...`

It is breaking it up in an invalid way which obviously doesn't import well. I would go as far to say that if you tried to import that back into Enpass itself it would not be right.

Closing as I don't see a way to resolve this without Enpass fixing their export themselves.

**Comment by jeroen7s** [comment]
so it is as i expected, it looks weird in the enpass application as well, with parts of xml code broken up, like i said in a previous comment it might be from some previous imports that got parsed incorrectly, since i have moved between multiple password managers in the past.
anyway i highly doubt many people will come across this issue. :smile:
