### ISSUE TITLE
2FA non-functional on self-hosted instance.

### ISSUE THREAD

**Issue by RyanHakurei** [bitwarden/web#486]
I know this is #190 (he never solved the issue though it just magically went away for him when he switched to a new host) but I simply cannot get my self-hosted Bitwarden instance to accept any code that Authy generates. My system is time is 100% correct, the time on the device generating the codes is 100% correct, and my Bitwarden install is completely up to date, but it claims ["invalid token"](https://i.postimg.cc/m2CcX5QT/Screenshot-at-2020-03-05-17-51-43.png) no matter what.

**Comment by enoch85** [comment]
Maybe for another issue, but suddenly my 2FA field is gone in the only place I saved it. I'm also self-hosting and now I can't access one of my backup servers. :(

I tried updating to the latest server version, but it didn't help.
