### ISSUE TITLE
Vault is empty in Firefox

### ISSUE THREAD

**Issue by motorbelly** [bitwarden/web#496]
I started using Bitwarden in Chrome and really like it so I installed it in Firefox but it won't see my vault, I log in and it says the vault is empty, not in chrome it isn't. What's up? I am using latest versions (according to firefox, 1.43.1

**Comment by kspearrin** [comment]
Are you sure you are logged into the same user account on each? Are you using a self-hosted server?

**Comment by motorbelly** [comment]
Same email and password, not self hosted. Works fine in Android but not any
Firefox, I have both Windows 10 and Linux Mint. Won't show the vault
in Firefox in either OS. It does show the folders but they are empty.

-=Lare=-

**Comment by kspearrin** [comment]
Can you open the browser dev tools and see if there are any errors listed in the console?

**Comment by motorbelly** [comment]
I have tried the dev tools but no seeing any errors. In the time since my
post the Linux Mint version began working, was there an update in the last
seven days? But in Windows 10 here are Firefox and chrome with Bitwarden
logged in the same account:
[image: image.png]

**Comment by kspearrin** [comment]
We have not made any updates this past week.

**Comment by kamilmichna** [comment]
Hello, i also use bitwarden in firefox and it works well, so maybe its version specific bug or local problem on your pc.

**Comment by sov-j** [comment]
FWIW, I use Bitwarden (version 2.15.1) in Chrome (version 84.0.4147.89) and checked opening my vault in Firefox (version 78.0.2) on Windows 8.1. It was successful in both cases.

**Comment by sarod** [comment]
Similar problem here:
Bitwarden for FF was working fine for months. But when I opened firefox 3 days agao bitwarden app lost my account email.
I logged in again but now my vault is empty in firefox. 
The data is still here when I go to vault.bitwarden.com with the same login.

FF version is 84.0.2 on windows 10
Bitwarden extension about displays Version: 1.47.1

**Comment by motorbelly** [comment]
Can't remember what I found (months ago) but it is working now. Expect it may be some browser cache issue? If you find a solution (or a cause for that matter) please post it.

**Comment by sarod** [comment]
I think I posted in the wrong project it looks like I should have posted in bitwarden/browser project as the bug I face is related to the firefox extension.

**Comment by djsmith85** [comment]
Closing this now as the original problem reported by @motorbelly was resolved and @sarod also had the issue resolved in the separate ticket.
