### ISSUE TITLE
[LastPass Import] The field notes must be a string with a maximum length of 10000

### ISSUE THREAD

**Issue by InAnimaTe** [bitwarden/web#50]
:(

![screenshot from 2017-03-23 01-40-22](https://cloud.githubusercontent.com/assets/1192726/24233917/9a2be7ee-0f6b-11e7-83df-a071106c241f.png)

![screenshot from 2017-03-23 01-53-09](https://cloud.githubusercontent.com/assets/1192726/24233921/9d9cbf7a-0f6b-11e7-9463-569e44960834.png)

**Comment by kspearrin** [comment]
It looks like you have some last pass data around entry 359 and 390 that have really long notes fields. If you edit the csv and remove or modify those notes so that they have more manageable values, save, and try again it should work.

**Comment by InAnimaTe** [comment]
Thanks. Got it to import. 

Is there any roadmap or progress already in supporting Notes as a first class citizen, or at least allowing longer notes? Not really a huge deal, just wondering if I should start modifying my notes now or wait for something to come along.

**Comment by kspearrin** [comment]
We hope to have better notes support for things like credit cards, etc by sometime this summer.
