### ISSUE TITLE
Failed to import passwords from LastPass

### ISSUE THREAD

**Issue by bharat-p** [bitwarden/web#501]
Was planning to switch from LastPass to Bitwarden and tried to import my exists secrets from Lastpass by following the instructions outlined, but ran into following error:

```
Ciphers[754].Login: The field Password exceeds the maximum encrypted value length of 1000 characters.
```

**Comment by kspearrin** [comment]
See here: https://help.bitwarden.com/article/import-data/#troubleshooting-import-errors

**Comment by bharat-p** [comment]
Thanks, sorry should have searched better before creating issue :)
