### ISSUE TITLE
Must assign a collection when sharing an entry, but is removable again in a different view

### ISSUE THREAD

**Issue by Rolfie** [bitwarden/web#502]
Hi, 

I created an item/entry from within my own vault, with as ownership the organisation and assigned the colletion 'test' to it. For this I have to choose/assign a collection upon creation. Also when editting the entry via "My Vault" -> Entry Settings -> "Collections" I cannot remove the assigned collection.

However, when I go into the organisation view, edit the item via the vault of the organisation view, I can remove the assigned collection. 

From this point onwards, the entry is no longer visible to me as manager with access rights to only this collection (actually it needs a refresh, and before that refresh it is still visible and I can still click edit). For an owner the item is now visible under a "Not assigned" collection, however, the owner of the organisation cannot assign it back to a collection, nor can he edit the item, but he can only delete the item.

I would expect the item to be assignable to a collection again, or atleast editable. And also I would expect not to be able to remove all collections from it (as manager). Please let me know if my assumptions are correct or if this is expected behaviour.

Regards,
Rolf

**Comment by Rolfie** [comment]
Nevermind on the not being able to re-assign a collection (pebuak with the owner).

The behaviour of being able to remove the assigned collections when editing the item from the organisation view is maybe weird considering that you must assign a collection when sharing in the first place. However, not sure if that is expected behaviour.

If it is expected, you can close this issue. And probably also this similar issue: #388

**Comment by kspearrin** [comment]
This would be the expected functionality. Removing all collections would place it in the "unassigned" grouping what only org owners can then re-assign back out.
