### ISSUE TITLE
Exporting and importing a .json backup causes duplicated entries/folders

### ISSUE THREAD

**Issue by anderson-** [bitwarden/web#508]
I noticed that each entry/item in the .json file have an unique uuid, so why importing the backup file causes all items in the vault to be duplicated?

The article at the help center (https://help.bitwarden.com/article/export-your-data/) clearly says that "An exported .json file can be opened, read, and modified in a simple text editor like Notepad.", but it didn't mention that it cannot be imported again, importing only the modified entries or overwriting/updating the old ones.

I had to delete all entries and manually delete every folder, and then re-import the backup file :disappointed:

**Comment by kspearrin** [comment]
This is the expected functionality. Importing the same data multiple times is not supported.
