### ISSUE TITLE
LastPass import not pulling in URIs

### ISSUE THREAD

**Issue by winniequinn** [bitwarden/web#51]
While I had no issue exporting a CSV from LastPass and importing it, all of the URI entries in my imported passwords are blank.

Looking at the CSV does not reveal anything unusual. All entries in the CSV have URL fields. Deleting secure notes before importing does not make a difference. I've also tried exporting from both Firefox and Chromium on Linux to no avail: Even a hand-made CSV with a single entry has the same issue.

**Comment by kspearrin** [comment]
@winniequinn did you select lastpass as the source when importing?

**Comment by kspearrin** [comment]
@winniequinn Good ideas. We'll make some adjustments.
