### ISSUE TITLE
Missing unification - TOTP key field

### ISSUE THREAD

**Issue by mKoonrad** [bitwarden/web#512]
It's not typical problem but small UI unification issue.

On mobile, desktop app or browser extension I need to edit login entry to see authenticator key for TOTP login.
![image](https://user-images.githubusercontent.com/11725227/78944323-e9e92600-7abd-11ea-8174-19213cc27be8.png)

On web I don't have any addition edit view. When I just open entry I can see TOTP key value. It's sensitive value so it should be hidden by default as in other Bitwarden apps. By the way in all apps this value should be hidden by default as password field.

**Comment by alexishorner** [comment]
Experiencing the same issues in Kubuntu 20.04. Tested in web vault (Firefox 84.0, private window), browser extension (Firefox 84.0) and desktop app.
