### ISSUE TITLE
Search doesn't run on IME input

### ISSUE THREAD

**Issue by no9vem** [bitwarden/web#517]
I'm Japanese and using Japanese language IME on Windows PC.

When I search entries in vault by Japanese words, search box doesn't recognize IME input and search will not run until second time input.

It looks that when box is empty search is triggered by ascii inputs only, IME input is not handled.

I tried hit enter key after IME input but happend nothing.
(I think that enter key triggers search will be the shortest workaround.)

"Microsoft IME" and "Google Japanese IME" got same results.

**Comment by Homura37** [comment]
I encountered the same problem, using IME to input any character will not trigger the search, including ascii。
