### ISSUE TITLE
Importing via pasting into textarea

### ISSUE THREAD

**Issue by ple103** [bitwarden/web#52]
Hi. It would be good if there was a secondary option that allows importing usernames/passwords via pasting into text box on the bitwarden vault. 

With this method, the user does not have to create a CSV file and then dispose of it. Because most of us know that once files have been deleted they can still be recovered (unless the file is shredded of course).

Here is a rough mockup of what I am suggesting:
![image](https://cloud.githubusercontent.com/assets/935054/24319453/f96044e6-1167-11e7-9268-77b0a6fe7692.png)

**Comment by kspearrin** [comment]
Good idea. Thanks.

**Comment by kspearrin** [comment]
Will be available in next release: https://github.com/bitwarden/web/commit/1db6d7f32b342f5efe03046f3d3b67a4dbcefc23

![image](https://cloud.githubusercontent.com/assets/1190944/24487375/15d1e800-14dd-11e7-9221-808f2d88a367.png)

**Comment by ple103** [comment]
Nice work :)
