### ISSUE TITLE
Can't delete URI

### ISSUE THREAD

**Issue by Chartman123** [bitwarden/web#531]
When I edit a password in the web vault, I can't delete URIs I don't need anymore.

![grafik](https://user-images.githubusercontent.com/16020496/82070092-895c9280-96d4-11ea-9ac3-3431e2a05e00.png)

**Comment by kspearrin** [comment]
You don't see the remove button on the right? 
![image](https://user-images.githubusercontent.com/1190944/82089960-9cfefd80-96c2-11ea-9998-e45d9733e45d.png)

**Comment by Chartman123** [comment]
Nope, only the buttons in the screenshot. Perhaps a problem with the localization?

**Comment by MattTheDev** [comment]
@Chartman123 Looking at this issue - does it persist? Using Chrome, I see the following:

![image](https://user-images.githubusercontent.com/7233525/91579419-31f3d280-e911-11ea-9fc6-df21508f23b9.png)

Can you verify this is still an issue for you? If it is - can you post what browser/version you're using?

**Comment by Chartman123** [comment]
@MattTheDev Yes, still the same way, latest Firefox 80.0:

![grafik](https://user-images.githubusercontent.com/16020496/91583243-32ac5900-e951-11ea-8db9-71b7bf5546cb.png)
