### ISSUE TITLE
Missing localization strings

### ISSUE THREAD

**Issue by mKoonrad** [bitwarden/web#536]
In Bitwarden web 2.14.0 I can see few missing strings (some from other web repository files, some from server repository.). I can't find these strings in messages.json files so in all languages texts won't be translated.

From web repository:
https://github.com/bitwarden/web/blob/3358846d41e82660d969bfcfe068cb1e56bf6e7e/src/connectors/u2f.js#L23
https://github.com/bitwarden/web/blob/3358846d41e82660d969bfcfe068cb1e56bf6e7e/src/connectors/u2f.js#L29
https://github.com/bitwarden/web/blob/3358846d41e82660d969bfcfe068cb1e56bf6e7e/src/connectors/u2f.js#L35
https://github.com/bitwarden/web/blob/3358846d41e82660d969bfcfe068cb1e56bf6e7e/src/connectors/u2f.js#L46
https://github.com/bitwarden/web/blob/3358846d41e82660d969bfcfe068cb1e56bf6e7e/src/connectors/u2f.js#L56
https://github.com/bitwarden/web/blob/3358846d41e82660d969bfcfe068cb1e56bf6e7e/src/connectors/u2f.js#L61
https://github.com/bitwarden/web/blob/3358846d41e82660d969bfcfe068cb1e56bf6e7e/src/connectors/u2f.js#L77

From server repository:
In most cases these are error messages like this:
![image](https://user-images.githubusercontent.com/11725227/82480668-6a933d00-9ad4-11ea-8f64-3938f02af3c9.png)

`Invalid password.` (probably this [file](https://github.com/bitwarden/server/blob/0cd90be83a506924f0064b9f9a396fddfe84b6bb/src/Api/Controllers/TwoFactorController.cs#L381
))
`Username or password is incorrect. Try again.` (probably this [file](https://github.com/bitwarden/server/blob/04224362875f87852b2f2fc9fa3d2bb42677716a/src/Core/IdentityServer/ResourceOwnerPasswordValidator.cs#L234))

I can't find all text because I don't know server repository well. Files could also contain other message errors.

**Comment by kspearrin** [comment]
Error messages generated by the server do not support localization at this time.

**Comment by mKoonrad** [comment]
Bad news. For users it looks like missing translation. Please consider improving it. What about u2f.js file?

**Comment by kspearrin** [comment]
It’s on our todo list
