### ISSUE TITLE
Warning in Developer Tools window

### ISSUE THREAD

**Issue by trparky** [bitwarden/web#549]
I noticed this warning in the Microsoft (Chrome) Edge Developer Tools window.

A cookie associated with a cross-site resource at https://bitwarden.net/ was set without the `SameSite` attribute. A future release of Microsoft Edge will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by MattTheDev** [comment]
This may have been resolved in a release between when you reported it and now - unable to see this warning now. Can you re-test and verify for me?

**Comment by djsmith85** [comment]
Hi @trparky, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
