### ISSUE TITLE
[Usability] Collections tab - External ID should be explained better / link to Collections

### ISSUE THREAD

**Issue by wkoszek** [bitwarden/web#551]
I have an "Team" plan with my organization "Segmed". I got to Segmed -> Manage -> Collections.

I click the collections, and I get:

```
Name: (Ok, I get that)
External ID: 
(The external id can be used as a reference or to link this resource to an external system such as a user directory)
```

No idea what that means. We probably need a link to more documentation on this. Also, I clicked "collections" to see a collection. Unfortunately I can't do it from here. 

What I miss here is actually an ability to see a collection (without going back to my Vault).

**Comment by kspearrin** [comment]
External ID is just a non-encrypted, user-defined string value that you can use to reference the collection in the API or some other external system.

**Comment by wkoszek** [comment]
@kspearrin Your sentence ^^^ could probably put in the web UI instead of that's there now. It's much clearer. BTW, I've never seen External IDs in the web UI for other products. Maybe it could be hidden completely from here. If one needs ID, the name of the collection should be enough?

**Comment by kspearrin** [comment]
The name of the collection is encrypted, so when dealing with the entity in the API, you cannot use that for reference.
