### ISSUE TITLE
Not able to open vault in  localhost (login issue) 

### ISSUE THREAD

**Issue by beverlyhillz** [bitwarden/web#553]
Related to:
https://github.com/bitwarden/web/issues/462#issue-566829054
I cloned this repository and tried to run it on local host but the login page opens and after tying in the email id a popup appears which says failed to fetch resource. I don't understand how to get past that login page on local host. I also tried changing the api end points but i don't understand it very much. 
Any help is appreciated

**Comment by kspearrin** [comment]
You need to have a running server for the web vault to talk to. See https://github.com/bitwarden/web#run-the-app

**Comment by madhanhere** [comment]
@beverlyhillz

If you don't have a running server then you can point out to bitwarden qa or prod servers.

For prod server: `npm run build:prod:watch`

For QA server: `npm run build:qa:watch`

**Comment by djsmith85** [comment]
Hi @beverlyhillz , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
