### ISSUE TITLE
Self-Hosted Server Non-Standard HTTPS Port Not Included in Verification Mail Link

### ISSUE THREAD

**Issue by tahyonline** [bitwarden/web#555]
Hello,

I have a fresh install of the self-hosted bitwarden server with non-standard ports.

The link in the verification e-mail does not reflect the non-standard https port, so clicking on the link times out in the users' browsers (443 is not open).

It looks something like this: https://my.bitwarden.hostname.com/#/verify-email?userId=...

The expected behaviour would be that the non-standard https port is included in the verification link URL: https://my.bitwarden.hostname.com:1234/#/verify-email?userId=...

Your help in this would be much appreciated.

The work around is to click on or copy the URL from the e-mail and then manually add the port to the URL in the address bar. The verification then gets processed and the email address is verified. 

Kind regards,
Thomas

**Comment by kspearrin** [comment]
Make sure your base Urls are set appropriately under environment variables.

**Comment by tahyonline** [comment]
Hello @kspearrin,

Going through the installation based on the documentation only config.yml is mentioned in the context of non-standard ports.

Given there are specific setting for the ports, the instinct is not to set in other places as that may create conflicts - and the system seemingly works if only the http_port and https_port are set.

Does the https port need to be added to the url setting in config.yml as well as all six lines (*baseServiceUri*, *attachment__baseUrl*) in  global.override.env?

Kind regards,
Thomas

**Comment by kspearrin** [comment]
> Does the https port need to be added to the url setting in config.yml as well as all six lines (baseServiceUri, attachment__baseUrl) in global.override.env?

Yes, I believe so since these are the URLs used for email link generation.
