### ISSUE TITLE
Self-hosted Server disableUserRegistration Ignored

### ISSUE THREAD

**Issue by tahyonline** [bitwarden/web#556]
Hello,

Fresh install of self-hosted bitwarden server. Successfully registered a new user and then set globalSettings__disableUserRegistration=true in bwdata/env/global.override.env 

The create new user button still appears on the login screen and the registration process is till active.

Have tried
./bitwarden.sh rebuild
and
./bitwarden.sh update
then start / restart the instance, but no change, new users can stillr register.

Your help would be much appreciated in this.

I did not find a work-around for the problem other than shutting down the instance to prevent new registrations.

Kind regards,
Thomas

**Comment by kspearrin** [comment]
The UI option will not go away, but you should get an error when trying to register.

**Comment by tahyonline** [comment]
Thank you @kspearrin 

Indeed the process fails at the submission phase with the error that registrations have been disabled.

Perhaps a feature request, then, to disable the button and registration page as well. It seems to be additional functionality active and therefore a bit more exposure.

Kind regards,
Thomas
