### ISSUE TITLE
PassKeep CSV Import

### ISSUE THREAD

**Issue by jerryn70** [bitwarden/web#56]
As you requested here is the sample CSV 

[sampleCSV_21-04-17_205019.zip](https://github.com/bitwarden/web/files/947540/sampleCSV_21-04-17_205019.zip)

PassKeep : https://play.google.com/store/apps/details?id=eu.wedgess.passkeep

**Comment by kspearrin** [comment]
Thanks. A couple questions:

- Do you know what the password2 column is for?
- Does the description column map to bitwarden notes?
- Can you provide a description with multiple lines in it?
- Does category map to bitwarden folders?
- Can you provide one that something in the APK column?

**Comment by jerryn70** [comment]
1, I Don't know what password 2 is . Maybe 1 is for master password and 2 is for pin.
2. Yes
3. Provided in attachment below.
4. Yes
5. See attachment

[Sample2_22-04-17_094043.zip](https://github.com/bitwarden/web/files/948706/Sample2_22-04-17_094043.zip)

**Comment by kspearrin** [comment]
Thanks

**Comment by kspearrin** [comment]
Done. Will be available soon.

https://github.com/bitwarden/web/commit/9918e903b2ce1a74a11efcb95ec33d58420ffcce
