### ISSUE TITLE
Verification mail error message

### ISSUE THREAD

**Issue by Thefreebee** [bitwarden/web#566]
## Describe the Bug

Not receving verification mail and getting error message "An unhandled server error as occured"

## Steps To Reproduce

Login to your vault: 

1. Go to 'https://vault.bitwarden.com'
2. Click on 'Send Email'

## Expected Result

Receive the verification mail

## Actual Result

Nothing is received and i get the error message trying more than once gives another error to wait 60 mins.

## Environment

- Operating system: [Windows 10]
- Browser: [Firefox]
- Build Version (Bottom of the page): [2.13.0]

## Additional Context

Tried Firefox and chrome browsers i get the same error

**Comment by kspearrin** [comment]
Go to settings and look at your email address. Is it valid?

**Comment by Thefreebee** [comment]
> 
> 
> Go to settings and look at your email address. Is it valid?

**Comment by Thefreebee** [comment]
it's a gmail account not sure what do you mean by valid ?

**Comment by Thefreebee** [comment]
> 
> 
> Go to settings and look at your email address. Is it valid?

Yup you were right there was 2 dots in my address so it wasn't valid didn't notice it but didn't think i could make the account with non valid address
