### ISSUE TITLE
[Security][UX] Password hint field on sign up too close to password field

### ISSUE THREAD

**Issue by mcfedr** [bitwarden/web#567]
## Describe the Bug

I was doing some maintenance on my self hosted Bitwarden instance, and whilst looking in the `User` table, I noticed quite a few `MasterPasswordHint`s that look suspiciously like a password, and on further inspect, turn out to be the actual password of the user.

## Steps To Reproduce

Hard to say exactly, I wonder if the non-english speaking nature of my users has an effect on this, but clearly something in the UX isn't making it clear what should be in that box

## Expected Result

Hint, should be a hint, not the password.

I'm thinking some validation that this isnt the case is required.

I would question how helpful the hint really is...

## Actual Result

Hint contains the users password.

## Screenshots or Videos

<img width="512" alt="Screenshot 2020-07-03 at 3 49 50 pm" src="https://user-images.githubusercontent.com/704356/86470933-17eca800-bd45-11ea-9c99-c65e90354dba.png">

## Environment

- Build Version: [2.15.1] - but most of these users have signed up before this.

**Comment by cwille97** [comment]
I'm going to work on a fix for this tomorrow that will reject any hints that are the same as the password since that isn't very secure.

**Comment by djsmith85** [comment]
This issue can be closed. The initial PR #685 was closed due to another PR for the jslib component https://github.com/bitwarden/jslib/pull/194
