### ISSUE TITLE
Domain rules not clear

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/web#57]
> Only "base" domains are allowed. Do not enter subdomains. For example, enter "google.com" instead of "www.google.com".
> You can also enter "androidapp://package.name" to associate an android app with other website domains. 

Here is the guide in the web vault. However here is my experience with the Android app of my bank (Fortuneo). The same applies for Protonmail website/Android app.

**URI**: https://mabanque.fortuneo.fr/......
**Android package name**: com.fortuneo.android

The domain rule that really works is **fortuneo.fr, fortuneo.android, **
If I set **androidapp://com.fortuneo.android** (androidapp://package.name) instead of **fortuneo.android** then it doesn't work. It doesn't work either if I set **androidapp://fortuneo.android**

![capture](https://cloud.githubusercontent.com/assets/5938828/25530731/98a0f012-2c27-11e7-93bb-666707fb7ee5.PNG)

**Comment by kspearrin** [comment]
androidapp://com.fortuneo.android should be what is used. Sounds like a bug in the mobile app. I'll have a look.

**Comment by kspearrin** [comment]
This was an Android bug. Fixed in next release.

**Comment by kspearrin** [comment]
@Primokorn You can try the new beta build on the Play store that has this fix in place: https://play.google.com/store/apps/details?id=com.x8bit.bitwarden

**Comment by Primokorn** [comment]
It works as expected now.
