### ISSUE TITLE
2FA Enterprise Policy does not remove users that do not have 2FA enabled

### ISSUE THREAD

**Issue by lschober-bw** [bitwarden/web#573]
## Describe the Bug

Per the second bullet point of the [Two-Step Login Enterprise Policy article](https://bitwarden.com/help/article/policies/#setting-the-policy), if the policy is enabled while users are part of the Organization and they do not have 2FA active, they will be removed from the Organization and receive an email notifying them.

Currently, when enabling the policy, users without active 2FA are not removed from the Organization and they do not receive an email. An Admin must manually remove the users.

## Steps To Reproduce

From an Enterprise Organization with confirmed users that _do not_ have 2FA active:

1. Go to Manage > Policies > Two-Step Login
2. Enable the policy

## Expected Result

Any user without 2FA enabled is removed from the Organization and they will be notified via email.

## Actual Result

Users remain as part of the Organization with access to assigned items. 2FA is not required when logging in.

## Environment

- Web Vault Build Version: [2.15.1]

**Comment by addisonbeck** [comment]
@lschober-bw I'm actually not able to recreate this as the issue describes. Can you check this gif out and let me know if I'm missing any steps here?

![2FAPolicyBug](https://user-images.githubusercontent.com/15897251/87597334-3f356480-c6b7-11ea-8378-f86915b3bc41.gif)

**Comment by lschober-bw** [comment]
I just went through the process again and it worked as expected. Not sure why it didn't work when I tested it. Nothing to see here!
