### ISSUE TITLE
TOTP secret is not placed in the correct field when importing from KeePass 2.x XML file

### ISSUE THREAD

**Issue by belidzs** [bitwarden/web#579]
## Describe the Bug

When I try to import a KeePass 2.x xml, file the TOTP secrets located in the protected `otp` fields are imported as extra fields instead of TOTP secrets.

```xml
<String>
  <Key>otp</Key>
  <Value ProtectInMemory="True">key=ABCDABCDABCDABCD</Value>
</String>
```

## Steps To Reproduce

1. Create a KeePass2 database with KeePass 2.45 and KeeOTP 1.3.9
2. Create an entry with dummy data
3. Right click on the item, click `Copy TOTP`
4. "Must configure TOTP on this entry..."
5. Click yes
6. Use `abcdabcdabcdabcd` as the secret
7. Export the database as KeePass2 XML
8. Import this XML file into a bitwarden vault

## Expected Result

The otp secret should end up in the `Authenticator Key (TOTP)` field of the entry

## Actual Result

It is added as a custom field with the name `otp` instead

## Environment

- Operating system: Windows 10
- Browser: Firefox 78.0.2
- Build Version (Bottom of the page): [2.15.1]

## Additional Context

The frontend is running against a bitwarden_rs instance.

I'm reporting this issue here because I think both implementation uses the exact same web frontend so this bug is probably affecting everyone. Sorry if I'm wrong and please feel free to close this ticket if invalid.

**Comment by kspearrin** [comment]
Hi. Could you please provide a complete example of the XML for a keepass export with a totp secret?

**Comment by belidzs** [comment]
I've attached the requested test files to this ticket (the kdbx file with master password `a` and the exported database in XML).

You'll find the TOTP-configured entry at `root / Sample Entry`. The secret is in a memory protected field called `otp`

[Downloads.zip](https://github.com/bitwarden/web/files/4941491/Downloads.zip)
