### ISSUE TITLE
import from firefox results in empty fields

### ISSUE THREAD

**Issue by basedtho** [bitwarden/web#586]
## Describe the Bug

when i import from firefox i only see passwords and usernames (and -- instead of urls), nothing else 
## Steps To Reproduce

1. export passwords from firefox into a csv file
2. select firefox (csv) in bitwarden
3. import data

## Screenshots or Videos

https://i.imgur.com/OU8yMuy.png

## Environment

- Operating system: linux
- Browser: firefox 81.0a1
- Build Version (Bottom of the page): [2.13.0]

**Comment by basedtho** [comment]
oh i just noticed this
![image](https://user-images.githubusercontent.com/60894565/88780488-e9919b00-d13f-11ea-917a-c8e406e50584.png)

firefox nightly now has a built in password exporter!

**Comment by Greenderella** [comment]
That .csv import was done with the built-in password exporter from Firefox Nightly?

If that is the case it is possible that we need to update our custom importer to support the format from Firefox Nightly. If you want, you can send us a dummy/example file of the export file and we can check it. It may take a little while for us to make the change so in the meantime, if you would like to import your information right away, you can open your export file in a text editor or spreadsheet application and make a few adjustments to meet our Generic CSV Format which can be seen here: https://help.bitwarden.com/article/import-data/#generic-csv-format-individual-account

You can also generate a dummy export file (JSON, CSV) from Bitwarden to use as a template. If you make multiple import attempts until you get it how you like then you may want to use the Purge Vault option to clear your vault before doing another import. This will keep you from having duplicates or anything like that. The option can be found by logging into the Web Vault (https://vault.bitwarden.com/) and going to Settings > My Account > Danger Zone > Purge Vault.

**Comment by basedtho** [comment]
okay here it is, the header

"url","username","password","httpRealm","formActionOrigin","guid","timeCreated","timeLastUsed","timePasswordChanged"

**Comment by kspearrin** [comment]
This is supported in next web vault version.
