### ISSUE TITLE
[Feature request] Auto-fill if only one password available

### ISSUE THREAD

**Issue by Primokorn** [bitwarden/web#59]
Hi,
On many websites I only have one login and one password so i wouldn't need to open bitwarden's popup to select my credentials.
It would be better to auto-fill the web page if this situation. Then we are able to just validate and enter in our account or don't validate them and browse the website as a regular visitor.

Thank you.

**Comment by kspearrin** [comment]
I think you are referring to this? https://github.com/bitwarden/browser/issues/75

**Comment by Primokorn** [comment]
Exactly.
