### ISSUE TITLE
Importing logins from Firefox not saving URI

### ISSUE THREAD

**Issue by Osrepnay** [bitwarden/web#591]
## Describe the Bug

Importing passwords from Firefox not adding domain

## Steps To Reproduce

1. Save a password in Firefox
2. Export passwords into csv file
3. Import the csv in Bitwarden's Web Vault

## Expected Result

Each of the logins should have the domain added to the URI section of the login.

## Actual Result

The URI section is blank.

## Environment

- Operating system: Ubuntu 18.04
- Browser: Firefox 79
- Build Version (Bottom of the page): 2.15.1

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/web/issues/586
