### ISSUE TITLE
Passwords that share an ip as a url, display all passwords for that url, regardless of port.

### ISSUE THREAD

**Issue by Darkwolf1515** [bitwarden/web#597]
## Describe the Bug

1. Have multiple passwords with ip as a url, each with a different port specified.
2. Open any page in your browser that uses that server
3. Watch as all the websites that use that url show up.
## Expected Result

 Only the current password that matches the port to show up

## Actual Result

 All of them show up

## Screenshots or Videos

 
![image](https://user-images.githubusercontent.com/65789901/89753827-43dc1580-dac9-11ea-95ee-5e4a44d4e24b.png)

## Environment

- Operating system Windows 10, Ios
- Browser: [e.g. Firefox 73.0.1]

**Comment by kspearrin** [comment]
You need to use host matching. See https://bitwarden.com/help/article/uri-match-detection/
