### ISSUE TITLE
Collection User list shows all users

### ISSUE THREAD

**Issue by RobBrazier** [bitwarden/web#60]
I was trying out the new organisation collection feature in the browser, and noticed something slightly disconcerting - when you try to add a user to a collection, the list of users seems to show all users that have created (or are in) an organisation.

I would have thought that the only users you would be able to select are the ones that are in the organisation.

![screenshot_20170504-084018](https://cloud.githubusercontent.com/assets/2453018/25694841/82447764-30a8-11e7-9bc9-d557c62e28f4.png)
![screenshot_20170504-084028](https://cloud.githubusercontent.com/assets/2453018/25694840/824457de-30a8-11e7-800d-bb63cf483f5b.png)

**Comment by RobBrazier** [comment]
My users are numbers 2 and 8 in the list, so there are quite a lot more than there should be.

Also, most of the users come up as admin/owner

**Comment by kspearrin** [comment]
Thanks Rob. This has been patched.
