### ISSUE TITLE
Unable to pay for premium account

### ISSUE THREAD

**Issue by werunom** [bitwarden/web#603]
## Describe the Bug

In the `Go Premium` page, when I fill the credit-card information and hit on `submit`, I get the following error message:

```
You passed an empty string for 'payment_method_data[referrer]'. We assume empty values are an attempt to unset a parameter; however 'payment_method_data[referrer]' cannot be unset. You should remove 'payment_method_data[referrer]' from your request or supply a non-empty value.
```

## Screenshots

![Screenshot_20200813_160441](https://user-images.githubusercontent.com/24664855/90124931-c8a38980-dd7e-11ea-84b5-097dfdeafd52.png)

## Environment

- Operating system: Linux Manjaro
- Browser: Firefox 79
- Build Version (Bottom of the page): 2.15.1

## Additional Context

Tried even with adblock disabled and Firefox Enhanced Tracking Protection off. No luck.

**Comment by cscharf** [comment]
Hi @werunom , can you please clarify any of the following scenarios for us?

1. You have Fingerprinting Protection enabled in Firefox (from `about:config`)
2. You have a privacy plugin like Privacy Badger, etc. installed and enabled
3. You have `network.http.sendRefererHeader` in `about:config` set to `0` (_Disable referrer_)

If so, at least for the duration of the checkout process, please change, enable referrer or disable privacy guards for the time being during checkout.

**Comment by werunom** [comment]
@cscharf, as I stated initially, I tried disabling `ublock` and Firefox's `Enhanced Tracking Protection` and still saw the same error. 

Anyways, after you suggested, I tried the same in `private` window and was able to successfully upgrade to premium. So, looks the payment process is being impeded by some addon or browswer option. 

To specifically answer your queries,

1. As I said, I had disabled firefox protection
![Screenshot_20200813_201210](https://user-images.githubusercontent.com/24664855/90149693-6ceaf780-dda2-11ea-947c-d1f5c0e54d98.png)

2. I disabled `ublock` also; but this was not helpful. 

3. When I looked up for `network.http.sendRefererHeader`, the value was `2`

Anyways, not sure how further I can help you with the debugging given that the payment went through fine :)

PS --- I have one more addon - Decentraleyes. Couldnt test with switching this off. Sorry for that.

**Comment by cscharf** [comment]
Thank you for the follow up and additional information! I'll go ahead and close this since you were able to do this and from what I've seen Stripe (our payment gateway/API) has a tendency to throw a tantrum when the Referrer header is not included (from us to Stripe in your browser). Also, thank you for your support!

**Comment by Zeik0s** [comment]
Since i also first troubleshooted and then found this issue, can you implement a Note describing this issue?
