### ISSUE TITLE
[Usability] Collections are confusing to users

### ISSUE THREAD

**Issue by wkoszek** [bitwarden/web#615]
## Describe the Bug

We onboarded 14+ interns in the last 10 weeks, and it made us switch to BitWarden b/c of flexible pricing model (we had people join for 10 weeks or so, and they all joined at different times)

Setting up password sharing in BitWarden as it is now is very hard, and I blame collections for this. First as an admin "adam" I need to create all the collections, because it appears like just simply sharing an item with a user isn't possible [or at least I haven't found a way to do this]. This is very awkward and different than any other sharing. 

I ended up having a bunch of collections .e.g: `adam_john`, `adam_mary` etc. 14 of them.

For every new user, nobody knew what "collections" are. I had to explain it all to everyone. Also, my users had problems figuring out sharing. People know 1password and LastPass, and other programs like Google Drive, where you share item to the user, not via collection. It was a lot of explaining to do a simple thing.

## Expected Result

It'd be awesome if you could do a usability test and see if I'm alone. My take is that collections should be hidden from the users, and I shouldn't have to think about this.

**Comment by tgreer-bw** [comment]
Hi @wkoszek - thanks for the feedback! While we are always trying to improve the product, we use GitHub for errors/issues/development bugs, but we actually have a community forum for these types of requests, and specifically a thread on collections/folders:

https://community.bitwarden.com/t/reduce-confusion-around-folders/4444

We feel that password sharing via Collection is a more scalable model than tracking 1:1 user shares, however please feel free to join the conversation, and let's see what cool stuff we can come up with!

**Comment by wkoszek** [comment]
@tgreer-bw Ok, I pasted it there too.

Have you interviewed users about this? I got a reverse impression -> it's not scalable, and the sharing person is a bottleneck. First it took me a while to understand collections, and then I had to explain it many times.

Collections are OK as an implementation details for N:M item sharing. I don't like creating collections by hand or explaining them.

Possible workaround: allow me to share item with a user. This event creates a collection automatically. The left "pane" of the web changes from "Collections", to "You share items with following users: user1, user2, user3" etc. This way you get to keep some organization, but without a hassle of me -> collection -> target user.

**Comment by cscharf** [comment]
Thanks for the update and additional detail @wkoszek , I'm sure there are plenty of ways to handle sharing that would benefit many different use-cases and types of users. Please use the community forums to vote, share perspective and help us incorporate your feedback for consideration as we plan our roadmap and enhancements going forward. I certainly like the suggestion regarding a user usability study and that's something we may consider in the future before embarking on any redesign. In the meantime I'm going to close this issue, please let us know if you run into any other problems.
