### ISSUE TITLE
Can access password of read-only shared password

### ISSUE THREAD

**Issue by erwanvivien** [bitwarden/web#619]
## Describe the Bug

When on your personal vault, clicking on an use-only item (shared as uneditable) you can access password, even if the 'eye' is not clickable

## Steps To Reproduce

1. Go to 'an uneditable shared item'
2. Open 'the html editor (F12)'
3. Scroll down to 'the password field'
4. Remove 'type=password'

## Expected Result

I expect first of all the page to show like 5 '•••••' instead of the exact length password (not related to bug but still a problem)
The expected behaviour would be the password is still hidden

## Actual Result

Can access the password and paste it

## Environment

- Operating system: Windows 10
- Browser: Chrome
- Build Version (Bottom of the page): not sure

**Comment by kspearrin** [comment]
If a password is shared with someone, they can still access it, even if it is hidden from them. See warnings here: https://bitwarden.com/help/article/user-types-access-control/#access-control

**Comment by erwanvivien** [comment]
Ok my bad then

However you also can't apply a group to a read-only shared password which is a shame

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________
