### ISSUE TITLE
1pif import fails

### ISSUE THREAD

**Issue by sdr0x07b6** [bitwarden/web#620]
## Describe the Bug

After importing `.1pif` to migrate from 1Password, I got the following error.
How can you solve it?
Or is it a bug?

<img width="400" alt="import-failed" src="https://user-images.githubusercontent.com/1102138/91035476-59ad1700-e641-11ea-94cd-d9418193b39c.png">

```
エラーが発生しました。
Ciphers[110]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[157]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[204]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[365]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[510]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[628]: The field Notes exceeds the maximum encrypted value length of 10000 characters.
```

And
Written at the same time as export of `.1pif`
-`attachments/`
-`previews/`
Can not be imported?
There are many important documents related to accounts.

## Steps To Reproduce

1. Export 1pif with 1Password
2. Import into Bitwarden

I can't submit because of my actual account data

## Actual Result

All imported

## Environment

- macOS 10.14.6
- Chrome 84.0.4147.135
- https://vault.bitwarden.com/#/tools/import

**Comment by Greenderella** [comment]
Hi,

Please follow these instructions regarding this message: https://bitwarden.com/help/article/import-data/#troubleshooting-import-errors

Also in order to import attachments you will need to manually import them after acquiring a premium membership: https://bitwarden.com/help/article/attachments/
