### ISSUE TITLE
Confusing warning on Inactive 2FA Report

### ISSUE THREAD

**Issue by Fastigium** [bitwarden/web#630]
## Describe the Bug

The warning box on the Inactive 2FA Report contains a confusing sentence:

"We found $COUNT$ website(s) in your vault that may not be configured with two-factor authentication (according to twofactorauth.org)." ([source](https://github.com/bitwarden/web/blob/1b466609f01134c2e70fa1f1e5eb32ab9a0c55b2/src/locales/en/messages.json#L1355))

This sentence may be interpreted as "these sites cannot be configured with two-factor authentication", while in fact the opposite is true.

## Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/tools/inactive-two-factor-report (need to be logged in to your vault, and to have a premium account)
2. Notice the text in the warning box

## Expected Result

The text is clear and unambiguous. I would suggest the following replacement for the confusing sentence:

"We found $COUNT$ website(s) in your vault that support two-factor authentication (according to twofactorauth.org) but where your account(s) may not have it enabled."

## Actual Result

The confusing sentence, as quoted above.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/10221829/92004002-f8bcc780-ed41-11ea-928e-28df2e99e502.png)

## Environment

Any OS, any browser. Build version 2.15.1

**Comment by dmcfaddengalway** [comment]
I agree with this. The suggested line is much clearer. I would be glad to work on this, if possible.
