### ISSUE TITLE
Clicking on item should open modal in "View mode" with Edit button to make fields editable

### ISSUE THREAD

**Issue by jashsayani** [bitwarden/web#638]
## Describe the Bug
Not a "feature request" but I consider this a UX bug. Clicking on an item should open it in "View" mode to copy password. Clicking on "Edit" button should make the fields editable. Like 1Password UI.

## Steps To Reproduce
1. Go to Vault
2. Click on any password item

## Expected Result
View mode with Labels. Clicking on "Edit" button makes them text boxes.

## Actual Result
Enter edit mode on clicking on items.

**Comment by Greenderella** [comment]
Hi jashsayani,

We appreciate your feedback. This has been added to our recommendation list for consideration.

Have a nice day.

**Comment by sagearslan** [comment]
This was 1.5 years ago but any plans to implement this UX improvement?
