### ISSUE TITLE
Firefox addon does not provide correct verification codes

### ISSUE THREAD

**Issue by renaldofreire** [bitwarden/web#639]
# Describe the Bug
Suddenly, two-factor code stopped working on some services, like Evernote and GitLab. I recently did not make any changes in verification code (TOTP). In the mobile version (android) is working correctly. The problem is only occurring in the firefox addon version.

## Steps To Reproduce

1. Go to Bitwarden addon in firefox;
2. Click on Search for service;
3. Copy verification code;
4. Does not work...

## Environment

- Operating system: Arch Linux x86_64;
- Browser: Firefox 80.0.1 (64-bit);
- Firefox Addon version: 1.45.0.

**Comment by kspearrin** [comment]
Check your system time.

**Comment by renaldofreire** [comment]
I enabled automatic time and the problem was solved.
