### ISSUE TITLE
"Import Data" page gives outdated Firefox instructions

### ISSUE THREAD

**Issue by LiberalArtist** [bitwarden/web#645]
Related to https://github.com/bitwarden/help/issues/163

On the "Import Data" page, selecting "Firefox (CSV)" as the import format shows a message with instructions for using "FF Password Exporter". These are no longer needed since https://github.com/bitwarden/jslib/pull/132 has been merged.

![Screenshot](https://user-images.githubusercontent.com/10700996/92541109-23f85880-f213-11ea-90b7-e8475b630c30.png)

**Comment by n-machiavelli** [comment]
Should we redirect users to Firefox import help page (https://bitwarden.com/help/article/import-from-firefox/) just like the other formats ? Creating a PR for this.

**Comment by vachan-maker** [comment]
> 
> 
> Should we redirect users to Firefox import help page (https://bitwarden.com/help/article/import-from-firefox/) just like the other formats ? Creating a PR for this.

Done. If any more changes need to be made. Let me know. #728

**Comment by vachan-maker** [comment]
@n-machiavelli  Should I close mine?

**Comment by n-machiavelli** [comment]
I closed mine. thanks!!

**Comment by vachan-maker** [comment]
@cscharf please close this issue. Thanks
