### ISSUE TITLE
Ensure proper http security policies are used

### ISSUE THREAD

**Issue by tbolon** [bitwarden/web#65]
Try to apply recommended http security rules.

For example: https://securityheaders.io/?q=https://vault.bitwarden.com/&followRedirects=on

Credibility is important in your state.

At least, add clickjacking and xss protections (x-frame & x-xss).

**Comment by kspearrin** [comment]
CSP has been added for next release, however, it appears that the scanning tools do not pick up `<meta>` tag CSP policies, only headers, so the score won't improve. Regardless, the protection is still there.

https://github.com/bitwarden/web/blob/7ebafaf0fc2eff441bd071a56291aa14a429cf70/src/index.html#L5-L34

**Comment by kspearrin** [comment]
CSP deployed as well as sub-resource integrity checks. As I suspected, this made no different int he score since the tools are broken on that website... We should be more like a "B" now.

**Comment by kspearrin** [comment]
We now score an A+ here.
