### ISSUE TITLE
i cannot login in centbrowser，hint“token not found” 。

### ISSUE THREAD

**Issue by figojs** [bitwarden/web#657]

**Comment by Greenderella** [comment]
It sounds like maybe one of your browser configurations or possible an extension such as an ad-blocker/script-blocker is preventing some connections from being made. Could you try temporarily disabling them or reverting any network configuration changes that could cause a connection issue? 

You may also want to try to log into the Web Vault with the browser Developer Tools, open the Network tab and see if any errors arise. One of the simplest ways to test would also be to open a new web browser profile that doesn't have any extensions or custom configurations and see if you are able to log in. You can also enable the extension to work with Private or Incognito mode and test it in a private browser window.

**Comment by figojs** [comment]
Thank you for your reply, I reinstalled the browser again, the current use is back to normal.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bitwarden/web"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 晚上10:42
收件人:&nbsp;"bitwarden/web"<web@noreply.github.com&gt;;
抄送:&nbsp;"五味"<21045521@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bitwarden/web] i cannot login in centbrowser，hint“token not found” 。 (#657)





 
Closed #657.
