### ISSUE TITLE
Expand/Collapse Folder via title bar

### ISSUE THREAD

**Issue by ple103** [bitwarden/web#66]
![](http://i.imgur.com/lT4Ocy0.gif)
Collapse/expand via clicking anywhere on the folder's header bar. Since all the majority of content is on the left side of the screen, this approach is will be a lot more convenient for desktop users especially for those who use a high-res screen.
I'm not sure how much this will affect mobile browser users, but if there are issues mobile browser users can be reverted to the current method.

**Comment by ClarkeCC** [comment]
This won't be really necessary when folders get moved to the side panel. Check #72

**Comment by jpbaril** [comment]
+1
