### ISSUE TITLE
Security: The bitwarden web vault app is inherently a major security risk and should not exist.

### ISSUE THREAD

**Issue by sneak** [bitwarden/web#660]
## Describe the Bug

This app, running at `vault.bitwarden.com`, is delivered to the web browser client from Bitwarden infrastructure on each and every page load.  This permits Bitwarden staff, or anyone who can subvert that staff's access (via any means, legal or otherwise, which is Quite A Lot Of People) to serve a backdoored application which steals user keys or plaintext passwords.

## Steps To Reproduce

Load `https://vault.bitwarden.com`.

## Additional Context

The point of doing end-to-end encryption of the passwords and password manager data is so that the server doesn't see the passwords.  It's designed so that the server does not need to be trusted to keep the passwords secret.

If the application is being loaded from the server uncritically (such as what happens with `vault`, this repo), then a dishonest server can simply provide backdoored code which subverts/disables the encryption entirely.  The clientside encryption is thus unnecessary and indeed ineffective in this scenario as the server must be trusted 100% at all times to deliver safe code anyway.

This is not an issue with clientside applications or a browser extension, the code for which is served by third parties (e.g. app stores, extension stores, et c) and stored locally on the client devices.  This is, however, an unavoidable issue with all browser-based apps.

**Comment by kspearrin** [comment]
We have no plans to discontinue the web vault. It exists by user demand.
