### ISSUE TITLE
Master password shows instead of password for vault item

### ISSUE THREAD

**Issue by dcltdw** [bitwarden/web#663]
## Describe the Bug

When viewing a vault entry, master password displays is password field instead of entry's pw.

## Steps To Reproduce

Go to Reused Passwords Report.
Click on an entry.
In the entry’s popup, click on the eyeball.
Master password is displayed instead of entry’s password.

## Expected Result

Entry's pw.

## Actual Result

Master pw.

## Environment

MacOS 10.15.6
Chrome 85.0.4183.121 (Official Build) (64-bit)
BitWarden 1.46.2

**Comment by kspearrin** [comment]
Sounds like you have your browser autofill turned on and it has saved your master password. Try turning that feature off in your browser.

**Comment by dcltdw** [comment]
I believe I have Chrome password autofill disabled (but it's hard to confirm via Chrome settings).

**Comment by clayadams5226** [comment]
As mentioned above, this almost certainly sounds like an auto-fill issue with Chrome. @dcltdw were you able to get this resolved?

**Comment by dcltdw** [comment]
Repeating the steps, I no longer have this problem, so either it was a
transient issue, a Chrome autofill issue that was resolved, or something
else.
I'm guessing this ticket can probably be closed now.
Thanks to everyone for the helpful comments!

dave
