### ISSUE TITLE
Launch button next to URL in Edit screen missing icon

### ISSUE THREAD

**Issue by cscharf** [bitwarden/web#665]
## Describe the Bug

When viewing an item in the web vault, on the edit screen, the "Launch" button next to the URL is missing the Launch icon. Instead a blank button is displayed which requires inspection or hovering for some time to get the title/tool tip to display so you know what it is.

## Steps To Reproduce

1. Go to https://vault.bitwarden.com
2. Log in
3. Click on "Login" under "TYPES" heading
4. Click on any login with a URL specified

## Expected Result

The "Launch" button has an icon, similar to other clients (e.g. from desktop: 
![image](https://user-images.githubusercontent.com/3904944/94808545-49662580-03bf-11eb-8270-d2ca624f3ee8.png)).

## Actual Result

It is a blank button without an icon.

## Screenshots or Videos

(initial appearance)
![image](https://user-images.githubusercontent.com/3904944/94808810-acf05300-03bf-11eb-99f0-94e1341e3337.png)
(hover)
![image](https://user-images.githubusercontent.com/3904944/94808313-f7250480-03be-11eb-8599-ae1fd5de2913.png)

## Environment

- Bitwarden Cloud, web vault
- Operating system: macOS Catalina version 10.15.6
- Browser: Chrome, version 85.0.4183.121 (Official Build) (64-bit)
- Build Version (Bottom of the page): 2.16.1

## Additional Context

The button still works when clicked, so that's pretty awesome!

**Comment by addisonbeck** [comment]
Does this persist after a logout/login, cleared cache, and all that? Mine look fine in my production cloud vault.

<img width="466" alt="Screen Shot 2020-10-01 at 11 12 59 AM" src="https://user-images.githubusercontent.com/15897251/94828108-234c7f80-03d7-11eb-8cc8-2e1eec85bc4b.png">

**Comment by cscharf** [comment]
Yes, did all that jazz. When I inspect it I can see the CSS applied class for that button as `fa fa-lg fa-share`, but the `<i/>` element has no `::before` psuedo element applied by a selected style, whereas the copy button does:

![image](https://user-images.githubusercontent.com/3904944/94849830-02deee00-03f4-11eb-9f0e-7251695e0ae2.png)

**Comment by dario-piotrowicz** [comment]
Mine looks ok too

I tried on Ubuntu 20.04 LTS, Chomium incognito and I got the icon with the `before` pseudo element:
![Screenshot at 2021-06-08 18-04-09](https://user-images.githubusercontent.com/61631103/121228179-54ddea80-c884-11eb-8773-c330722b3836.png)

And if the URL is not valid the icon is greyed out:
![Screenshot at 2021-06-08 18-04-20](https://user-images.githubusercontent.com/61631103/121228202-5effe900-c884-11eb-9f23-c4cc9873f2f9.png)

so it would all seem pretty normal

I even tried throttling the network speed to simulate a slow connection (to see if maybe the icon can take some time to load) but nothing all seems good at my end :'(

**Comment by eliykat** [comment]
This is an old issue - @cscharf can you confirm whether this is still a current issue or whether we can close?

**Comment by cscharf** [comment]
No longer an issue, sorry for not cleaning up my old mess, thanks @eliykat !
