### ISSUE TITLE
CORS when requesting production API

### ISSUE THREAD

**Issue by andreaslarssen** [bitwarden/web#675]
## Describe the Bug

If I'm not mistaken, the readme says you can use the production API for local development. When I tried that, the first request fails (apparently) due to CORS. 

## Steps To Reproduce

Change the API endpoint in `src/app/services/services.module.ts` using `apiService.setUrls()`

## Expected Result

I expected this to fail, but the readme seems to indicate that this should work. Any pointers?

## Actual Result

```
Access to fetch at 'https://api.bitwarden.com/accounts/prelogin' from origin 'https://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
zone.js:1118

POST https://api.bitwarden.com/accounts/prelogin net::ERR_FAILED
```

## Environment

- Operating system: Ubuntu 20.04.1 LTS
- Browser: Chrome Version 86.0.4240.75 (Official Build) (64-bit)
- Build Version (Bottom of the page): 2.16.1

**Comment by kspearrin** [comment]
Browsers have made CORS more restrictive lately, so I am not sure of a way to access prod from a local endpoint anymore.

**Comment by andreaslarssen** [comment]
@kspearrin So you'll need to set up a local environment. That's a bit of a hassle. You could set up a staging / test environment that allows local hosts? In any case, the readme should probably be changed.
