### ISSUE TITLE
Unable to find some translations in Crowdin

### ISSUE THREAD

**Issue by ffes** [bitwarden/web#678]
## Describe the Bug

The Dutch translation for the role "Manager" is wrong. When I look in https://crowdin.com/project/bitwarden-browser/nl I don't see that term in the list. I searched for "manager", I scrolled through the 9 pages of translatable string, but all the terms used in the popup shows when you manager a user within a organization seem to be missing.

## Steps To Reproduce

1. Go to an organization
2. Click on "People"
3. Click on a person, a popup is opened.
3. Note that in that popup are 4 roles a person can have and a summary per role is shown.
4. Go to https://crowdin.com/project/bitwarden-browser/nl
5. Try to find any of the string you see in the popup mentioned above and notice that they are not there. They are in https://github.com/bitwarden/web/blob/master/src/locales/nl/messages.json (line 2171), but don't seem to appear on Crowdin. I checked the German translation as well and couldn't find them there either.

**Comment by cscharf** [comment]
@ffes , that is the wrong Crowdin project for the web vault, please see: https://crowdin.com/translate/bitwarden-web/58/en-nl?filter=basic&value=0#q=manager

The keys are: `manager` and `managerDesc`.

**Comment by ffes** [comment]
You are right. My bad. I will update the translation and close this one.
