### ISSUE TITLE
1Password 7 .CSV Import adding Cards and Identity items as Secure Note Items. 

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/web#679]
## Describe the Bug

Importing a 1Password 7 .csv export file through the web vault adds Credit Card and Identity items as Secure Notes.

## Steps To Reproduce

1. Open 1Password Desktop (V.7.6.785) client on Windows 10.
2. Export Credit Card and Identity items to .csv file.
3. Import that .csv file through your Bitwarden web vault.

## Expected Result

To have the Credit Card and Identity items from 1Password be added into the Bitwarden vault as Credit Card and Identity items.

## Actual Result

Credit Card and Identity items from 1Password are added as Secure Note items into the Bitwarden vault.

## Screenshots or Videos

These items:
![image](https://user-images.githubusercontent.com/73389600/97190474-a75b1280-179d-11eb-81a2-118d1989b5e0.png)

Were added as these items:
![image](https://user-images.githubusercontent.com/73389600/97190525-b8a41f00-179d-11eb-970b-bb0119ea22cf.png)

## Environment

- Operating system: Windows 10 Pro 2004 (Build 19041.572)
- Browser: Chrome 86.0.4240.111
- Build Version (Bottom of the page): 2.16.1

## Additional Context

None.

**Comment by MGibson1** [comment]
Closed by bitwarden/jslib#217

**Comment by MGibson1** [comment]
Previous closed for MAC-produced CSVs.  My mistake, Windows support is merged in on bitwarden/jslib#222
