### ISSUE TITLE
[Enhancement] Add importer for Meldium

### ISSUE THREAD

**Issue by brianredbeard** [bitwarden/web#68]
The password management system https://www.meldium.com/ was acquired by LogMeIn and will be shut down 2017-07-05, in an effort to get users to migrate to the _other_ product acquired by LogMeIn in 2015, LastPass.

Meldium allows users to export their data in a CSV format through settings page:

![image](https://cloud.githubusercontent.com/assets/57542/26172271/b17f4708-3afc-11e7-8e8d-e3e2e598f0fd.png)

Using the "Export Data" function:

![image](https://cloud.githubusercontent.com/assets/57542/26172307/c856e6ca-3afc-11e7-8271-8a818e2298d1.png)

Once the user has exported their data, it will be in a CSV file of the following format:

```
DisplayName,UserName,Password,Notes,Url
My Account,user1,p4ssw0rd,,https://example.com
Flickr,jane@example.com,"stuff""@nthings",Random Account,https://flickr.com
Zapper,user+zap@example.com,zappass,Used for automation,https://zapier.com
```

For the corresponding data:

```
DisplayName	UserName	        Password	Notes	                Url
My Account	user1	                p4ssw0rd		                https://example.com
Flickr	        jane@example.com	stuff"@nthings	Random Account	        https://flickr.com
Zapper	        user+zap@example.com	zappass	        Used for automation	https://zapier.com
```

**Comment by kspearrin** [comment]
a few questions:

1. How are new lines exported for notes? Does it keep the proper new lines there or does it substitute a string of some sort (for example, some exports have the actual string `\n` that I then will replace with proper new line)?
2. What data is optional vs required?

=
