### ISSUE TITLE
Cookies are not sent when application is cached

### ISSUE THREAD

**Issue by AdamVB** [bitwarden/web#683]
## Describe the Bug

So the title might not be the most descriptive so I will try to explain it here:

We run a self-hosted Instance of Bitwarden behind an Apache Reverseproxy.

This Apache Reverseproxy acts as sort of Enterprise 2FA Solution. It asks for a Certificate/Password etc.. before you are allowed to access bitwarden itself.

The Reversproxy also issues a cookie for *.domain.com, which means the client is allowed through the Reverseproxy without any further prompts. 

Now when accessing Bitwarden after this cookie has expired (8h), it makes the bitwarden web app load (cached) before the 2FA prompt appears in the browser. Normally you get a white page with the browser prompting for smartcard. 
In this case you get the bitwarden login page with the smartcard prompt on top. 

What happens now is that the 2FA cookie for *.domain.com is issued, but the Bitwarden webapp doesn't send it when making a request.

## Steps To Reproduce

Run a reversproxy in front of Bitwarden that issues a cookie for site access

## Expected Result

Bitwarden Web App should look for cookies before making a request and send them with the request

## Actual Result

Bitwarden Web App only looks for cookies on page load and does not check again when making requests.

## Environment

- Operating system: Debian 10 (server) Windows 10 (client)
- Browser: Chrome 84.0.4147.89 
- Build Version (Bottom of the page): 2.16.1

## Additional Context

This looks very similar to this stackoverflow question:

https://stackoverflow.com/questions/59616290/angular-httpclient-does-not-send-domain-cookie

**Comment by cscharf** [comment]
Hi @AdamVB ,

We should be setting these credentials accordingly, as the server explicitly does send the following headers in responses:

```
access-control-allow-credentials: true
access-control-allow-origin: <domain.com>
```

Further, from the client-side we are setting the `credentials` portion of the `Request` when building the request in Angular with `'include'` when not Safari's Browser Extension and either not a web client (i.e. Desktop, browser extension) OR you're using the Base URL to control access to the environment, which our default self-hosted instance _should_ be. See: https://github.com/bitwarden/jslib/blob/master/src/services/api.service.ts#L1232

This sounds more perhaps cookie access is missed from the cached page, so subsequent requests are missing that value in the request header or something else going on that's blocking the cookie submission, likely from a CORS perspective or browser security perspective, not quite sure.

Can you use the browser's Dev Tools to perform some discovery on that subsequent request for smart card/2FA auth, and/or the request/responses leading up to that (proper redacted) to we can get some visibility into what headers/cookies are being sent. Feel free to send this directly via email to our customer success team (vs. posting here).

**Comment by AdamVB** [comment]
Hi @cscharf 

when the application already loaded in the background of the smartcard prompt and I then try to login into the bitwarden UI this is what is being sent:




![grafik](https://user-images.githubusercontent.com/15871966/100218917-a42a8200-2f15-11eb-942f-3043786e311b.png)



When refreshing the page (making the cookie stick) then it's being sent in the request header and login works fine:

![grafik](https://user-images.githubusercontent.com/15871966/100219061-d2a85d00-2f15-11eb-8f72-22a18a9d4c13.png)


I've sent a video of whats happening to Luc from your Support Team as well, if you have seen that already.

To clarify any configuration errors on the Base URL.



Our Setup looks like this:

`bitwarden.domain.com ` is the external URL, it points to the reverseproxies. This is also set as Base URL inside the Bitwarden config.



The Apache Reverseproxies use an internal domain name to access bitwarden:

`ProxyPass https://bitwarden.domain.internal/`

**Comment by cscharf** [comment]
Awesome, thank you for the detail, will look into this further today and will circle around with Luc as well.

**Comment by AdamVB** [comment]
I just realised something,

chrome does not seem to be aware of the pubtkt cookie, even though it has been received:

![grafik](https://user-images.githubusercontent.com/15871966/100223630-0c7c6200-2f1c-11eb-86fb-336d87ed813c.png)

hitting refresh here does not seem to help

Only when refreshing via f5 or the button on the top left the cookies appear:

![grafik](https://user-images.githubusercontent.com/15871966/100223775-39c91000-2f1c-11eb-922d-7046ea63cd0a.png)

**Comment by AdamVB** [comment]
Some more insight:

when the client does not send a pubtkt cookie, the reversproxy will redirect them to `sso.tsi-vc.otc-service.com/login`


in this redirect the 

```
access-control-allow-credentials: true
access-control-allow-origin: <domain.com>
```

headers are not sent in the response.


For testing I have added them in the site config for `sso.tsi-vc.otc-service.com/login`
```
        Header set Access-Control-Allow-Origin "*"
        Header set Access-Control-Allow-Credentials "true"
```

Now the SmartCard prompt actually comes when hitting the "login" button on the bitwarden UI


but we get a different error:


´´´
Access to fetch at 'https://sso.tsi-vc.otc-service.com/login?back=https%3a%2f%2fbitwarden.tsi-vc.otc-service.com%2fapi%2fsync%3fexcludeDomains%3dtrue' (redirected from 'https://bitwarden.tsi-vc.otc-service.com/api/sync?excludeDomains=true') from origin 'https://bitwarden.tsi-vc.otc-service.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
´´´

**Comment by cscharf** [comment]
Can you also add in the site config and see if that alleviates the issue?:
```
Header set Access-Control-Allow-Headers "Cookie"
```

**Comment by cscharf** [comment]
Also found this: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSExternalRedirectNotAllowed

**Comment by AdamVB** [comment]
> Can you also add in the site config and see if that alleviates the issue?:
> 
> ```
> Header set Access-Control-Allow-Headers "Cookie"
> ```

I've tried this, but that doesn't alleviate the issue.


I think setting 

```
    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Credentials "true"
```

Helped to some extent, as we now get CORS preflight error message.


On our reverseproxy, every unauthenticated request is redirected to the sso site. And this /api/prelogin OPTION request fails because of that.


Is there a way that we can follow that redirect before the application itself loads in chrome?

**Comment by cscharf** [comment]
🤔 , I'm not sure, but from the initial OPTION request, could the `SameSite` not being set on those cookies influence whether they're included in that request? I see them legitimately missing in your screen shot from the application storage which would lead me to believe the browser is ignoring them on the first request because `SameSite` is not set and therefore is using `Strict` by default.

**Comment by AdamVB** [comment]
So i tried setting SameSite on the cookie, but that didn't help, I think because the cookie actually isn't there after the request has been made.


I have explored the cache angle again and set

```
Header always set Cache-Control "must-revalidate"
```
on the Reverseproxy for the Bitwarden Site



This makes Chrome contact the server before accessing the cache, thus redirecting the user to the SSO Page, getting the cookie and only after all that, loading the Application from cache.

So far it seems to work very well without problems.

Can you think of any caveats or disadvantages that we might encounter when doing it like this?

**Comment by cscharf** [comment]
Thanks for the update @AdamVB !

> Can you think of any caveats or disadvantages that we might encounter when doing it like this?

It depends if that is set for each request or just for that given endpoint and also depends on what the expiry is set for the other cache control header(s), if any. If you're not seeing performance issues then I can't think of any drawbacks to this approach. I'll circle around with some of the other folks on the team to see if there's any collective evidence or thoughts around this to the contrary.

**Comment by AdamVB** [comment]
Closing this issue. Our team didn't see any performance issues and our problems are fully gone.

Thanks for the support!
