### ISSUE TITLE
Reports old "Exposed passwords"

### ISSUE THREAD

**Issue by sichkarmg** [bitwarden/web#690]
## Describe the Bug
The report of exposed passwords still shows me passwords that have been changed.
Is the old passwords stored i db for the "updated password counter"?
And if so, is the report generator including these passwords when generating the report?
Or am i missing some "purge" function that "cleans" the database from old changed passwords?

## Steps To Reproduce
When in my web vault, running the tools/report exposed passwords, the report shows me password entries with old (exposed) passwords.
When i click them in the report it shows the old password, and if i click the entry in the vault i see the new changed password (changed 2 month ago)

## Expected Result
The report should not generate warnings on passwords that have been changed in the vault.
**Im guessing the old passwords are still stored somewhere and the report generator can still find these old passwords and keeps warning me about them.**
I cant see the old password anywhere in the web vault, but if i use search and type in my old exposed password i get a list of entries that have had that password before i changed them, but i cant see that old password when i open the items from the list

## Actual Result
The report of exposed passwords still shows me passwords that have been changed.

 ## Environment
-  Chrome/86.0.4240.101 
- Bitwarden version 2.16.1

## Additional Context
Self server

**Comment by cscharf** [comment]
This will be resolved with PR #700 , where this issue is duplicated by #699 .
