### ISSUE TITLE
Leaving an Organisation after it is deleted

### ISSUE THREAD

**Issue by iain-id** [bitwarden/web#70]
Hi,

I created an account and a free organisation to have a look at the product.  When I was ready to start a formal trial in the company I deleted the Organisation and was planning to re-create the organisation with a Team licence.  I am now left with an interesting problem.

On the left menu it says "You do not belong to any organizations."  But when I look in Settings the Organisation I created is still listed.  Clicking the Leave option returns the "Unable to leave this organization" error.

Just to test I tried to create a new free organisation and get the error
"Errors have occurred
You can only be an admin of one free organization."

I was able to create a new Team licence organisation.

**Comment by kspearrin** [comment]
duplicate with https://github.com/bitwarden/web/issues/71
