### ISSUE TITLE
Unable to Download Mac version from App Store

### ISSUE THREAD

**Issue by mosidevv** [bitwarden/web#711]
Hey Team,

This is my first reported issue so I hope there isn't some protocol that I'm breaking by not using the right format or template as I've seen in other repos around here. 

I wanted to make the team aware that I am experiencing an issue with the Mac App Store version of Bitwarden. The issue really is that I just can't seem to download the app apparently as you can see below. 

![image](https://user-images.githubusercontent.com/72975473/99888082-ce2f2c00-2c17-11eb-837a-e772a58e8e91.jpeg)￼￼

I did post earlier to the sub and one of the commenters suggested I open an issue here. I believe, as I said in my post over on Reddit that the issue is likely related to the M1 architecture as I'm trying to download on a brand new MacBook Air which is where I'm experiencing this issue. Just as a point of reference this is the first app that I've come across so far to exhibit this behavior and I assumed that the app would run in Rosetta 2 without an issue but at least in my instance I am continuing to experience the inability to download the app and by proxy the Safari extension. 

Please let me know how I can be of assistance. Thanks in advance ￼

**Comment by cscharf** [comment]
@joseph-flinn , can you please give this a try through the AppStore with your new M1?

**Comment by joseph-flinn** [comment]
@cscharf Hmm...it seems to work as expected on the Macbook Pro 13 M1.

**Comment by mosidevv** [comment]
Where should I look for logs that might help me narrow down the issue?￼

**Comment by cscharf** [comment]
Hi @mosidevv , not quite sure without doing some searching around. Are you able to download and install directly from our site? https://bitwarden.com/download/

P.S. - We will be looking into native arm64 (Apple Silicon) support soon.

**Comment by mosidevv** [comment]
> Are you able to download and install directly from our site? https://bitwarden.com/download/
> 

This is normally and actually was my intended preference (actually my first preference was using homebrew but only the cli version was there) and while I do utilize and can appreciate the convenience that the App Store provides, I prefer to make it my last resort. 

I was actually under the impression that in order to get the safari extension, the app that provides the extension has to come from the App Store and can't be installed stand alone or separately which is why I ended up at the App Store. If I have that wrong which now I feel like maybe I do the answer is yes I can download and install￼ the package from the site. 
> 
> 
> P.S. - We will be looking into native arm64 (Apple Silicon) support soon.

**Comment by cscharf** [comment]
> If I have that wrong which now I feel like maybe I do the answer is yes I can download and install￼ the package from the site.

Yep, 😉 , you don't have to go through the AppStore, you'll get the Safari App Extension either way when installing the desktop client (you may have to restart Safari a couple of times/Force Quit for it to show up there).

**Comment by clayadams5226** [comment]
@mosidevv are you still having issues with this? I ran into this initially as well. Turns out I still had a stray version of Bitwarden on my Mac. If you do a search in spotlight, be sure to delete all versions of Bitwarden that appear. Once that's complete you should be able to download the App Store version without issue.
