### ISSUE TITLE
Unable to add a new User to an Org with 'Single Organization' and 'Single Sign-On Authentication' Policies enabled.

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/web#718]
## Steps To Reproduce

1. Invite a new user to your Org that has both 'Single Organization' and 'Single Sign-On Authentication' Policies enabled
2. As the user, accept the invitation
3. Confirm user in your Organization settings.
4. As the user, attempt to log into your vault

## Expected Result

User is logged into their vault and asked to setup SSO, or perhaps user is taken through the SSO flow before they are logged in.

## Actual Result

User is unable to log into their vault. Error Message "SSO Authentication is required". However, there's no way for a user to link their SSO to the Org.

## Environment

- Build Version (Bottom of the page): 2.17.0

**Comment by cscharf** [comment]
@clayadams5226 , can you please verify the `Single Organization` policy is required to hit this issue? It seems to be unrelated.
