### ISSUE TITLE
[Suggestion] Folder Position

### ISSUE THREAD

**Issue by ClarkeCC** [bitwarden/web#72]
Having the folders in the middle of the page gets a bit messing if you have a lot of them. Moving the folders to the side panel could help this.

**Comment by kspearrin** [comment]
I agree but I have not figured out a way to make this work with our other navigation items as well as supporting mobile responsiveness.

**Comment by kspearrin** [comment]
Concept on ride side menu:

![capture](https://cloud.githubusercontent.com/assets/1190944/26758631/02a7811e-48b2-11e7-9e16-7a0da4bdbc13.PNG)

**Comment by ClarkeCC** [comment]
Looks good to me! It would also work great with sub folders xD

**Comment by kspearrin** [comment]
Available in next release.

**Comment by ClarkeCC** [comment]
Amazing!
