### ISSUE TITLE
Error when registering a U2F device

### ISSUE THREAD

**Issue by AJEvans3** [bitwarden/web#724]
I know this has been brought up before but I just need some more direction. I am self hosting Bitwarden_rs in docker on my synology nas. When I try to add my Yubico security key or Solokey, I get a generic error that appears almost immediately after clicking on the "Read key" button. Ive read in the other posted issues that solution could potentially be found by looking at my configuration.

How do I go about checking my URLS to make sure they are correct? And if not, making the change? When typing in https://webvault.com/app-id.json I get the following:

{"trustedFacets":[{"ids":["http://xxxxx","ios:bundle-id:com.8bit.bitwarden","android:apk-key-hash:xxxxxxxxxx"],"version":{"major":1,"minor":0}}]}

**Comment by cscharf** [comment]
Hi @AJEvans3 , thanks for posting, however please open an issue in the bitwarden_rs repo in Github for better assistance with this issue; other than that, the web vault client URLs are hard-coded based on the self-hosted docker images when deploying an official Bitwarden self-hosted installation using our docker images; not familiar with bitwarden_rs usage/deployment/configuration.

Closing this issue now.
