### ISSUE TITLE
Password History Overflow

### ISSUE THREAD

**Issue by lschober-bw** [bitwarden/web#738]
## Describe the Bug

When viewing the password history of an item from the Web Vault, the item may overflow outside the bounds of the menu if it reaches an extreme length.

## Steps To Reproduce

1. Log in to the Web Vault
2. Select Password Generator from **Tools**
3. Set password length to 128
4. Create or edit a login item
5. Generate a password. 
6. Save.
7. Generate a new password
8. Save
9. View password history of the item.

## Expected Result

The generated password of 128 characters wraps onto a second line when viewing.

## Actual Result

The string overflows outside the bounds of the item menu.

## Screenshots or Videos

![overflow](https://user-images.githubusercontent.com/59910153/102149331-05fa4f80-3e23-11eb-899d-bad1e262302e.png)

## Environment

- Operating system: Windows 10
- Browser: Chrome
- Build Version (Bottom of the page): Version 2.17.1

**Comment by cscharf** [comment]
Resolved by #743
