### ISSUE TITLE
Export CSV doesn't escape new lines

### ISSUE THREAD

**Issue by Goblin80** [bitwarden/web#752]
## Describe the Bug

Login has a "Notes" section that accepts free text, including new line / carriage returns.

When you export the vault as CSV, these new lines ruins the whole structure of the said file.

## Steps To Reproduce

1. Create a new dummy Login item.
2. Set some dummy username and password.
3. Write some text (with some new lines) in the "Notes" section.
4. Save.
5. Go to "Settings".
6. Under "Tools", click "Export Vault".
7. Choose ".csv" as a File Format.

## Expected Result

```csv

folder,favorite,type,name,notes,fields,login_uri,login_username,login_password,login_totp
folder1,,login,name1,"this\nis just a normal\nnote written inside\nthe login\ngoes here",,https://www.dummy.me,dummy,hunter2,
folder1,,login,name2,,,http://www.dummy.me,dummy2,hunter2,
```

## Actual Result

```csv

folder,favorite,type,name,notes,fields,login_uri,login_username,login_password,login_totp
folder1,,type1,name1,"this
is just a normal
note written inside
the login
goes here",,https://www.dummy.me,dummy,hunter2,
folder1,,login,name2,,,http://www.dummy.me,dummy2,hunter2,
```

## Screenshots or Videos

No need. (unless required)

## Environment

- Operating system: 5.9.11-3-MANJARO
- Browser: Chrome 87.0.4280.88 (Official Build) (64-bit)
- Build Version (Bottom of the page): 2.17.1

## Additional Context

No need. (unless required)

**Comment by Goblin80** [comment]
This is an attempt at a simple fix in the `jslib` repository:

https://github.com/bitwarden/jslib/pull/239

**Comment by kspearrin** [comment]
The actual result looks correct to me. The note is escaped with quotes, which is per spec.

**Comment by Goblin80** [comment]
Importing the resulting CSV into another password manager (KeepassXC for example) leads to malformed database.

**Comment by kspearrin** [comment]
That sounds like an issue with the other password manager.

**Comment by cscharf** [comment]
Agreed... CSV specifications escape newlines, delimiters and text qualifiers (double double-quotes) with double quotes (text qualified). This works, for example, if you were to open that CSV in Excel or import into Sheets, etc. it would work as expected. Please report this issue to the appropriate pw manager attempting to import this format.
