### ISSUE TITLE
Favorites not synced between ios and web-based vault

### ISSUE THREAD

**Issue by OddHouseGames** [bitwarden/web#753]
The favorites section is blank on the web-based vault, even though is populated on the ios version of Bitwarden.

**Comment by SergeantConfused** [comment]
Hi there,

I've tested this on Bitwarden 2.7.0 (358) and iOS 14.3, and I was unable to reproduce this. My favourites are syncing.
Please uninstall your Bitwarden client, reboot your device, reinstall Bitwarden, and try again.
Please also check if syncing helps: https://bitwarden.com/help/article/vault-sync/

Keep me posted on your progress.


All the best,

**Comment by OddHouseGames** [comment]
Thanks and yes that fixed it!
