### ISSUE TITLE
Unable to import from F-Secure KEY

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/web#756]
## Describe the Bug

Unable to import from F-Secure KEY. Error Message "Nothing was imported"

## Steps To Reproduce

1. Export out your data from F-Secure Key as (fsk)
2. Import into Bitwarden

## Expected Result

Your data is imported into your vault

## Actual Result

There is error message "Nothing was imported". Your vault is still empty

## Environment

- Windows 10
- F-Secure Key Windows App 

## Additional Context

This is the content of fsk file, I only put 1 entry. Dummy data.

{"data":{"8d58b5cf252dd06fbd98f5289e918ab1":{"color":"#00baff","createdDate":1609302913,"creditCvv":"","creditExpiry":"","creditNumber":"","favorite":0,"modifiedDate":1609302913,"notes":"note","password":"word","passwordList":[],"passwordModifiedDate":1609302913,"rev":1,"service":"My first pass","style":"globe","type":1,"url":"https://bitwarden.com","username":"pass"}}}

**Comment by kspearrin** [comment]
Looks like they changed the format of their JSON file.

**Comment by steamwings** [comment]
For anyone else who may have this issue, I've created a simple script to help with others who may be transitioning from Key/ID Protection to Bitwarden.

https://github.com/steamwings/fsecuretobitwarden
