### ISSUE TITLE
Print Code button for recovery code does not work

### ISSUE THREAD

**Issue by hckhanh** [bitwarden/web#759]
## Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/settings/two-factor
2. Register one of the Two-step login methods
3. Click on 'View recovery code'
4. Click on 'Print Code'

## Expected Result

A PDF or some kind of backup code in the file is downloaded 

## Actual Result

Another tab opened then disappeared quickly. Nothing is downloaded or copied!

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/6380436/103411748-3290c400-4ba4-11eb-95cc-1394bc92bb3b.png)

## Environment

- Operating system: Windows 10
- Browser: Chrome 87.0.4280.88
- Build Version (Bottom of the page): 2.17.1

## Additional Context

Register a two-step login method

**Comment by apmarshall** [comment]
Relevant code appears to be [here](src/app/settings/two-factor-recovery.component.ts):

    ```
print() {
        const w = window.open();
        w.document.write('<div style="font-size: 18px; text-align: center;">' +
            '<p>' + this.i18nService.t('twoFactorRecoveryYourCode') + ':</p>' +
            '<code style="font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;">' +
            this.code + '</code></div>' +
            '<p style="text-align: center;">' + new Date() + '</p>');
        w.print();
        w.close();
    }
```

To answer immediate question, it looks to me like this should be calling the print dialog, not creating a pdf to download. However, it sounds like you are not seeing the dialog either. Wondering if the w.close() call is prematurely closing the window before the dialog has launched?

**Comment by hckhanh** [comment]
I bright good news, the solution for this feature is hear:
https://stackoverflow.com/a/17831586

Happy New Year

**Comment by iperryman-xeda** [comment]
I was able to work around the issue by just printing the page from the Chrome right click menu when the initial dialog was open, rather than clicking on "Print Code".  Not beautiful, but worked.
