### ISSUE TITLE
U2F does not work on Android Nokia 5.3

### ISSUE THREAD

**Issue by lobodol** [bitwarden/web#762]
## Describe the Bug
Good morning,

I'm trying to connect to my Bitwarden vault on my Nokia 5.3 phone, but it fails at 2FA step. I enabled FIDO U2F provider on my account, working with my [Yubikey 5 NFC](https://www.yubico.com/fr/product/yubikey-5-nfc/) and everything works fine on my desktop computer.\
Moreover, I'm using an enterprise account.

### In a browser
1. Browse to vault.bitwarden.com
2. Type my credentials
3. Submit

### In the Android app
1. Launch Bitwarden app
2. Click on "Identify"
3. Type credentials
4. Submit

## Expected Result

I expect Android to ask me how I want to use my security key: bluetooth, NFC or USB.

## Actual Result

Either on Chrome, Firefox or Android app, 2FA fails because U2F seems not supported whereas is works fine on https://demo.yubico.com/webauthn-technical/registration (via NFC or USB).

## Screenshots or Videos

Chrome result:
![bitwarden_chrome](https://user-images.githubusercontent.com/7249581/103518795-a9fc7700-4e74-11eb-970f-1e4506468125.png)

Firefox result:

![bitwarden_firefox](https://user-images.githubusercontent.com/7249581/103518805-af59c180-4e74-11eb-8d6f-5a10c1ba9315.png)

## Environment

* Android version: 10
* Chrome version: 87.0.4.4280.101
* Firefox version: 84.1.2

Regards,

**Comment by SergeantConfused** [comment]
Hi there,

FIDO U2F is not supported on all of our clients at this stage. You can learn more on this here: https://bitwarden.com/help/article/setup-two-step-login-u2f/
Since you're using a YubiKey 5, please consider adding it as a YubiKey in your 2FA configuration like so: https://bitwarden.com/help/article/setup-two-step-login-yubikey/ for a broader range of support.

I hope this helps.

All the best,

**Comment by lobodol** [comment]
Hi, thanks for your answer.

I saw [that](https://bitwarden.com/help/article/setup-two-step-login-yubikey/) but I don't want to use OTP but FIDO instead.

Do you plan to make vault.bitwarden.com supporting U2F fully soon?\
Or the Android/desktop app?

Regards,

**Comment by clayadams5226** [comment]
Hey @lobodol yes we do have it on our roadmap to make U2F available on other clients. However, we don't yet have a timeframe in place.
