### ISSUE TITLE
Release Notes are confusing for international visitors

### ISSUE THREAD

**Issue by phol** [bitwarden/web#766]
## Describe the Bug

First of all, I know this is not the proper repository to report this issue on, but thought it was the closest to the actual website.

Right now, the [Bitwarden Release Notes](https://bitwarden.com/help/article/releasenotes/) page entries are dated as "11/12/2020". To me, as a European, this is confusing: I automatically assume you mean the 11th of December. Only by looking at the previous date (09/30/2020) I can deduct that you used the US notation, but only because the second number is higher than 12. Europeans generally use day-month-year whereas in the US you seem to prefer month-day-year. That can cause confusion in communications and is slightly annoying and confusing when you're not used to this standard. 

As this is something you can never do right by choosing either one or another national format, a solution I'd like to suggest is to use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) dates instead. E.g.: 2020-11-12 and 2020-09-30.

**Comment by tgreer-bw** [comment]
Fair point! We've just adjusted it and it will be fixed in a few minutes.

**Comment by phol** [comment]
Awesome, thanks for adjusting this!

**Comment by tgreer-bw** [comment]
Issue moved to [bitwarden/help #349](https://github.com/bitwarden/help/issues/349) via [**ZenHub**](https://www.zenhub.com/)
