### ISSUE TITLE
[Suggestion] Include Site Logo in Entry

### ISSUE THREAD

**Issue by jarbro** [bitwarden/web#77]
Would be great to automatically pull in a logo from the site the password is related to similar to how lastpass/dashlane work.

Example
http://i.imgur.com/zfPfGL2.png

**Comment by craziedde** [comment]
Yes, this feature would be nice.

Here sample from Roboform/chrome extension:
https://screenpresso.com/=fpd5f#

Thanks,

Ed

**Comment by kspearrin** [comment]
This is now available with the website icons feature.
