### ISSUE TITLE
Update local "Build/Run" "Requirements" sentence in the README.md

### ISSUE THREAD

**Issue by begincalendar** [bitwarden/web#78]
Should this sentence (in the README.md):

> Unless you are running the Core API locally, you'll probably need to switch the application to target the production API. Open package.json and set production to true.

...be updated to say something along the lines of "you can set the build environment using the 'env' setting/key in package.json", or should the sentence just be removed?

**Comment by kspearrin** [comment]
Updated. Thanks.
