### ISSUE TITLE
Improve 404 error page

### ISSUE THREAD

**Issue by vachan-maker** [bitwarden/web#787]
The 404 page has Github branding. Shouldn't the branding and links be replaced with Bitwarden and https://status.bitwarden.com

Link https://vault.bitwarden.com/s for 404 error
![Screenshot_2021-01-20 Page not found · GitHub Pages](https://user-images.githubusercontent.com/65799568/105142227-5a7aa400-5b20-11eb-9f4f-c5d51d368255.png)

**Comment by cscharf** [comment]
Thanks @vachan-maker , much appreciated. Will get this on our backlog.
