### ISSUE TITLE
Copy password doesn't copy password

### ISSUE THREAD

**Issue by bh-chwo** [bitwarden/web#788]
## Describe the Bug

On an entry you can select "Copy Username/Password" and it copies the value in the clipboard, and get a little toast notification, today this feature doesn't work anymore, you can still copy the value if you edit the entry though

## Steps To Reproduce

1. Go to vault.bitwarden.com and login
2. Click on the little gear button and copy username/password

## Expected Result

The value to be copied to the clipboard and a little toast notification

## Actual Result

nothing gets copied to the clipboard

## Environment

- Operating system: Windows 10
- Browser: Edge
- Build Version (Bottom of the page): Version 87.0.664.75 (Offizielles Build) (64-Bit)

- Operating system: Android 11
- Browser: Firefox

## Additional Context

can't test any other browser, since they are not available in our infrastructure

**Comment by bh-chwo** [comment]
sorry was an error with javascript, our AV blocked the site

**Comment by desmondgc** [comment]
I can confirm the same behavior. Seems to have been introduced since version 2.18.0. Only appears to affect Edge for me. Firefox still working.

**Comment by cscharf** [comment]
@desmondgc , This was fixed/resolved yesterday afternoon and should be working. Please try a hard refresh in Edge (removing any cached items) as the version number was kept the same in the hot-fix and it should start working for you, please let us know either way.

**Comment by desmondgc** [comment]
Thanks, @cscharf - it's working now after Ctrl+F5 in Edge.

**Comment by bh-chwo** [comment]
Thx its working now 👍

**Comment by dohlin** [comment]
@cscharf I'm seeing the same behavior in my self hosted instance - what is the status of a fix for self hosted environments?  Already tried updating again but it tells me there aren't any available updates.  Thanks!

**Comment by cscharf** [comment]
Hi @dohlin , what version do you currently have installed locally? Just want to confirm you're running the latest. We'll work on reproduction of the issue but as far as I know the fix is already live; we may just need to push a new release tag and update the self-hosting scripts accordingly.

**Comment by dohlin** [comment]
@cscharf Running the latest v1.39.0 & v2.18.0 for server & web, respectively.

**Comment by dohlin** [comment]
I should also add that this definitely can/does affect FF/Chrome too at least in certain circumstances (as that's what I'm seeing).  After seeing this commit [here](https://github.com/bitwarden/web/commit/99c80828663a0c73b014e6ecb95a65dddcda64c0) I tried to copy a password for an item that already had a TOTP entry present and sure enough then it works perfectly.  Entries that don't have TOTP though you are unable to use the copy password (or copy username) options.

**Comment by cscharf** [comment]
Aah, that's definitely good to know, thanks!

**Comment by dohlin** [comment]
@cscharf Thanks for the quick hotfix build - I can confirm it resolves my issue!

**Comment by cscharf** [comment]
Awesome, it turns out the fix didn't make the "cut" when we tagged the release (bad timing), latest release tag/assets includes the fix PR.
