### ISSUE TITLE
[Bug] Generated passwords differ in strength

### ISSUE THREAD

**Issue by Limero** [bitwarden/web#79]
If you use the "Generate Password" button when adding a new login, it should always be strong enough to fill the password strength meter.

Currently, it is sometimes not enough to fill the meter.

How it should always look:
![Good](http://i.imgur.com/57QiYRx.png)
How it sometimes looks now:
![Bad](http://i.imgur.com/yF3CuJ0.png)

**Comment by kspearrin** [comment]
Generated password are truly random, so it's possible for them to differ in what we define as strength. We should probably enhance the way we define strength.

**Comment by kspearrin** [comment]
Generated length was increased so I don't think this should be a problem anymore.
