### ISSUE TITLE
Learn more link in Emergency Access page links to wrong page

### ISSUE THREAD

**Issue by yoseph1998** [bitwarden/web#793]
## Describe the Bug

In the [Emergency Access vault page](https://vault.bitwarden.com/#/settings/emergency-access), the learn more button takes you to the [page about Fingerprint Phrase](https://bitwarden.com/help/article/fingerprint-phrase/) and not to the [page about Emergency Access](https://bitwarden.com/help/article/emergency-access/). 

## Steps To Reproduce

1. While signed into the web vault, go to https://vault.bitwarden.com/#/settings/emergency-access
2. Click on 'Learn more'
3. The wrong page is linked. It links to the Fingerprint Phrase and not to the Emergency Access page.

## Expected Result

For the link to take you to a page about Emergency Access such as https://bitwarden.com/help/article/emergency-access/

## Actual Result

The link currently takes you to the page about Fingerprint Phrase https://bitwarden.com/help/article/fingerprint-phrase/

## Environment

- Operating system: All Operating Systems | tested on Linux (5.9.16-1-MANJARO)
- Browser: All browsers | tested on Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)
- Build Version (Bottom of the page): Version 2.18.0

**Comment by cscharf** [comment]
@yoseph1998 , thanks, this has been resolved!
