### ISSUE TITLE
[feature request] yubikey support

### ISSUE THREAD

**Issue by EMLVIRUS** [bitwarden/web#80]
Would like to see that yubikey is added as a 2FA method or even login credential

**Comment by kspearrin** [comment]
This is already complete and will be available next release.

**Comment by EMLVIRUS** [comment]
@kspearrin just a little question: can I use yubikey as login credential instead of without master password on PC browser? (On cell phone, use otp wire or password still)

**Comment by kspearrin** [comment]
No, YubiKey is a second factor (2FA) so it always requires your master password first.
