### ISSUE TITLE
Emergency access cannot download note attachments

### ISSUE THREAD

**Issue by jknockaert** [bitwarden/web#801]
## Describe the Bug

When view access is granted through emergency access it is not possible to download files attached to secure notes.

## Steps To Reproduce

1. Grant view emergency access to someone else (the grantee)
2. The grantee can access all vault items including secure notes, but cannot download any note attachments

## Expected Result

The grantee should be able to download note attachments.

## Actual Result

The grantee has access to the secure notes but not to the attachments.

## Environment

- Operating system: Mac OS Catalina
- Browser: Firefox 84.0.2
- Build Version (Bottom of the page): 2.18

## Additional Context

As far as I am aware the access to secure note attachments is within the scope of the emergency access feature.

**Comment by cscharf** [comment]
Hi @jknockaert , thank you for your report, our customer success team has confirmed the issue and we will be looking at this shortly.
