### ISSUE TITLE
Missing feature: Rename Collection

### ISSUE THREAD

**Issue by KeepMasterBranch** [bitwarden/web#802]
Right now, when a collection is created, it can't be renamed.

**Comment by Greenderella** [comment]
Hi @KeepMasterBranch, are you self-hosting or using our cloud solution?

If you are self-hosting please make sure your instance it's up to date: https://bitwarden.com/help/article/updating-on-premise/

If you are using our cloud solution you just need to go to the Web Vault (https://vault.bitwarden.com) click on Settings > Organizations > {YOUR ORG NAME} > Manage sub-tab > Collections > click on the desired Collection to open the edit window:

![image](https://user-images.githubusercontent.com/5418577/105684673-91bccc80-5ef5-11eb-9fbd-b61872b3d949.png)

**Comment by cscharf** [comment]
Let us know if you have any further issues with this, for now closing this issue. Thanks!

**Comment by jarnopunt** [comment]
If I try to do this to change a name of a colelction and hit 'save' I get this error:

An error has occurred.
An unhandled server error has occurred.

cloud hosted, I am not an admin, any advice?

**Comment by Greenderella** [comment]
Do you have permission to modify that collection? Maybe your user only has **Read Only** permissions for that collection:
![image](https://user-images.githubusercontent.com/5418577/112809787-ac88fa00-907a-11eb-953f-2e91a6a7c4c9.png)

**Comment by jarnopunt** [comment]
Thank you  @Greenderella. I was a manager and not an admin. As an admin it works. 

maybe the frontend message could be changed to something like "you do not have sufficient rights to do this".

thanks again!
