### ISSUE TITLE
Enabling Two-Step Login policy does not remove non-compliant Users and Mangers from the organization.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/web#806]
## Describe the Bug
Users and Manager without 2FA set on their accounts are not removed from the organization when the Two-Step Login policy is enabled.

## Steps To Reproduce
1. Create a test organization.
2. Invite and confirm a test user.
3. Go to the Business Portal and enable the Two-Step Login policy.

## Expected Result
For the test user to be removed from the organization.

## Actual Result
Test user remains a member of the organization.

## Screenshots or Videos
N/A.

## Environment

- Operating system: Windows 10 Pro.
- Browser: Chrome version 88.0.4324.104.
- Build Version: 2.18.0.

## Additional Context
N/A.

**Comment by cscharf** [comment]
@SergeantConfused , I believe the default behavior is that it should add *email* 2FA for all non-compliant users automatically, this is one of the policies that will not generally kick out non-compliant users but bring them immediately into compliance instead.

**Comment by cscharf** [comment]
Yes, non-compliant users should be deleted: https://github.com/bitwarden/server/blob/master/src/Core/Services/Implementations/PolicyService.cs#L100

**Comment by clayadams5226** [comment]
This has been tested pretty extensively and it seems to work as designed. In your example above, Has the user already been confirmed to the Org before the policy was in place? Are they an admin or owner of the org? Are they the last remaining user in the org?

**Comment by SergeantConfused** [comment]
Yes, the user in my example above was confirmed into the organization. Please note that this was tested in 2.18.0 and the behaviour changed slightly in following versions, please watch the video I've attached internally.

**Comment by eliykat** [comment]
Fixed by https://github.com/bitwarden/server/pull/1254
