### ISSUE TITLE
[Bug] Vault keep asking to "Update your Encryption Key"

### ISSUE THREAD

**Issue by taynaud** [bitwarden/web#81]
Hello,

In my vault, there is a kind of pop-up asking to update my encryption key. I have followed the link, fill my master password, get disconnected with a popup saying it is upgraded, but after reconnection it is coming back. After several tries, I think it is a bug.

Tried on firefox and chrome, on linux.

Best,

**Comment by kspearrin** [comment]
Hmm, that tells me that the update for you is failing for some reason. When you get a minute, could you join me in live dev chat so we could debug a few things and try to find out what the problem is? https://gitter.im/bitwarden/Lobby

**Comment by kspearrin** [comment]
This should be resolved now.
