### ISSUE TITLE
Can't access web vault from Brave Browser

### ISSUE THREAD

**Issue by Loudiy** [bitwarden/web#811]
## Describe the Bug

I can't access the web vault when using Brave Browser! I deactivated the ad-blocker but I still get an error.

## Steps To Reproduce

1. Go to https://vault.bitwarden.com/ using Brave Browser
2. Try to login

## Expected Result

To be redirected to my personal vault.

## Actual Result

While inspecting the network, I get a 403 status code for the request URL https://vault.bitwarden.com/api/accounts/prelogin like in the bellow image.

## Screenshot

![bitwarden error](https://user-images.githubusercontent.com/39141311/105799311-87054480-5f94-11eb-8923-22e35b4de06b.png)

## Environment

- Operating system: Ubuntu 20.04.1 LTS
- Browser: Brave Browser Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
- Build Version (Bottom of the page): [2.18.1]

## Additional Context

N/A

**Comment by kspearrin** [comment]
Try now please.

**Comment by Loudiy** [comment]
It worked perfectly now! Thank you!!
