### ISSUE TITLE
Error while hitting: Send verification code email again button with SSO login + 2FA

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/web#812]
## Describe the Bug

The button "Send verification code email again" doesn't work when signing up for an account using SSO + a 2FA method

## Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/
2. Click on Enterprise Single Sign On
3. Complete authentication process with your IDP and wait to go back https://vault.bitwarden.com/#/2fa?identifier=XXXXXXXX&sso=true
4. Click on 'Send verification code email again'
5. _An error has occurred.
The email field is required.
The MasterPasswordHash field is required._

## Expected Result

Code gets send again.

## Actual Result

Variety of Error 400

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/5418577/106164821-b1b8ee00-618a-11eb-9648-a448c931b4eb.png)

![image](https://user-images.githubusercontent.com/5418577/106164516-57b82880-618a-11eb-8ad3-c5e85f6f5b11.png)

## Environment

- Operating system: Ubuntu 20 LTS
- Browser: Chrome Version 88.0.4324.96
- Build Version (Bottom of the page): [2.18.1]

**Comment by amc950** [comment]
The same issue observed on customer call via ticket 142818 

![err](https://user-images.githubusercontent.com/71721678/123097245-f1b09400-d3fd-11eb-9502-5fd8b6f55be0.png)
![err2](https://user-images.githubusercontent.com/71721678/123097250-f37a5780-d3fd-11eb-90b4-bae11b351af6.png)
