### ISSUE TITLE
access entries from a deleted account

### ISSUE THREAD

**Issue by TimmePfeife** [bitwarden/web#816]
## Describe the Bug
Today I found in my opinion a critical security bug. To the story. I setup 2FA and everything was working fine but I forgot to note down the recovery code. Today I made a big mistake and deleted the 2FA code from my authentication app. This led me to lock myself out completely. To resolve the problem I deleted my old account and created a new one with the exact same email and password. After my big fuck up I realized that I have the vault page on my second computer always open. I logged in with my credentials and to my surprise I had still access to all of my saved entries. I noted all of them down and migrated them to the new account. Fortunately, this saved me a lot of work and frustration. However, in my opinion, this is a major security issue.

## Steps To Reproduce

1. login to your bitwarden account on multiple devices in the browser
2. enable 2FA authentication
3. delete your account on the recover-delete page
4. create a new account with the exact same credentials
5. login with the credentials on one of the other devices

## Expected Result
The account should be completely deleted and I should not have access to my entries on a different device.

## Actual Result
I could access all my old entries from a deleted account on a different device.

## Environment

- Operating system: Windows 10
- Browser: Google Chrome
- Build Version: Version 2.18.1

**Comment by kspearrin** [comment]
Are you sure you logged in on the other devices, rather than just unlocked an old offline session?

**Comment by TimmePfeife** [comment]
Honestly, I didn't know there were offline sessions until now. That could be the case but I can't tell you.

**Comment by clayadams5226** [comment]
it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
