### ISSUE TITLE
Approving an Emergency Access request from a Bitwarden account without a Name set will show __$1__ as the name.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/web#828]
## Describe the Bug
Attempting to approve an Emergency Access request from a Bitwarden account that has nothing set in their Name field will show \__$1__ as the name.

## Steps To Reproduce
1. Create a new test Bitwarden account without a name.
2. Add this Bitwarden account as an emergency contact with Takeover access.
3. Accept the invitation and request emergency access.
4. Try to approve the emergency access request.

## Expected Result
To see the email address if no name is present.

## Actual Result
\__$1__ shows up as the name.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/73389600/107874413-46795680-6ec2-11eb-847a-09683e9b4bc0.png)

## Environment
- Operating system: Windows 10 Pro 19042.804.
- Browser: Firefox 85.0.2.
- Build Version: 2.18.1.

## Additional Context
N/A.

**Comment by cscharf** [comment]
Thanks, that looks like a scary account access request message, lol. @eliykat , hopefully an easy fix.
