### ISSUE TITLE
Vulnerabilities on dependencies

### ISSUE THREAD

**Issue by rdupuis** [bitwarden/web#843]
Please find here a security report about your dependencies:
https://snyk.io/test/github/bitwarden/web

You should upgrade at least to node-forge@0.10.0, papaparse@5.2.0, jquery@3.5.0, @angular/core@11.0.5

**Comment by djsmith85** [comment]
Hi @rdupuis thank you for report. We recently made some changes to the structure of the jslib-submodule, how it integrates into the other projects, and during this process we removed but also updated a lot of dependencies.
