### ISSUE TITLE
Bitwarden Vault shows 404 when accessing vault.bitwarden.com

### ISSUE THREAD

**Issue by Veggieoskibroski** [bitwarden/web#846]
The web vault is not working.

When trying to log in, Github presents 404 page.

This can be reproduced by going to https://vault.bitwarden.com/
This should show the error

**Comment by tgreer-bw** [comment]
Thanks for reporting! The issue should be resolved now 👍

**Comment by cscharf** [comment]
All done, was my fault, thanks for the report!
