### ISSUE TITLE
Import Enpass TOTP codes

### ISSUE THREAD

**Issue by mcg** [bitwarden/web#85]
Enpass supports TOTP codes and exports them in the CSV as a "TOTP" value. I was hoping this would be imported, but sadly it's not.

**Comment by kspearrin** [comment]
Can you provide a sample file with it?

**Comment by mcg** [comment]
Yup. Will a single entry with a fake TOTP seed work?

**Comment by kspearrin** [comment]
Make it two. One with and one without totp

**Comment by mcg** [comment]
Two line csv attached, one with TOTP. This imports successfully into Bitwarden. The TOTP seed ends up in the "notes" field.

[enpass.csv.txt](https://github.com/bitwarden/web/files/1219184/enpass.csv.txt)

**Comment by kspearrin** [comment]
Yea notes is just the default for everything that isn't handled. I need to add support for totp to 1password imports as well

**Comment by kspearrin** [comment]
Done for next release: https://github.com/bitwarden/web/commit/bf382889d380fa7cb0ac9f34126632b5b6f0c58d
