### ISSUE TITLE
[Feature Request] Import paspack format

### ISSUE THREAD

**Issue by timemaster67** [bitwarden/web#87]
Would it be possible to make an importer for Passpack in the web vault ? 
Passpack can export to comma separated value, tab separated value and html format. 
if you take the csv, the default format of the export is 
name,userid,password,link,tags,notes,email

name is the entry name, link is the url to the web server, tags could be managed by your directory. 

here is an example of the file. 

```
mywebsite1,username,password,https://mywebsite.com,mytag,,
11 with coma in pass,test,"-,-",,,,
11 with email,username,,,,,email@email.com
11 with note,,,,,"This is a note with comma, cash $ only one double quotes "" and single quotes '  ok

you need to know that user can add carriage return/enter in this note field like done just above. ",
anotherwebsite,username,password,,,,
```

bugs : entry with only a name and an email are not exported. 

I am not sure how to make a parser with angular in js and boot the code, so maybe if I provide details here it could be done ?

**Comment by kspearrin** [comment]
Yes, this is possible to add. One problem I see though is their export allows the order of the columns to be in a different order depending on how you select them during export. We can only support 1 specific configuration and there is lots of room for user error.

**Comment by timemaster67** [comment]
I was thinking of supporting only one configuration. There is room for errors because of the reordering, but who are going to reorder columns ? Usually people stick to the default values and because of this, I think we'll be fine.

**Comment by kspearrin** [comment]
That seems to be the problem. There is no default values. It seems to depend on the order that you click the columns that you want to export.

**Comment by timemaster67** [comment]
??  you can ignore those columns and click on export without defining a custom order, and they will be exported in the default order I wrote above.

**Comment by kspearrin** [comment]
Hmm. Maybe I didn't do that right then. Will have to look again.

**Comment by kspearrin** [comment]
Ok, looks good. Here are instructions for export (for the web vault):

> Sign in to your account at www.passpack.com. Navigate to "Tools" > "Export". Keep the default options for the export: "Comma Separated Values" and "All entries" (you can change this one if desired). Do not change the order of the columns by selecting fields to export. Select "Continue".

**Comment by timemaster67** [comment]
Hello, 
I was able to import my data by importing passpack to lastpass, then importing lastpass to bitwarden. Therefore this chg might not be needed anymore.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
