### ISSUE TITLE
Font in "Add Login" inputs is ambiguous

### ISSUE THREAD

**Issue by softmoth** [bitwarden/web#88]
It would be nice to set a font in input boxes that is designed to make I, l, 1, |, O and 0 all very distinct. It's easy to confuse those characters for each other in many default fonts. For example:

![screenshot from 2017-08-31 18-03-22](https://user-images.githubusercontent.com/774788/29950093-c59cd084-8e76-11e7-80f2-cefc486b9138.png)

**Comment by kspearrin** [comment]
for sure. we can switch that to some monospace one.

**Comment by Diablo-D3** [comment]
Try Adobe Source Code Pro if you're allowing externally linked webfonts.

**Comment by kspearrin** [comment]
This is done for next release.

**Comment by softmoth** [comment]
Thanks!!!
