### ISSUE TITLE
updateself not pulling in latest web version

### ISSUE THREAD

**Issue by vinnyperella** [bitwarden/web#884]
## Describe the Bug

Web version 2.18.2 has been out for 14 days but the bitwarden.sh script has not been updated to reflect the new version so running updateself does nothing. I also do not see the image on dockerhub. 

## Steps To Reproduce

How can we reproduce the behavior:

1. Run "bitwarden.sh updateself" and see that the web version does not change. 

## Expected Result

The web version is updated to 2.18.2.

## Actual Result

The web version remains at 2.18.1.

## Environment

- Operating system: Linux
- Browser: [e.g. Firefox 73.0.1]
- Build Version (Bottom of the page): 2.18.1

## Additional Context

This has happened multiple times in recent memory for the web release.

**Comment by Greenderella** [comment]
Hi @vinnyperella,

The _updateself_ command only updates the main bitwarden.sh script, you must also run _update_	in order to update all containers and the database as stated here: https://bitwarden.com/help/article/updating-on-premise/

More information here: https://bitwarden.com/help/article/install-on-premise/#script-commands-reference

**Comment by anhyzer5525** [comment]
> Hi @vinnyperella,
> 
> The _updateself_ command only updates the main bitwarden.sh script, you must also run _update_ in order to update all containers and the database as stated here: https://bitwarden.com/help/article/updating-on-premise/
> 
> More information here: https://bitwarden.com/help/article/install-on-premise/#script-commands-reference

This is not working for me either as I am still stuck on the 2.18.1 version even after running those commands. I've seen Bitwarden release an update but not make it available through the update script until they feel it is safe to release. Is that the case here?

However the last time it only took them maybe 7 days. 14 days seems a little excessive.

**Comment by cscharf** [comment]
Hi @anhyzer5525 , yes that is generally our process, however this fix was a rapid release fix for the inactive 2FA report, is this the functionality you're trying to use from your local host version that's not working for you (where you need this update). We simply missed doing the self-hosted deploy as it was a rapid-turnaround patch release. We are going to be releasing 2.19.0 tomorrow and will follow up Monday with the self-hosted update across the board (that's the tentative schedule anyway). If you need that fix in the meantime you can use the `rc` version tag from Docker to pull down the upcoming release candidate early.

Closing this for now, please let me know if you need anything else; thank you!
