### ISSUE TITLE
Inactive 2FA Report - Some websites reports are missing

### ISSUE THREAD

**Issue by gradypark86** [bitwarden/web#893]
## Describe the Bug

I found that the number of websites in "Inactive 2FA Report" is less than 1Password (with the same amount of password data), lacking of website such as facebook.com, autodesk.com, jetbrains.com, linkedin.com, teamviewer.com, etc. 
After checking [#839](https://github.com/bitwarden/web/issues/839) , I searched the websites above on 2fa.directory, they are both showed support for software token. I'm so confused, why are most of the results normal, but some missing？I‘m not sure it is only abnormal to me, so I post here. Thanks a lot.

## Steps To Reproduce

1. Login to Web Vault
2. Navigate to Tools Tab
3. Click Inactive 2FA Report

## Expected Result

Inactive 2FA Report might be matching with 2fa.directory. 

## Actual Result

Inactive 2FA Report missing websites such as
- adobe.com
- autodesk.com
- cloudflare.com
- facebook.com
- jetbrains.com
- linkedin.com
- teamviewer.com

## Environment

- Operating system: Windows 10 Pro Build 20H2
- Browser: Vivaldi 3.7.2218.45 (Chrome/89.0.4389.91)
- Build Version (Bottom of the page): 2.19.0

**Comment by Blacksmoke16** [comment]
This seems to be related to the hostname comparison logic between the login's URI and the directory's URL. E.g. for Facebook, the directory has the hostname of `facebook.com`.  Having a URL of `https://facebook.com/login.php` matches, but having a URL of `https://www.facebook.com/login.php` does not.  Similarly some sites like `JetBrains` or `Wargaming` have URLs with a subdomain. E.g. `account.jetbrains.com` or `eu.wargaming.net` while the directory has `jetbrains.com` and `wargaming.net`; thus they don't match and won't show up in the list.

One possible solution would be a bit more liberal with the comparisons.  I.e. only use the base domain name, minus any `www` or subdomains.  This way `wargaming.net` from the directory would match all logins like:
* `www.wargaming.net`
* `us.wargaming.net`
* `www.eu.wargaming.net`
