### ISSUE TITLE
Download isssues

### ISSUE THREAD

**Issue by JoweriaK** [bitwarden/web#894]
My phone cannot sustain downloading some apps ,and thats why the bitwarden cannot be downloaded on my phone my phone ,when itry it fails

**Comment by Tashima42** [comment]
Is it a problem with your phone or with Bitwarden?

**Comment by JoweriaK** [comment]
I donot think its my phone but bitwarden ,good evening

**Comment by Tashima42** [comment]
Are you downloading ir through Play Store? What's you phone model and android version?

**Comment by cscharf** [comment]
HI @JoweriaK, I'm not sure I quite understand the issue you're reporting. Is it that the Bitwarden application won't complete installation on your device. You mentioned your phone can[t sustain downloading some apps... is it out of space? do you have very low bandwidth? are you running a compatible operating system? What OS / device is it? What is the error or observed behavior? Is your birthday a prime number? What steps have you tried to remedy this?

I'm going to assume if you have issues with other apps as well, this may have to do with your device, cellular provider or ISP. From that standpoint once we publish our app to the various App Stores, we generally don't have any control over how Google or Apple decides to deliver it or any issues there. I would suggest perhaps going to Apple or Android support for assistance with the specific store you're having issues with or your device manufacturer or cellular network provider who you get service through for support.

If this is a specific issue with Bitwarden (e.g. the app is downloaded and you can't login, there's an app crash, etc.) then please feel free to re-open this issue and let us know, along with the necessary pertinent detail to be able to assist you better. For now, closing this issue. Thanks!

**Comment by JoweriaK** [comment]
Yes iused Google play to download it ,and my is spark3 ,tecon type
