### ISSUE TITLE
WebSocket Token in URI

### ISSUE THREAD

**Issue by Berndinox** [bitwarden/web#899]
I'm kind of unsure if this should be treated as issue or feature-request.
Please just close / let me know, if this is the wrong place.

## Describe the Bug
After Authentication JWT Tokens are safely transfered in the HTTP Headers.
However, the WebSocket connection is established passing the TOKEN in the URI:

`wss://domain.com/notifications/hub?access_token=JWT_TOKEN `

Those, the Token may be logged on forward- and reverse-proxys as well may be cached in browsers.

## Steps To Reproduce

- Open Browser Dev-Console
- Login to Web-Vault
- Inspect HTTP Calls

## Expected Result

I'd love to see a temporary token with a short lifetime for establishing the WebSocket connection.
May also a way to disable WSS entirely could help in some usecases.

## Environment

- Operating system: Windows 10
- Browser: Chromium (ungoogled chrome)
- Web-Vault Version: 2.18.1

## Additional Context

Please see also: https://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html#query-param
There is also suggested not to pass the Token in the URI.

Any feedback welcome!

**Comment by kspearrin** [comment]
Hi,
Unfortunately, WebSockets doesn't provide a way to transmit the parameter any other way in a browser environment. This is the [suggested way](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0) to provide JWT authentication via SignalR websockets.

**Comment by Berndinox** [comment]
Hej @kspearrin  - thanks for your feedback.
