### ISSUE TITLE
Login email validator does not properly validate

### ISSUE THREAD

**Issue by pkarjala** [bitwarden/web#9]
At https://vault.bitwarden.com/#/login, when typing in an email address before submitting the form, the only requirement is that there is an "@" symbol present.  It does not actually validate whether it is a properly formatted email address before submitting to the back end and returning a validation error.

This allows submissions such as "test@test".

This also affects the registration page at https://vault.bitwarden.com/#/register

**Comment by nikoTM** [comment]
@pkarjala the thing with email validation is that no matter how you treat an email, there can be use cases that don't match your pattern. I believe that's the reason behind browsers validation of email by testing for presence of '@'. I would leave email validation as is and rely on email confirmation.

**Comment by haraldkoch** [comment]
https://hackernoon.com/the-100-correct-way-to-validate-email-addresses-7c4818f24643

**Comment by kspearrin** [comment]
Unfortunately I cannot implement email verification during registration because it causes too large of a bounce rate for users on mobile devices. Additional email regex could be added though.

**Comment by kspearrin** [comment]
Closing this since we don't plan to validate any further. Users can delete squatted accounts now as well.
