### ISSUE TITLE
"Resource not found" unexpected error creating entry while "personal vault disabled" policy active

### ISSUE THREAD

**Issue by BloodyIron** [bitwarden/web#934]
I'm in the testing/implementation/trial phase of hosted Enterprise bitwarden, hammering out UX so I can do good documentation for users/others.

Currently we have one Organization, and the policy enabled that disables "personal vault". We don't want any users to have any personal vaults, and I'm trying to find "gotchas" from a UX perspective for all classes of Users (in this case the test account has "User" class in bitwarden).

The "New User" account has their E-Mail verified. They can access the org content. The issue, however, is from when they are in the "My Vault" scope and they try to make an entry (but try to assign it to the org, and with/without a collection selected).

So, to reiterate. The user is in their own "My Vault" section, not the Org vault section.

User clicks on "Add Item", then puts in the cred info. Under Ownership the appropriate Org is already selected, however two issues arise.

1. If no Collection is selected, an error pops up "you must select a collection"
2. If I check one, or more, Collections, the New User gets the error "An error has occurred. Resource not found."

From a UX perspective, this could easily trip people up if they don't realise they are not in the Org scope. If the same steps are performed with the browser plugin, the user receives no error if they select a Collection, but if they select no Collection they are told to select a Collection.

So the UX is inconsistent, and prone to breakage here.

Honestly this would be avoidable if the whole "My Vault" page, tab in top left, and such was completely removed when the "personal vault disabled" policy is active, and the user just went directly into the Org scope every time.

**Comment by BloodyIron** [comment]
I'd also like to add, when the "personal vault disabled" policy is active. The user can still create a "folder" in their personal vault, which no other user (not even the org) can see the folder. This too should really not be possible.

Also, when using the web interface, and try to make a Org entry from the Personal Vault scope, and the Org is set to owner, they can select the folder to put it in (even if they fail). HOWEVER, this personal folder is not present as an option when using the browser extension.

Ooof, this is all tough to explain, I hope I was precise enough! D:

**Comment by eliykat** [comment]
I was able to reproduce the "Resource not found" error, however it was fixed after the user logged out and logged back in again after being confirmed by the admin/owner. I was then able to create org items from the personal vault page. I think it may just be a minor syncing issue, unrelated to the Personal Ownership policy. Can you try this and see if it fixes the error? 

I expect we leave the My Vault page there because the user may have personal items from before they joined the org / before the org activated the policy.

I agree that users should not be able to create folders if the Personal Ownership policy is active, we can triage this as a minor bug. Ideally the server should reject the create folder request with the appropriate error message to the user.

I also agree that the folder dropdown should be disabled or hidden if Personal Ownership policy is active. It appears for me in both browser and web clients.

**Comment by BloodyIron** [comment]
1. I didn't do a full log-out (as I'm just responding to this now, you know... Mondays, lol). However my test user "timed out" and required their master password to log back in. After doing so, (was not prompted for SSO), I was able to create an entry for the Org from the "My Vault" scope (as in, I initiated it there), and saved it successfully to a collection in the org. So I did not get "resource not found". I think you're right this might be a session thing. I may retest this, not yet sure.
2. I can appreciate there are scenarios where users with their own content _may_ join an org that disables personal vault, however in the scenario we want to build, we want to only have users that are new accounts, tied to our own auth system, hopefully to fully disable (even from a UX perspective) the personal vault. We namely want to do this because we see this as a possible way to lose information, as org master password resets for users is still on the roadmap and not in the tool.

If there's any appetite for a mechanism to "fully disable" the "my vault" visibility and such, we would likely be interested. But, my opinion may change over time as we use it. I'm just trying to find areas where a fresh user might get tripped up, and then either find a way to mitigate that, or report it here. (or something like that).

**Comment by cscharf** [comment]
Also, let us know whether the "Resource not found" error was resolved or reproducible... @eliykat , let's ensure in the meantime that if the real issue is the user is not yet confirmed when trying to save the item to the collection that an appropriate error message is displayed instead to help eliminate confusion.

**Comment by BloodyIron** [comment]
Hey @cscharf I'm trying to provide as useful feedback as I can! :D 

I can totally appreciate the "My Vault" aspect is something to think long and hard about, and either way can take a good amount of time if any action is to be taken on it. This is me trying to convey it as soon as I could so that process can start as early as possible (whenever that is).

In regards to folders, I got muddled about it earlier on. I see now that it is personal, and in my additional testing I haven't observed any issues with it. So I'm not concerned about users making folders at all. I do see that this is more akin to personal favourites and stuff like that, I had a completely different idea of it in my head, until I tested it further, hehe.

In regards to the trial-phase, while we are still doing that, at this point I really haven't found anything that is preventing us from moving forward. There's areas for improvement (multi-org management, I do see it on the roadmap btw), but nothing that's a blocker at this time. There really is a lot of maturity to this ecosystem!

**Comment by BloodyIron** [comment]
@cscharf in regards to the "Resource not found", we'll have to see how that pans out as more users use the system. As @eliykat outlined, it does look to be some sort of temporary issue (caching? session?). So I'm less concerned about that currently.

I do think that reviewing what error message is presented might be worth doing, but at this point I can't recall enough of the parameters of that scenario to recommend specific language (sorry).

**Comment by cscharf** [comment]
Excellent, thanks @BloodyIron  and I'll let Thomas look further into the error scenario and message (since he was able to reproduce it).

I don't remember seeing anything on the email validation, however if you posted something I'll see it once I get caught up (it is indeed Monday 😉 ).  Thanks again!

**Comment by BloodyIron** [comment]
@cscharf well maybe I didn't post it or something. The idea is, I invite an SSO user (we don't have directory sync just yet), they click, create new bitwarden account, login with SSO creds. But they can't access org content until they validate E-Mail (and until I "approve" them, but let's put that aside for now). And the UX workflow for E-Mail validation is a small reminder in the top right (to start the process).

While a good number of users might notice the top right reminder, I anticipate some users might miss it. This might result in IT helpdesk calls, or whatnot.

What I think might be a good idea is to make it so when they first login successfully there's a front-and-center "hey please validate your email, click here" kind of thing. Namely in the vein of being extremely self-obvious ;)

**Comment by cscharf** [comment]
That helps, thanks!

**Comment by BloodyIron** [comment]
This is probably safe to close at this point. Unsure if still active as a "bug" or whatever, but it's also not relevant to my/our use-case anyways since we have master password reset now :)
