### ISSUE TITLE
Unable to scroll the page when folders are filtered

### ISSUE THREAD

**Issue by ple103** [bitwarden/web#94]
I currently have 30+ folders in my vault. When I select a folder to filter by, I am no longer able to scroll down the page to access the remaining folders/filters.

This can be reproduced by doing the following:
1. Create a dozen or so folders
2. Resize your browser so that some of the filters in the right-hand filter panel go out of view
3. Click on a filter

Result: You will be unable to scroll the page to view the other filters.

**Comment by kspearrin** [comment]
Can you provide a screenshot or something? I'm a bit confused.

**Comment by ple103** [comment]
I've PM'ed you on Gitter with a GIF to demo the issue.

**Comment by kspearrin** [comment]
Resolved in next release.
