### ISSUE TITLE
The Copy-Password button in the Web Vault can place an escaped password in the clipboard

### ISSUE THREAD

**Issue by trevoranderson** [bitwarden/web#95]
I've got a password with a '&' character in it. If I use the webpage UI to copy it into the clipboard, it places an escaped version '\&amp;' in the password. If I show the password with "Toggle Password", it shows the sequence as well.

This problem doesn't exist in the browser extension (Firefox version 1.16.3) or IOS extension (1.9.0 (17)) from my preliminary investigation.

**Comment by trevoranderson** [comment]
Got it to happen on the Firefox extension, but on a different site.

**Comment by kspearrin** [comment]
Not able to reproduce. Are you sure you didnt import them that way from LastPass due to their export bug? See warning here: https://help.bitwarden.com/article/import-from-lastpass/
