### ISSUE TITLE
Changing port?

### ISSUE THREAD

**Issue by StarNumber12046** [bitwarden/web#950]
## Describe the Bug

How to change the port of the localhost? (example: from 8080 to 5000)

## Steps To Reproduce

Nothing
## Expected Result

Nothing here

## Actual Result

I have another server (one in 8080 and this but I cannot start BitWarden)

## Environment

- Operating system: linux [e.g. Windows 10, Mac OS Catalina]
- Browser: Brave [e.g. Firefox 73.0.1]
- Build Version 2.13.0 (Bottom of the page): [2.13.0]

**Comment by SergeantConfused** [comment]
Hi there,

Please check out this: https://www.reddit.com/r/Bitwarden/comments/eicb3s/selfhosting_bitwarden_config_issues/ and this: https://community.bitwarden.com/t/change-bitwarden-port/2698 and please direct future support inquiries here: https://bitwarden.com/contact/

Best wishes,

**Comment by eliykat** [comment]
Thanks @SergeantConfused for providing some useful links. If you're still having trouble, please reach out to our customer success team on the link provided. We use GitHub issues as a place to track bugs and other development related issues, so this issue will now be closed.
