### ISSUE TITLE
Edit modal closes without prompting or saving changes 

### ISSUE THREAD

**Issue by briancontario** [bitwarden/web#956]
## Describe the Bug

When using the Bitwarden Vault website and doing the following:
* creating a new item in the ADD ITEM modal ... or
* editing an existing item in the EDIT ITEM modal

If the user:
* clicks the mouse ANYWHERE outside of the modal window 
* clicks the Cancel button

The result is that the modal closes and ALL OF THE CHANGES or new data entered into the modal is discarded without warning or prompting the user for confirmation.

## Steps To Reproduce

USE CASE 1
1. Log in to Bitwarden Vault website https://vault.bitwarden.com
2. Click Add Item button
3. Enter any data into text fields in the ADD ITEM modal dialog
4. Click the cursor anywhere outside of the modal dialog window
5. Modal window disappears and clicking ADD ITEM again does not show any of the data previously entered.

USE CASE 2
1. Log in to Bitwarden Vault website https://vault.bitwarden.com
2. Click on existing item
3. Enter or change any data in text fields in the EDIT ITEM modal dialog
4. Click the cursor anywhere outside of the modal dialog window
5. Modal window disappears and opening the same item does not show any of the data previously entered or changed.

USE CASE 3
1. Log in to Bitwarden Vault website https://vault.bitwarden.com
2. Click on existing item
3. Enter or change any data in text fields in the EDIT ITEM modal dialog
4. Click the Cancel button without clicking the Save button
5. Modal window disappears and opening the same item does not show any of the data previously entered or changed.

## Expected Result

In all Use Cases the user should be prompted to confirm that they want to leave the modal dialog and discard the changes made.  If the user does not confirm they should be returned to the modal and allowed to Save the data.

## Actual Result

The modal closes and all new or changed data is lost.

## Screenshots or Videos

Not applicable

## Environment

- Operating system: Windows 10
- Browser: Firefox 88.0
- Build Version (Bottom of the page): 2.19.0

This was not tested in other browsers, but it is likely to behave the same in other browsers.

## Additional Context

Desktop app prompts you with this:
![image](https://user-images.githubusercontent.com/1538142/116943252-2f384280-ac41-11eb-9132-8f7190e50391.png)

**Comment by eliykat** [comment]
This would be a minor feature improvement but I think we can probably track it here as a bug. I'm open to PRs if anyone wants to dig into it. It would be nice if we could open a swal2 dialog (using `platformUtilsService.showDialog`) warning the user about unsaved changes, similar to how the desktop app works.

**Comment by dltmurphy** [comment]
Would it be worthwhile preventing the user clicking off the modal to close it and instead requiring them to click save or cancel rather than providing a prompt? if the save and cancel button is prominent on screen it should provide a good user experience for people

**Comment by eliykat** [comment]
@dltmurphy that could also work - the add/edit screen is already in a modal, so another popup modal over the top of that might be messy. Instead we could just force the user to explicitly click save or cancel.

**Comment by eliykat** [comment]
I don't think any prompt is necessary if the user clicks the Cancel button - that's a deliberate choice to exit out of the add/edit dialog. This is also how desktop works - it only prompts you if you try to navigate away, not if you click Cancel. So I'd keep the scope of this issue to your use cases 1 & 2.

**Comment by dltmurphy** [comment]
It's out of my current coding skills, but the submit button could be disabled and grey until the input fields are interacted with. That way the user can visibly see if they have edited anything at a glance before cancelling and losing their changes. At least then there's no need for additional popups and the user has a somewhat good experience with the process. What do you think?

I'll take a look at learning how to do it this week

**Comment by eliykat** [comment]
@dltmurphy I just don't think there's any need for it. If the user has clicked the cancel button then that is an intentional action that we should respect, and disabling the Save button if the form is untouched is not really going to achieve anything. I don't think we need to over-engineer this one :)
