### ISSUE TITLE
Importing from KeePass2

### ISSUE THREAD

**Issue by christianreiss** [bitwarden/web#96]
Hey,

running current (28.09.2017) docker image. Got it running, went straight for the "import from Keepass" option. Issue is that my Keepass Vault has several files stored which raises the "maximum length of 1000 chars" import error. One of Keepass'es killer feature is the ability to hold license files/files in general, which will get exported as well.

The issue is that my KeePass vault has 500+ entries with several files in between. The Export function is not really letting me apply any sorts of filter so the importing side should be able to deal with this. I am pretty sure I am not the only one having this issue :)

Suggestion: Either cleanly handle such issues or let the import continue even after failure.

Cheers!
-Christian.

**Comment by kspearrin** [comment]
Can you let me know what fields in the XML file contain these files? We will have to skip them so that they are not added to notes during import.

**Comment by christianreiss** [comment]
It's at:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<KeePassFile>
  <Meta>       
    <Binaries>
	<Binary ID="0" Compressed="True">H4sIAAAAAAAAA22SuZaqQABEc75ics[...]
```

**Comment by kspearrin** [comment]
@christianreiss We do not import anything from KeePassFile > Meta. We only pull entries from KeePassFile > Root so it has to be something in there.

**Comment by kspearrin** [comment]
Closing since no more information was provided.

**Comment by christianreiss** [comment]
I forgot to answer & solve: I indeed had a single password with 1000+ chars. Deleted that, import worked like a charm. Tracking it down was evil, tho.
