### ISSUE TITLE
Unexpected error has occurred' when you click on Log in

### ISSUE THREAD

**Issue by lrefra** [bitwarden/web#977]
Describe the Bug

When trying to log into the web vault on Google Chrome or other browser, you receive a red error banner stating 'An unexpected error has occurred' when you click on Log in.
With the app, same problem.

Steps To Reproduce
1) Go to the web vault.
2) Enter your credentials.
3) Click on Log In.

Expected Result
To log into the web vault.

Actual Result
Receive a red error banner stating 'An unexpected error has occurred'.

Screenshots or Videos

![error](https://user-images.githubusercontent.com/48889474/118409159-779f2980-b65f-11eb-992a-a80726bf7877.png)

Environment

- Operating system: Windows 10 21H1
- Browser: Chrome 90, Edge 90
- Build Version (Bottom of the page): Last

**Comment by eliykat** [comment]
Hi @lrefra, it appears that the recent server update has locked a few people out of their accounts if they were using a premium 2FA option and their premium subscription lapsed. You didn't mention your subscription type, but I'm assuming it's probably related. Either way, please contact our Customer Success team here: https://bitwarden.com/contact/. You can include a link to this issue in your message content. They can help you re-gain access to your vault. (If anyone reading this has the same issue, please do the same.) Our dev team are working on a more permanent fix in the meantime.
