### ISSUE TITLE
Notifications on Bitwarden send are not placed correctly.

### ISSUE THREAD

**Issue by luximus-hunter** [bitwarden/web#996]
## Describe the Bug
Notifications on Bitwarden send are not placed correctly.

## Steps To Reproduce
- Create send text item in desktop app
- Open link in browser
- Click copy value
- See notification lower than needed

## Expected Result
Notification in the top right, fully.

## Actual Result
Notification is about one notification too low.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/49814847/119841756-60392980-bf06-11eb-80fe-40988e383200.png)

## Environment

- Operating system: Windows 10 Pro 21H1 19043.985
- Browser: Firefox Developer Edition 89.0b15 (64-bit)
- Build Version (bottom of the page): Version 2.20.3

**Comment by sov-j** [comment]
FWIW, I have tested this on 
Operating system: Windows 8.1 x64
Browser: Firefox 90.0.1 (64-bit), Chrome Version 91.0.4472.164 (Official Build) (64-bit)
Build Version (bottom of the page): Version 2.21.1

and I can reproduce it.

**Comment by dltmurphy** [comment]
The toast notifications for `.toast-top-right` is set to 76px on all pages. I think the lack of a header makes it look lower than it needs to be. @eliykat I can add a fix into my current PR that sets `.layout_frontend .toast-top-right: 20px` (taking the height of the header out) if the design team are happy with the change?

**Comment by eliykat** [comment]
@dltmurphy I think this is a good fix, but please submit a separate PR for it. (Probably after we've merged dark mode, otherwise you'll hit merge conflicts.) Dark mode already has so many changes, this would get lost if we included it in there and had to debug later.
